import {chromium} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({executablePath:'/home/kevin/.cache/ms-playwright/chromium-1246/chrome-linux64/chrome',args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1512,height:1050}}),results=[],errors=[];
page.setDefaultTimeout(3500);page.on('pageerror',e=>errors.push(e.message));
const state=()=>page.evaluate(()=>window.hybrid.getState());
async function closeParameters(){if((await state()).contextView)await page.keyboard.press('Escape');}
async function parameter(view){const st=await state();if(st.draft)await page.locator('#score-edit').press('Enter');if(['variant','add','order'].includes(view)&&!(await state()).chordId){const z=await state(),b=z.model.sections.flatMap(x=>x.bars).find(b=>b.id===z.selected[0]);if(b?.chords.length)await page.locator(`[data-chord="${b.chords[0].id}"]`).click();}if((await state()).contextView!==view)await page.locator(`button[data-action="context:${view}"]`).filter({visible:true}).first().click();}

const part=async(id='verse')=>(await state()).model.sections.find(s=>s.id===id);
const button=a=>page.locator(`button[data-action="${a}"]`).filter({visible:true}).first();
const action=a=>button(a).click();
const assert=(ok,message)=>{if(!ok)throw Error(message);};
const chord=c=>page.locator(`[data-chord="${c.id}"]`);
const select=async(b)=>{await closeParameters();await page.locator(`[data-select-bar="${b.id}"]`).click({position:{x:3,y:5}});};
async function test(name,fn){try{await page.setViewportSize({width:1512,height:1050});await page.goto(new URL('prototype.html',import.meta.url).href);await page.evaluate(()=>document.fonts.ready);await fn();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:e.message});}}
await test('Single selected measure exposes duplicate and delete once above bar',async()=>{const b=(await part()).bars[4];await select(b);assert(await page.locator(`[data-action="duplicate-bar:${b.id}"]`).count()===1&&await page.locator(`[data-action="delete-bar:${b.id}"]`).count()===1,'duplicate corner actions');const bar=await page.locator(`[data-bar="${b.id}"]`).boundingBox(),corner=await page.locator('.flat-bar-tools').boundingBox();assert(corner.y+corner.height<=bar.y,'row not above bar');});
await test('Chord selection preserves corner actions and direct duplication copies full bar',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).click();assert(await page.locator('.bar-corner-actions').count()===1,'chord lacks corner actions');await action('duplicate-bar:'+b.id);const p=await part();assert(p.bars.length===9&&p.bars[5].chords.map(c=>c.name).join(' ')==='D A/C#','corner copy does not duplicate full measure');assert(!(await state()).draft,'copy also starts editing');});
await test('Corner delete removes measure with selected chord and supports undo',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).click();await action('delete-bar:'+b.id);assert((await part()).bars.length===7&&!await page.locator(`[data-bar="${b.id}"]`).count(),'corner delete targets wrong measure');await action('undo');assert((await part()).bars[4].id===b.id,'corner delete undo loses measure');});
await test('Corner background click neither edits chord nor changes selection',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).click();await page.locator('.bar-corner-actions').click({position:{x:1,y:1}});assert((await state()).chordId===b.chords[1].id&&!(await state()).draft,'corner background activates editor');});
await test('Number strip remains selectable while corner buttons are shown',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).click();await page.locator(`[data-select-bar="${b.id}"]`).click({position:{x:4,y:8}});assert(!(await state()).chordId&&!(await state()).draft&&(await state()).selected[0]===b.id,'number strip covered by corner buttons');});
await test('First and second chord clicks retain selection/editing contract with icons',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).click();assert(!(await state()).draft,'first click opens editor');await chord(b.chords[1]).click();assert(await page.locator('#score-edit').inputValue()==='D A/C#','second click fails full line');assert(!await page.locator('.bar-corner-actions,.context-tools').count(),'buttons overlay text input');});
await test('Icon buttons all contain hidden SVG and nonempty accessible labels',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).click();const invalid=await page.locator('button.icon-button').evaluateAll(items=>items.filter(el=>!el.querySelector('svg[aria-hidden="true"]')||!el.getAttribute('aria-label')?.trim()||!el.dataset.tooltip?.trim()).map(el=>el.dataset.action));assert(!invalid.length,'icon buttons lack labels or SVG: '+invalid.join(','));});
await test('Mouse hover displays readable floating tooltip and clears it on click',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).click();await button('context:variant').hover();assert((await page.locator('[role="tooltip"]').textContent())==='Variantackord','hover lacks correct tooltip');const tip=await page.locator('[role="tooltip"]').boundingBox();assert(tip.x>=0&&tip.x+tip.width<=1512,'tooltip clipped');await action('context:variant');assert(!await page.locator('[role="tooltip"]').count(),'click leaves stale tooltip');});
await test('Keyboard focus shows icon tooltip and Tab clears or updates it',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).click();await page.keyboard.press('Tab');await button('context:variant').focus();await page.waitForTimeout(120);assert((await page.locator('[role="tooltip"]').textContent())==='Variantackord','keyboard focus lacks tooltip');await page.keyboard.press('Tab');assert(!await page.locator('[role="tooltip"]').count()||(await page.locator('[role="tooltip"]').textContent())!=='Variantackord','tooltip remains for old focus');});
await test('Variant inline fields omit voice, align chord and pass, retain live multi chord editing',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).click();await action('context:variant');assert(!await page.locator('#context-variant-voice').count(),'inline voice field remains');const chordBox=await page.locator('#context-variant').boundingBox(),passBox=await page.locator('#context-variant-pass').boundingBox();assert(Math.abs(chordBox.y-passBox.y)<2&&passBox.x>chordBox.x,'variant not compact inline');await parameter('variant');await page.locator('#context-variant').pressSequentially('G Am');await page.locator('#context-variant-pass').fill('3');await page.locator('#context-variant-following').check();const c=(await part()).bars[4].chords[1];assert(c.variant==='G Am'&&c.variantPass===3&&c.variantFollowing,'compact variant loses metadata');});
await test('Context variant omits voice and preserves field labels',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).click();await parameter('variant');assert(!await page.locator('#context-variant-voice').count(),'voice remains');assert(await page.locator('label[for="context-variant"]').textContent()==='Ackord'&&await page.locator('label[for="context-variant-pass"]').textContent()==='Spelas gång','field labels unclear');});
await test('Add and order parameters do not duplicate Write button',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).click();for(const view of ['add','order']){await parameter(view);assert(await page.locator('[data-action="context-edit"]').count()===1,'duplicate write in '+view);assert(!await page.locator('[data-action*="more"],[data-action="context-tool:chord"]').count(),'old submenu remains');assert(await page.locator('[data-chord-grid]').count()===1,'shared placement missing');}});
await test('Desktop global column collapse preserves tab and score selection',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).click();await action('tab:song');const before=await state(),width=await page.locator('.scene').evaluate(el=>el.getBoundingClientRect().width);await action('toggle-panel');assert(!(await page.locator('#editor-panel').isVisible())&&(await state()).panelCollapsed,'panel visible');assert(await page.locator('.scene').evaluate(el=>el.getBoundingClientRect().width)>width+200,'score not expanded');await action('toggle-panel');const after=await state();assert(await page.locator('#editor-panel').isVisible()&&after.tab===before.tab&&after.chordId===before.chordId&&JSON.stringify(after.selected)===JSON.stringify(before.selected),'expansion loses context');});
await test('Desktop close returns keyboard focus to persistent expand control',async()=>{await action('tab:form');await action('close-panel');assert((await state()).panelCollapsed,'desktop close does not collapse');assert(await button('toggle-panel').evaluate(el=>el===document.activeElement),'desktop close loses focus');await action('toggle-panel');assert((await state()).tab==='form','expand resets form tab');});
await test('Collapsed panel reopens for requested global Settings tab',async()=>{await action('toggle-panel');await action('tab:settings');assert(!(await state()).panelCollapsed&&await page.locator('#editor-panel').isVisible()&&(await state()).tab==='settings','settings remains hidden');});
await test('Whole part has source actions and subset has bulk actions',async()=>{await action('select-part:verse');assert(!await page.locator('.flat-bar-tools').count(),'part has measure actions');const p=await part();await select(p.bars[1]);for(let i=2;i<=3;i++)await page.locator(`[data-bar-check="${p.bars[i].id}"]`).check();assert(await page.locator('[data-action="duplicate-bars"]').count()&& !await page.locator('[data-action^="duplicate-bar:"]').count(),'subset gets single-bar copy');});
for(const width of [320,375,430])await test(`Mobile ${width}: corner targets and chords remain reachable without overflow`,async()=>{await page.setViewportSize({width,height:800});const p=await part();for(const i of [0,3,7]){const b=p.bars[i];await chord(b.chords[0]).click();const corner=await page.locator('.bar-corner-actions').boundingBox(),bar=await page.locator(`[data-bar="${b.id}"]`).boundingBox();assert(corner.x>=0&&corner.x+corner.width<=width,'corner actions overflow');assert(corner.y<bar.y+15,'mobile corner actions not at top');const target=chord(b.chords[0]);await target.click();assert((await state()).draft?.barId===b.id,'corner intercepts chord second click');await page.locator('#score-edit').press('Escape');await select(b);assert(!(await state()).draft,'number strip begins editing');}assert(await page.evaluate(()=>document.documentElement.scrollWidth)<=width,'mobile horizontal overflow');});
for(const width of [320,375,430])await test(`Mobile ${width}: menu toggle is reachable through popup navigation and close`,async()=>{await page.setViewportSize({width,height:800});const p=await part();await select(p.bars[0]);const before=await state();await action('toggle-panel');assert((await state()).panelOpen&&await page.locator('#editor-panel').isVisible(),'mobile toggle does not open popup');assert(await button('toggle-panel').getAttribute('aria-expanded')==='true','toggle state wrong');const box=await button('toggle-panel').boundingBox();assert(await button('toggle-panel').evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}),'scrim intercepts toggle');assert(box.x>=0&&box.x+box.width<=width,'mobile toggle clipped');for(const tab of ['form','song'])await page.locator('.panel-nav button[data-action="tab:'+tab+'"]').click();assert((await state()).panelOpen,'navigation closes popup');await action('toggle-panel');assert(!(await state()).panelOpen&&!(await page.locator('#editor-panel').isVisible()),'toggle cannot close popup');assert(JSON.stringify((await state()).selected)===JSON.stringify(before.selected),'toggle changes score selection');await action('toggle-panel');await action('close-panel');assert(await button('toggle-panel').evaluate(el=>el===document.activeElement),'popup close loses toggle focus');});
await test('Resize between desktop and mobile updates toggle name and state',async()=>{await action('toggle-panel');await page.setViewportSize({width:375,height:800});await page.waitForFunction(()=>document.querySelector('[data-action="toggle-panel"]').getAttribute('aria-label')==='Öppna menyn');assert(await button('toggle-panel').getAttribute('aria-label')==='Öppna menyn','mobile toggle has desktop label');await action('toggle-panel');await page.setViewportSize({width:1512,height:1050});await page.waitForFunction(()=>document.querySelector('[data-action="toggle-panel"]').getAttribute('aria-label')==='Fäll in menykolumn');assert(await button('toggle-panel').getAttribute('aria-label')==='Fäll in menykolumn','desktop toggle has mobile label');assert(await page.locator('#editor-panel').isVisible(),'resize leaves column hidden');});
await test('Selection and second click do not move the marked chord or number strip',async()=>{const b=(await part()).bars[4],target=chord(b.chords[1]);const before=await target.boundingBox();await target.click();const after=await target.boundingBox();assert(Math.abs(before.y-after.y)<1,'selection shifts chord under pointer');await target.click({position:{x:10,y:10}});assert((await state()).draft?.barId===b.id,'second click misses after selection');});
await test('Parentheses tooltip changes and selected state is visible',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).click();assert(await button('context-parentheses').getAttribute('data-tooltip')==='Inom parentes','initial parenthesis hint wrong');await action('context-parentheses');assert(await button('context-parentheses').getAttribute('data-tooltip')==='Ta bort parentes'&&await button('context-parentheses').getAttribute('aria-pressed')==='true','active parenthesis hint/state wrong');});
await test('Deletion confirmation uses distinct icons for keep and remove',async()=>{await closeParameters();await action('select-part:verse');await closeParameters();await action('delete-part:verse');const keep=await button('part-delete-cancel').innerHTML(),remove=await button('part-delete-confirm').innerHTML();assert(keep!==remove&&remove.includes('M3 6h18'),'confirmation and cancellation use same icon');await action('part-delete-cancel');assert((await part()).bars.length===8,'cancel removes part');});
await test('Changing base chord opens required native variant-choice dialog',async()=>{const b=(await part()).bars[0];await chord(b.chords[0]).click();await parameter('variant');await page.locator('#context-variant').fill('Am');await closeParameters();await action('toggle-panel');await chord(b.chords[0]).click();await page.locator('#score-edit').fill('G');await page.locator('#score-edit').press('Enter');assert(await page.locator('.variant-choice-dialog').evaluate(d=>d.open),'required variant choice hidden');await action('variant-choice:keep');assert((await part()).bars[0].chords[0].name==='G'&&(await part()).bars[0].chords[0].variant==='Am','choice loses variant');});
await test('Double click after contextual variant edit retains pointer position',async()=>{const b=(await part()).bars[0];await chord(b.chords[0]).click();await parameter('variant');await page.locator('#context-variant').fill('Dm');await closeParameters();await select(b);const target=chord(b.chords[0]),before=await target.boundingBox();await target.dblclick();assert((await state()).draft?.barId===b.id,'doubleclick misses');const after=await page.locator('#score-edit').boundingBox();assert(Math.abs(before.y-after.y)<8,'toolbar shifts score');});
await writeFile(new URL('compact-verification.json',import.meta.url),JSON.stringify({errors,results},null,2)+'\n');console.log(JSON.stringify({errors,results},null,2));await browser.close();if(errors.length||results.some(r=>!r.passed))process.exitCode=1;
