import {chromium} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({executablePath:'/home/kevin/.cache/ms-playwright/chromium-1246/chrome-linux64/chrome',args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1512,height:1050}}),results=[],errors=[];
page.setDefaultTimeout(3500);page.on('pageerror',e=>errors.push(e.message));
const state=()=>page.evaluate(()=>window.hybrid.getState());
async function closeParameters(){if((await state()).contextView)await page.keyboard.press('Escape');}
async function parameter(view){const st=await state();if(st.draft)await page.locator('#score-edit').press('Enter');if(['variant','add','order'].includes(view)&&!(await state()).chordId){const z=await state(),b=z.model.sections.flatMap(x=>x.bars).find(b=>b.id===z.selected[0]);if(b?.chords.length)await page.locator(`[data-chord="${b.chords[0].id}"]`).click();}if((await state()).contextView!==view)await page.locator(`button[data-action="context:${view}"]`).filter({visible:true}).first().click();}

const part=async(id='verse')=>(await state()).model.sections.find(s=>s.id===id);
const action=a=>page.locator(`[data-action="${a}"]`).filter({visible:true}).first().click();
const assert=(ok,message)=>{if(!ok)throw Error(message);};
const chord=c=>page.locator(`[data-chord="${c.id}"]`);
const select=async(b)=>{await closeParameters();await page.locator(`[data-select-bar="${b.id}"]`).click({position:{x:3,y:5}});};
const area=b=>page.locator(`[data-chord-area="${b.id}"]`);
const edit=async(b,text)=>{await closeParameters();await area(b).click({position:{x:4,y:5}});await page.locator('#score-edit').fill(text);await page.locator('#score-edit').press('Enter');};
async function range(first,last){await closeParameters();const bars=(await part()).bars;await page.locator(`[data-select-bar="${bars[first].id}"]`).click({position:{x:3,y:5}});for(let i=first+1;i<=last;i++)await page.locator(`[data-bar-check="${bars[i].id}"]`).check();}
async function test(name,fn){try{await page.setViewportSize({width:1512,height:1050});await page.goto(new URL('prototype.html',import.meta.url).href);await page.evaluate(()=>document.fonts.ready);await fn();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:e.message});}}
async function signedBar(){const b=(await part()).bars[4];await select(b);await action('repeat:both');await action('context:rhythm');await action('attack:1');return (await part()).bars[4];}
await test('Chord first click selects and second click edits the full measure',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).click();assert(!(await state()).draft&&(await state()).chordId===b.chords[1].id,'first click edits');await chord(b.chords[1]).click();assert(await page.locator('#score-edit').inputValue()==='D A/C#','second click lacks full line');assert(!await page.locator('.context-tools').count(),'context overlaps editing');});
await test('Context caption and parameter background clicks retain chord selection',async()=>{const b=(await part()).bars[4];await chord(b.chords[0]).click();await page.locator('.flat-chord-tools .context-caption').click();await parameter('variant');await page.locator('.parameter-body').click({position:{x:2,y:2}});assert(!(await state()).draft&&(await state()).chordId===b.chords[0].id,'context background activates measure');});
await test('Parentheses toggle targets selected chord and is undoable',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).click();await action('context-parentheses');const changed=(await part()).bars[4];assert(changed.chords[1].parenthetical&&!changed.chords[0].parenthetical,'parentheses affect wrong chord');await action('undo');assert(!(await part()).bars[4].chords[1].parenthetical,'parentheses undo fails');});
await test('Delete chord retains other chords, signs, rhythm and restores variant on undo',async()=>{const b=await signedBar();await closeParameters();await chord(b.chords[1]).click();await action('context:variant');await parameter('variant');await page.locator('#context-variant').fill('G Am');await action('context-delete-chord');const changed=(await part()).bars[4];assert(changed.chords.length===1&&changed.chords[0].name==='D'&&changed.repeatStart&&changed.repeatEnd&&changed.attacks.length===1,'delete loses other contents');await action('undo');assert((await part()).bars[4].chords[1].variant==='G Am','undo loses removed variant');});
await test('Last chord removal creates editable empty measure',async()=>{const b=(await part()).bars[0];await chord(b.chords[0]).click();await action('context-delete-chord');assert(!(await part()).bars[0].chords.length,'last chord not removed');await area(b).click({position:{x:4,y:5}});assert(await page.locator('#score-edit').inputValue()==='','empty editor missing');});
await test('Add group inserts after selection without replacing later chord',async()=>{const b=(await part()).bars[4];await chord(b.chords[0]).click();await action('context:add');await parameter('add');await action('recent:G');const changed=(await part()).bars[4];assert(changed.chords.map(c=>c.name).join('|')==='D|G|A/C#'&&changed.chords[1].start===2,'insertion replaces or misplaces');});
await test('Variant typing retains trailing spaces, caret and live model',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).click();await action('context:variant');const input=page.locator('#context-variant');await parameter('variant');await input.pressSequentially('G ');assert(await input.inputValue()==='G ','trailing space disappears during rerender');assert(await input.evaluate(el=>el.selectionStart)===2,'caret jumps');await input.pressSequentially('Am');assert((await part()).bars[4].chords[1].variant==='G Am','multi chord variant not live');});
await test('Continuous variant typing is one undo and metadata remains live',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).click();await action('context:variant');const before=(await state()).pastCount;await parameter('variant');await page.locator('#context-variant').pressSequentially('G Am');await page.locator('#context-variant-pass').fill('3');assert(!await page.locator('#context-variant-voice').count(),'removed voice field remains');await page.locator('#context-variant-following').check();const c=(await part()).bars[4].chords[1];assert(c.variant==='G Am'&&c.variantPass===3&&c.variantFollowing,'metadata not live');assert((await state()).pastCount===before+1,'one continuous context edit creates multiple undos');await action('undo');assert(!(await part()).bars[4].chords[1].variant,'undo leaves partial variant');});
await test('Invalid variant retains last valid model and recovery retains raw input',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).click();await action('context:variant');await parameter('variant');await page.locator('#context-variant').fill('G Am');await parameter('variant');await page.locator('#context-variant').fill('G ?');assert((await part()).bars[4].chords[1].variant==='G Am','invalid variant persisted');assert((await page.locator('#context-variant-feedback').textContent()).includes('Skriv'),'invalid input lacks feedback');await parameter('variant');await page.locator('#context-variant').fill('(G Am)');assert((await part()).bars[4].chords[1].variant==='(G) (Am)','variant recovery fails');});
await test('Parameter toggle, close and Escape retain chord selection',async()=>{const b=(await part()).bars[4];await chord(b.chords[0]).click();await action('context:add');await action('context:add');assert(!(await state()).contextView,'toggle fails');await action('context:variant');await action('close-context');assert(!(await state()).contextView,'close fails');await action('context:variant');await page.keyboard.press('Escape');assert(!(await state()).contextView&&(await state()).chordId===b.chords[0].id,'Escape clears selection');});
await test('Changing selected chord closes stale group and restores static card position',async()=>{const b=(await part()).bars[4];await chord(b.chords[0]).click();const box=await page.locator('.context-tools').boundingBox(),bar=await page.locator(`[data-bar="${b.id}"]`).boundingBox();await action('context:add');await chord(b.chords[1]).click();const next=await page.locator('.context-tools').boundingBox(),nextBar=await page.locator(`[data-bar="${b.id}"]`).boundingBox();assert(!(await state()).contextView&&Math.abs(box.x-bar.x-next.x+nextBar.x)<1&&Math.abs(box.y-bar.y-next.y+nextBar.y)<1,'stale group or moving card');});
await test('Opening parameter popover does not move direct chord row buttons',async()=>{const b=(await part()).bars[4];await chord(b.chords[0]).click();const box=await page.locator('[data-action="context-edit"]').boundingBox(),card=await page.locator('.flat-chord-tools').boundingBox();await parameter('variant');const next=await page.locator('[data-action="context-edit"]').boundingBox(),nextCard=await page.locator('.flat-chord-tools').boundingBox();assert(Math.abs(box.x-card.x-next.x+nextCard.x)<1&&Math.abs(box.y-card.y-next.y+nextCard.y)<1,'popover moves row');});
await test('Placing chord preserves keyboard focus after rerender',async()=>{const b=(await part()).bars[4],c=b.chords[1],a='chord-step:'+c.id+':1';await chord(c).click();await page.locator('[data-chord-grid]').selectOption('16');await page.locator(`[data-action="${a}"]`).focus();await page.keyboard.press('Enter');assert((await part()).bars[4].chords[1].start===3.25,'keyboard placement does not work');assert(await page.locator(`[data-action="${a}"]`).evaluate(el=>el===document.activeElement),'placement loses focus');});
await test('Clearing chord row preserves signs and rhythm and supports undo',async()=>{const b=await signedBar();await select(b);await action('context-clear-chords');const empty=(await part()).bars[4];assert(!empty.chords.length&&empty.repeatStart&&empty.repeatEnd&&empty.attacks.length===1,'clear erases metadata');await action('undo');assert((await part()).bars[4].chords.length===2,'clear undo fails');});
await test('Takt insertion and duplication retain intended placement and select copy',async()=>{const b=(await part()).bars[4];await select(b);await action('context-insert-bar');let p=await part();assert(p.bars.length===9&&p.bars[5].chords.length===0,'empty takt not inserted after');assert((await state()).draft?.barId===p.bars[5].id,'inserted blank bar not opened');await page.locator('#score-edit').press('Escape');await select(p.bars[4]);await action('duplicate-bar:'+b.id);p=await part();assert(p.bars.length===10&&p.bars[5].chords[1].name==='A/C#'&&(await state()).selected[0]===p.bars[5].id,'duplicate misplaced or unselected');});
await test('Range exposes only range actions and places repeat endpoints correctly',async()=>{await range(1,3);assert(!await page.locator('.context-tools [data-action="context-edit"]').count(),'range offers chord edit');await action('repeat:both');let p=await part();assert(p.bars[1].repeatStart&&p.bars[3].repeatEnd&&!p.bars[2].repeatStart&&!p.bars[2].repeatEnd,'repeat endpoints wrong');await action('context-remove-repeat');p=await part();assert(!p.bars.slice(1,4).some(b=>b.repeatStart||b.repeatEnd),'repeat removal incomplete');});
await test('Range houses apply, conflict cancel and replace preserve correct spans',async()=>{await range(1,3);await action('context-house:1');let p=await part();assert(p.bars[1].houseSpan.barIds.length===3,'house span wrong');await range(2,4);await action('context-house:2');assert(!!(await state()).pendingHouse,'overlap silently overwritten');await page.locator('.context-warning [data-action="house-cancel"]').click();assert((await part()).bars[1].houseSpan.number==='1','cancel destroys original');await action('context-house:2');await page.locator('.context-warning [data-action="house-replace"]').click();p=await part();assert(!p.bars[1].houseSpan&&p.bars[2].houseSpan.number==='2','replace leaves overlapping house');await action('house-remove');assert(!(await part()).bars.some(b=>b.houseSpan),'remove misses house');});
await test('Custom house closes to direct row and uses typed numbers',async()=>{await range(1,2);await action('context:house-number');await action('close-context');assert(!(await state()).contextView&&await page.locator('[data-action="repeat:both"]').count(),'direct reprise row missing');await action('context:house-number');await page.locator('#context-house-number').fill('1, 3');await action('context-house-apply');assert((await part()).bars[1].houseSpan.number==='1, 3','custom house ignored');});
await test('Range deletion confirms, moves repeat signs and undo restores whole span',async()=>{await range(1,3);await action('repeat:both');await action('context:delete-range');assert((await part()).bars.length===8,'opening confirmation deletes');await action('context-delete-range');let p=await part();assert(p.bars.length===5&&p.bars[1].repeatStart&&p.bars[1].repeatEnd,'range deletion fails transfer');await action('undo');p=await part();assert(p.bars.length===8&&p.bars[1].repeatStart&&p.bars[3].repeatEnd,'range undo only restores one bar');});
await test('Entire part range deletion leaves a blank bar and single undo restores',async()=>{await range(0,7);await action('context:delete-range');await action('context-delete-range');assert((await part()).bars.length===1&&!(await part()).bars[0].chords.length,'whole range does not become blank');await action('undo');assert((await part()).bars.length===8,'whole range undo incomplete');});
await test('Whole section exposes source actions without ambiguous local tools',async()=>{await action('select-part:verse');assert(!await page.locator('.flat-bar-tools,.flat-chord-tools,[data-action="context:rhythm"],[data-action="context:variant"]').count(),'whole part shows local tools');assert(await page.locator('[data-action="context-copy-part:verse"]').count(),'source action missing');});
await test('Copy part remaps bars, chords and houses with independent source',async()=>{await range(1,3);await action('context-house:1');const original=await part();await closeParameters();await action('select-part:verse');await action('context-copy-part:verse');const s=await state(),copy=s.model.sections.find(x=>x.id===s.selectedPart);assert(copy.name==='Vers · kopia'&&copy.bars.length===8,'copy missing');assert(copy.bars.every((b,i)=>b.id!==original.bars[i].id&&b.chords.every((c,j)=>c.id!==original.bars[i].chords[j].id)),'copy shares IDs');assert(copy.bars[1].houseSpan.barIds.every(id=>copy.bars.some(b=>b.id===id)),'copied house points at original');await edit(copy.bars[0],'C');assert((await part()).bars[0].chords[0].name==='D','copy edit leaks to original');assert((await state()).model.form[2].source===copy.id,'copy not inserted after source');});
await test('New part inserts four blank measures and can be renamed and edited',async()=>{await closeParameters();await action('select-part:verse');await action('context-new-part:verse');let s=await state(),copy=s.model.sections.find(x=>x.id===s.selectedPart);assert(copy.bars.length===4&&copy.bars.every(b=>!b.chords.length),'new part has music');await action('rename-part:'+copy.id);await page.locator('#part-name').fill('Brygga');await page.locator('#part-name').press('Enter');await edit(copy.bars[0],'C G');assert((await part(copy.id)).name==='Brygga'&&(await part(copy.id)).bars[0].chords.length===2,'new part cannot edit');});
await test('Context reuse applies settings and linked title updates propagate',async()=>{await closeParameters();await action('select-part:verse');await closeParameters();await action('select-part:verse');await action('context-reuse:verse');let s=await state(),reuse=s.model.form.find(f=>f.id===s.selectedReuse);assert(reuse.reuse&&reuse.source==='verse','reuse not linked');await page.locator('#context-reuse-count').fill('3');await page.locator('#context-reuse-instruction').fill('Instrumentalt');await action('context-reuse-apply');assert((await state()).model.form.at(-1).count===3,'context count not saved');await closeParameters();await action('select-part:verse');await action('rename-part:verse');await page.locator('#part-name').fill('Brygga');await page.locator('#part-name').press('Enter');assert((await page.locator('.reuse-score').textContent()).includes('Brygga × 3'),'rename label stale');});
await test('Context reuse detach preserves settings and becomes independent',async()=>{await closeParameters();await action('select-part:verse');await closeParameters();await action('select-part:verse');await action('context-reuse:verse');const id=(await state()).selectedReuse;await page.locator('#context-reuse-count').fill('3');await page.locator('#context-reuse-instruction').fill('Solo');await action('context-reuse-apply');await action('detach-reuse');const s=await state(),block=s.model.form.find(f=>f.id===id),own=s.model.sections.find(p=>p.id===block.source);assert(!block.reuse&&block.source!=='verse'&&block.count===3&&block.instruction==='Solo','detach loses settings');assert(!s.selectedReuse&&(s.selectedPart===own.id||s.selected.includes(own.bars[0].id)),'detached source not selected');await edit(own.bars[0],'C');assert((await part()).bars[0].chords[0].name==='D','detach editing affects original');});
await test('Removing contextual reuse retains source and undo restores reuse',async()=>{await closeParameters();await action('select-part:verse');await closeParameters();await action('select-part:verse');await action('context-reuse:verse');await action('reuse-remove');assert((await state()).model.form.length===3&&(await part()).bars.length===8,'reuse removal affects source');assert(!(await state()).selectedReuse,'removed reuse remains selected');await action('undo');assert((await state()).model.form.at(-1).reuse,'reuse undo fails');});
for(const width of [375,430])await test(`Mobile ${width}: chord and bar groups fit and expanded card clears next row`,async()=>{await page.setViewportSize({width,height:900});let p=await part();for(const i of [0,3,7]){await select(p.bars[i]);const card=await page.locator('.flat-bar-tools').boundingBox();assert(card.x>=0&&card.x+card.width<=width,'context card clipped horizontally');const next=i===7? page.locator('#section-chorus .section-title'):page.locator('#section-verse .score-row').nth(Math.floor(i/4)+1);const below=await next.boundingBox();assert(card.y+card.height<=below.y,'expanded menu overlaps next row');await action('break:row');assert((await part()).bars[i].rowBreak,'mobile layout action fails');p=await part();}assert(await page.evaluate(()=>document.documentElement.scrollWidth)<=width,'mobile page overflows');});
await test('Mobile variant and reuse parameters open focused native dialog for scope',async()=>{await page.setViewportSize({width:375,height:800});const b=(await part()).bars[4];await chord(b.chords[1]).click();await parameter('variant');assert(await page.locator('#context-popup').evaluate(d=>d.open)&&await page.locator('#context-variant').evaluate(el=>el===document.activeElement),'variant dialog focus missing');await page.locator('#context-variant').fill('G Am');assert((await part()).bars[4].chords[1].variant==='G Am','wrong variant chord');await action('close-context');await action('select-part:verse');await closeParameters();await action('select-part:verse');await action('context-reuse:verse');assert(await page.locator('#context-popup').evaluate(d=>d.open)&&await page.locator('#context-reuse-count').evaluate(el=>el===document.activeElement),'reuse dialog not focused');});
await test('Desktop final row expanded variant and submenu controls remain reachable',async()=>{const b=(await part('chorus')).bars[7];await chord(b.chords[0]).click();await action('context:variant');await parameter('variant');await page.locator('#context-variant').fill('G Am');await page.locator('#context-variant-following').scrollIntoViewIfNeeded();const box=await page.locator('#context-variant-following').boundingBox(),scene=await page.locator('.scene').boundingBox();assert(box.y>=scene.y&&box.y+box.height<=scene.y+scene.height,'final row variant unreachable');assert(await page.locator('#context-variant-following').evaluate(el=>document.elementFromPoint(el.getBoundingClientRect().x+5,el.getBoundingClientRect().y+5)===el),'final row checkbox occluded');});
await test('Range row disables single-bar parameters and omits chord controls',async()=>{await range(1,3);assert(!await page.locator('.flat-chord-tools,[data-action="context-edit"]').count(),'range exposes text edits');assert(await page.locator('[data-action="context:rhythm"]').isDisabled()&&await page.locator('[data-action="context:changes"]').isDisabled(),'range enables local parameters');});
await test('Full measure recent-add chips disable without removing existing chord context',async()=>{const b=(await part()).bars[4];await edit(b,'D G A Bm');const full=(await part()).bars[4];await chord(full.chords[1]).click();await action('context:add');const chips=page.locator('.context-tools [data-action^="recent:"]');assert(await chips.count()>0&&await chips.evaluateAll(items=>items.every(el=>el.disabled)),'full bar offers invalid insert');assert((await state()).chordId===full.chords[1].id,'full bar loses selection');});
await test('Direct break actions target first range measure and remove correctly',async()=>{await range(1,3);await action('break:page');let p=await part();assert(p.bars[1].pageBreak&&!p.bars[3].pageBreak,'range break wrong edge');await action('break:remove');assert(!(await part()).bars[1].pageBreak,'break remove fails');});
await test('Mobile last-column chord placement and grid remain fixed and focused',async()=>{await page.setViewportSize({width:375,height:800});const b=(await part()).bars[6],c=b.chords[1];await chord(c).click();const card=await page.locator('.context-tools').boundingBox();const expanded=await page.locator('.context-tools').boundingBox();assert(card.x===expanded.x&&expanded.x>=0&&expanded.x+expanded.width<=375,'mobile chord expansion shifts or clips card');await page.locator('[data-chord-grid]').focus();await page.locator('[data-chord-grid]').selectOption('16');assert(await page.locator('[data-chord-grid]').evaluate(el=>el===document.activeElement),'grid change loses focus');assert((await state()).chordId===c.id&&!(await state()).draft,'grid triggers text edit');});
await test('Selecting reuse then source clears reuse context and restores correct source actions',async()=>{await closeParameters();await action('select-part:verse');await closeParameters();await action('select-part:verse');await action('context-reuse:verse');const id=(await state()).selectedReuse;await action('select-part:chorus');assert(!(await state()).selectedReuse&&(await state()).selectedPart==='chorus'&&!(await state()).contextView,'source keeps reuse context');assert(await page.locator('[data-action="context-reuse:chorus"]').count()&&!await page.locator('.reuse-actions').count(),'wrong actions remain visible');await action('context-select-reuse:'+id);assert((await state()).selectedReuse===id&&!await page.locator('.part-actions').count(),'reuse leaves source controls');});
await writeFile(new URL('contextual-verification.json',import.meta.url),JSON.stringify({errors,results},null,2)+'\n');console.log(JSON.stringify({errors,results},null,2));await browser.close();if(errors.length||results.some(r=>!r.passed))process.exitCode=1;
