import {chromium} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({executablePath:'/home/kevin/.cache/ms-playwright/chromium-1246/chrome-linux64/chrome',args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1512,height:1050}}),results=[],errors=[];
page.setDefaultTimeout(3500);page.on('pageerror',e=>errors.push(e.message));
const state=()=>page.evaluate(()=>window.hybrid.getState());
async function closeParameters(){if(await page.locator('#variant-edit').count())await page.locator('#variant-edit').press('Enter');if((await state()).contextView)await page.keyboard.press('Escape');}
async function finishVariant(){if(await page.locator('#variant-edit').count())await page.locator('#variant-edit').press('Enter');}
async function variantSettings(owner){await finishVariant();await page.locator(`[data-action="variant-settings:${owner}"]`).filter({visible:true}).first().click();}

const part=async(id='verse')=>(await state()).model.sections.find(s=>s.id===id);
const button=a=>page.locator(`button[data-action="${a}"]`).filter({visible:true}).first();
const action=a=>button(a).click();
const assert=(ok,message)=>{if(!ok)throw Error(message);};
const chord=c=>page.locator(`[data-chord="${c.id}"]`);
const select=async(b)=>page.locator(`[data-select-bar="${b.id}"]`).click({position:{x:3,y:5}});
const check=b=>page.locator(`[data-bar-check="${b.id}"]`);
async function subset(indices,id='verse'){const p=await part(id);await select(p.bars[indices[0]]);for(const i of indices.slice(1))await check(p.bars[i]).check();return p;}
async function test(name,fn){try{await page.setViewportSize({width:1512,height:1050});await page.goto(new URL('prototype.html',import.meta.url).href);await page.evaluate(()=>document.fonts.ready);await fn();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:e.message});}}
await test('No ellipsis or obsolete music menu anywhere',async()=>{const p=await part();await chord(p.bars[4].chords[1]).click();assert(!await page.locator('[data-action*="more"],[data-action^="tool:"],[data-action="tab:music"],[data-action^="range-"]').count(),'obsolete menu actions remain');await action('select-part:verse');assert(!await page.locator('[data-action*="more"]').count(),'part still has More');await closeParameters();await action('select-part:verse');await action('context-reuse:verse');assert(!await page.locator('[data-action*="more"]').count(),'reuse still has More');});
await test('Bar actions share one line above bar and chord actions one separate line below',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).click();const bar=await page.locator(`[data-bar="${b.id}"]`).boundingBox(),upper=await page.locator('.bar-corner-actions').boundingBox(),lower=await page.locator('.chord-tools').boundingBox();assert(upper.y+upper.height<=bar.y+2&&lower.y>=bar.y+bar.height,'actions on wrong side');const upperYs=await page.locator('.bar-corner-actions button').evaluateAll(items=>items.map(el=>Math.round(el.getBoundingClientRect().y))),lowerYs=await page.locator('.chord-tools button').evaluateAll(items=>items.map(el=>Math.round(el.getBoundingClientRect().y)));assert(new Set(upperYs).size===1&&new Set(lowerYs).size===1,'actions wrap into multiple rows');});
await test('One-line bar row exposes common actions without opening submenus',async()=>{await select((await part()).bars[4]);for(const a of ['context-insert-bar','context:rhythm','context:changes','repeat:both','repeat:start','repeat:end','context-house:1','context-house:2','context:house-number','break:row','break:page','context-clear-chords'])assert(await button(a).count()===1,'missing direct action '+a);});
await test('One-line chord row exposes placement, variants, add, order, parentheses, NC and deletion',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).click();for(const a of ['context-edit','context:variant','context:add','context:order','context-parentheses','nc','context-delete-chord'])assert(await button(a).count()===1,'missing chord action '+a);assert(await page.locator('[data-chord-grid]').count()===1,'missing resolution');});
await test('Checkboxes initially appear for all bars and narrow to selected section',async()=>{assert(await page.locator('[data-bar-check]').count()===20,'unselected checkboxes missing');const b=(await part()).bars[4];await check(b).check();assert((await state()).selected[0]===b.id,'check does not select');const outside=await page.locator('[data-bar-check]').evaluateAll(items=>items.filter(el=>!el.closest('#section-verse')).length);assert(!outside,'cross-section checkboxes remain');});
await test('Checking arbitrary bars produces sorted subset and does not fill gaps',async()=>{const p=await subset([4,1,6]);assert((await state()).selected.join(',')===[p.bars[1].id,p.bars[4].id,p.bars[6].id].join(','),'checkboxes create range or unsorted order');assert(!(await state()).draft,'checking opens chord edit');});
await test('Unchecking middle selected measure retains remaining noncontiguous selection',async()=>{const p=await subset([1,2,3]);await check(p.bars[2]).uncheck();assert((await state()).selected.join(',')===[p.bars[1].id,p.bars[3].id].join(','),'uncheck fills gap or discards others');});
await test('Unchecking final selected measure clears selection and reveals all sections',async()=>{const p=await subset([1]);await check(p.bars[1]).uncheck();assert(!(await state()).selected.length&&await page.locator('[data-bar-check]').count()===20,'final uncheck leaves selection');});
await test('Checkboxes hide while typing and during whole part or reuse selection',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).dblclick();assert(!await page.locator('[data-bar-check]').count(),'typing has checkboxes');await page.locator('#score-edit').press('Escape');await action('select-part:verse');assert(!await page.locator('[data-bar-check]').count(),'part has checkboxes');await closeParameters();await action('select-part:verse');await action('context-reuse:verse');assert(!await page.locator('[data-bar-check]').count(),'reuse has checkboxes');});
await test('Gapped subset disables contiguous repeat and houses while keeping basic bulk actions',async()=>{await subset([1,3]);for(const a of ['repeat:both','context-house:1','context-house:2','context:house-number'])assert(await button(a).isDisabled(),'gaps allow '+a);for(const a of ['duplicate-bars','context-clear-chords'])assert(!(await button(a).isDisabled()),'gaps block useful '+a);});
await test('Filling selection gap enables continuous repeat and exact house span',async()=>{const p=await subset([1,3]);await check(p.bars[2]).check();assert(!(await button('repeat:both').isDisabled()),'gap remains disabled');await action('repeat:both');await action('context-house:1');const next=await part();assert(next.bars[1].repeatStart&&next.bars[3].repeatEnd&&next.bars[1].houseSpan.barIds.length===3,'continuous markup incorrect');});
await test('Bulk clear affects selected subset only and undo restores whole subset',async()=>{const p=await subset([1,3,5]);await action('context-clear-chords');const after=await part();assert([1,3,5].every(i=>!after.bars[i].chords.length)&&[0,2,4,6,7].every(i=>JSON.stringify(after.bars[i])===JSON.stringify(p.bars[i])),'clear affects unselected gaps');await action('undo');assert(JSON.stringify((await part()).bars)===JSON.stringify(p.bars),'bulk clear undo incomplete');});
await test('Bulk duplicate copies only selected subset in written order',async()=>{const p=await subset([1,3,5]);await action('duplicate-bars');const after=await part();assert(after.bars.length===11,'duplicate fills gaps');assert(after.bars.slice(6,9).map(b=>b.chords.map(c=>c.name).join(' ')).join('|')===[1,3,5].map(i=>p.bars[i].chords.map(c=>c.name).join(' ')).join('|'),'duplicates wrong content or order');assert((await state()).selected.length===3,'copy selection wrong');await action('undo');assert((await part()).bars.length===8,'bulk duplicate undo incomplete');});
await test('Checkbox on second section replaces selection without cross-section subset',async()=>{const p=await subset([1,3]);const b=(await part('intro')).bars[2];await select(b);assert((await state()).selected.join(',')===String(b.id),'second section leaves cross-part subset');assert(await page.locator('#section-verse [data-bar-check]').count()===0,'oldsection boxes remain');});
await test('Parameter groups switch directly and opening them changes no music',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).click();const before=JSON.stringify((await state()).model);for(const a of ['context:add','context:order','context:rhythm','context:changes','context:house-number']){await action(a);assert(JSON.stringify((await state()).model)===before,'opening '+a+' mutates music');assert((await state()).contextView===a.slice(8),'wrong open group '+a);}assert(await page.locator('#context-house-number').count()===1,'last parameter form missing');});
await test('Order popover edits chord starts, order and resolution',async()=>{const b=(await part()).bars[4];await chord(b.chords[1]).click();await action('context:order');await action('resolution:16');await page.locator(`[data-start="${b.chords[1].id}"]`).selectOption('1.25');await action('chord-up:'+b.chords[1].id);const after=(await part()).bars[4];assert(after.chords[0].name==='A/C#'&&after.chords[0].start===1,'order swaps slot positions');});
await test('Local changes require single bar and retain local model after popup closure',async()=>{const b=(await part()).bars[4];await select(b);await action('context:changes');await page.locator('#local-key').selectOption('E');await action('local-apply');await page.keyboard.press('Escape');assert((await part()).bars[4].key==='E','local change lost');await check((await part()).bars[6]).check();assert(await button('context:changes').isDisabled(),'bulk local changes ambiguous');});
for(const width of [320,375,430])await test(`Mobile ${width}: action rows remain single line with horizontal overflow confined to row`,async()=>{await page.setViewportSize({width,height:800});const b=(await part()).bars[4];await chord(b.chords[1]).click();for(const sel of ['.bar-corner-actions','.chord-tools']){const box=await page.locator(sel).boundingBox();assert(box.x>=0&&box.x+box.width<=width,'row extends beyondviewport '+sel);const ys=await page.locator(sel+' button').evaluateAll(items=>items.map(el=>Math.round(el.getBoundingClientRect().y)));assert(new Set(ys).size===1,'wrappedrow '+sel);}assert(await page.evaluate(()=>document.documentElement.scrollWidth)<=width,'horizontal page overflow');});
for(const width of [375,430])await test(`Mobile ${width}: variant text stays inline and metadata popup retains owner scope`,async()=>{await page.setViewportSize({width,height:800});const b=(await part()).bars[4];await chord(b.chords[1]).click();await action('context:variant');assert(await page.locator('#variant-edit').isVisible()&&!await page.locator('#context-popup').count(),'mobile variant text uses popup');await page.locator('#variant-edit').fill('G Am');await variantSettings(b.chords[1].id);assert(await page.locator('#context-popup').evaluate(d=>d.open),'metadata dialog missing');assert((await part()).bars[4].chords[1].variant==='G Am'&&!(await part()).bars[4].chords[0].variant,'mobile loses chord scope');await page.keyboard.press('Escape');assert(!(await state()).contextView&&(await state()).chordId===b.chords[1].id,'popup close loses selection');});
await test('Global column contains Form and Song while header and Settings are absent',async()=>{await action('tab:form');const sidebar=page.locator('#editor-panel');assert(!await sidebar.locator('[data-action^="tool:"],[data-action="tab:music"],#local-key,#variant-edit,#context-rhythm').count(),'local tools remain global column');await action('tab:song');assert(await page.locator('#song-title').isVisible(),'song controls missing');assert(!await page.locator('.header,[data-action="tab:settings"],input[name="text-behavior"]').count(),'removed header/settings remain');});
await test('Escape closes one parameter group and keeps subset selection',async()=>{const p=await subset([1,2,3]);await action('context:house-number');await page.keyboard.press('Escape');assert(!(await state()).contextView&&(await state()).selected.join(',')===p.bars.slice(1,4).map(b=>b.id).join(','),'Escape clears subset');});
await test('Checkbox clicking while chord selected changes to measure scope without editing',async()=>{const p=await part(),b=p.bars[4];await chord(b.chords[1]).click();await check(p.bars[6]).check();assert(!(await state()).chordId&&!(await state()).draft&&(await state()).selected.length===2,'checkbox preserves ambiguous chord scope');});
await test('Gapped subset deletion preserves unselected measures and transfers repeat signs with one undo',async()=>{const p=await subset([1,3,5]);await action('repeat:start');await action('repeat:end');const before=await part();await action('context:delete-range');assert((await part()).bars.length===8,'confirmation opening deletes');await action('context-delete-range');const after=await part();assert(after.bars.map(b=>b.id).join(',')===[0,2,4,6,7].map(i=>p.bars[i].id).join(','),'gapped delete removes intervening bars');assert(after.bars[1].repeatStart&&after.bars[3].repeatEnd,'repeat signs not moved to next surviving bar');await action('undo');assert(JSON.stringify((await part()).bars)===JSON.stringify(before.bars),'gapped deletion undo incomplete');});
await test('Horizontal bar strip position remains after direct layout changes',async()=>{await page.setViewportSize({width:375,height:800});const b=(await part()).bars[4];await select(b);const strip=page.locator('[data-strip="bar"]');await strip.evaluate(el=>el.scrollLeft=el.scrollWidth);await button('break:page').scrollIntoViewIfNeeded();const before=await strip.evaluate(el=>el.scrollLeft);assert(before>0,'bar strip does not overflow for meaningful scroll test');await action('break:page');assert((await part()).bars[4].pageBreak,'layout action not applied');assert(Math.abs(await strip.evaluate(el=>el.scrollLeft)-before)<2,'bar strip resets horizontal position');});
await test('Horizontal mobile chord strip position remains after parenthesis toggle',async()=>{await page.setViewportSize({width:375,height:800});const b=(await part()).bars[4];await chord(b.chords[1]).click();const strip=page.locator('[data-strip="chord"]');await strip.evaluate(el=>el.scrollLeft=el.scrollWidth);await button('context-parentheses').scrollIntoViewIfNeeded();const before=await strip.evaluate(el=>el.scrollLeft);assert(before>0,'mobile chord strip has no meaningful scroll');await action('context-parentheses');assert((await part()).bars[4].chords[1].parenthetical,'parenthesis toggle failed');assert(Math.abs(await strip.evaluate(el=>el.scrollLeft)-before)<2,'chord strip resets horizontal position');});
async function selectClippedChord(){
 await page.setViewportSize({width:1512,height:740});
 const b=(await part()).bars[4],c=b.chords[1],before=JSON.stringify((await state()).model);
 await chord(c).evaluate(el=>{const scene=document.querySelector('.scene');scene.scrollTop+=el.getBoundingClientRect().y+el.getBoundingClientRect().height/2-(scene.getBoundingClientRect().bottom-45);});
 await page.waitForTimeout(100);
 const box=await chord(c).boundingBox(),point={x:box.x+box.width/2,y:box.y+box.height/2};
 await page.mouse.click(point.x,point.y);
 const selectedBox=await chord(c).boundingBox(),scene=await page.locator('.scene').boundingBox(),tools=await page.locator('.flat-chord-tools').boundingBox();
 assert(tools.y+tools.height>scene.y+scene.height,'fixture does not clip selected chord tools');
 assert(Math.abs(selectedBox.y-box.y)<1,'initial selection moves chord');
 return {b,c,before,point,box:selectedBox};
}
await test('Clipped chord remains stationary after 800ms hover and a slow second click edits same bar',async()=>{
 const fixture=await selectClippedChord();await page.waitForTimeout(800);
 const after=await chord(fixture.c).boundingBox();
 assert(Math.abs(after.x-fixture.box.x)<1&&Math.abs(after.y-fixture.box.y)<1,'delayed reveal moves chord under stationary pointer');
 assert((await state()).chordId===fixture.c.id&&!((await state()).draft),'waiting changes selection or edits');
 await page.mouse.click(fixture.point.x,fixture.point.y);
 assert(await page.locator('#score-edit').isVisible()&&(await state()).draft.barId===fixture.b.id,'slow second click does not edit original measure');
 assert(JSON.stringify((await state()).model)===fixture.before,'slow second click changes music');
});
await test('Leaving clipped chord reveals its row without changing model or selected chord',async()=>{
 const fixture=await selectClippedChord();await page.waitForTimeout(800);await page.mouse.move(4,4);await page.waitForTimeout(650);
 const scene=await page.locator('.scene').boundingBox(),tools=await page.locator('.flat-chord-tools').boundingBox();
 assert(tools.y>=scene.y-1&&tools.y+tools.height<=scene.y+scene.height+1,'chord tools remain clipped after pointer leaves: '+JSON.stringify({scene,tools}));
 const current=await state();assert(current.chordId===fixture.c.id&&current.selected.join(',')===String(fixture.b.id)&&!current.draft&&!current.contextView,'reveal changes editing scope');
 assert(JSON.stringify(current.model)===fixture.before,'reveal changes music');
});
await writeFile(new URL('flat-verification.json',import.meta.url),JSON.stringify({errors,results},null,2)+'\n');console.log(JSON.stringify({errors,results},null,2));await browser.close();if(errors.length||results.some(r=>!r.passed))process.exitCode=1;
