import {createRequire} from 'node:module';
const require=createRequire('/home/kevin/ai/workspaces/harmisgenerator/package.json');
const {chromium}=require('@playwright/test');
const browser=await chromium.launch({executablePath:'/home/kevin/.cache/ms-playwright/chromium-1246/chrome-linux64/chrome',args:['--no-sandbox']});
const p=await browser.newPage({viewport:{width:1512,height:1050}});
const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto('file:///home/kevin/ai/workspaces/harmisgenerator/design/mockups/hybrid/prototype.html');
await p.evaluate(()=>document.fonts.ready);
const state=()=>p.evaluate(()=>window.hybrid.getState());
const results=[];
async function fresh(){await p.reload();await p.evaluate(()=>document.fonts.ready);}
async function clickChord(section,index,chordIndex=0){const s=await state();const b=s.model.sections.find(x=>x.id===section).bars[index];await p.locator(`[data-chord="${b.chords[chordIndex].id}"]`).dblclick();}
async function test(name,fn){try{await fresh();await fn();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:e.message});}}
function assert(condition,msg){if(!condition)throw Error(msg);}
await test('Single tool click commits valid draft and opens requested tool',async()=>{await clickChord('verse',0);await p.locator('#score-edit').fill('Dm');await p.locator('.toolbar [data-action="tool:chord"]').click();const s=await state();assert(s.tool==='chord','tool is '+s.tool);assert(s.model.sections[1].bars[0].chords[0].name==='Dm','edit lost');});
await test('Second chord activation replaces the full measure line',async()=>{await clickChord('verse',4);await p.locator('#score-edit').fill('Dm F');await p.locator('#score-edit').press('Enter');const c=(await state()).model.sections[1].bars[4].chords;assert(c.map(x=>x.name).join(' ')==='Dm F','got '+c.map(x=>x.name).join(' '));});
await test('Blank area replaces whole bar',async()=>{const s=await state(),b=s.model.sections[1].bars[4];await p.locator(`[data-chord-area="${b.id}"]`).click({position:{x:4,y:5}});await p.locator('#score-edit').fill('Dm F');await p.locator('#score-edit').press('Enter');assert((await state()).model.sections[1].bars[4].chords.length===2,'neighbors not replaced');});
await test('Production chord extension syntax accepted',async()=>{await clickChord('verse',0);await p.locator('#score-edit').fill('(Fm(maj9)/Ab)');await p.locator('#score-edit').press('Enter');assert(!(await state()).draft,'valid extension rejected');});
await test('Invalid chord is kept as draft after tool click',async()=>{await clickChord('verse',0);await p.locator('#score-edit').fill('Dgarbage');await p.locator('.toolbar [data-action="tool:rhythm"]').click();const s=await state();assert(s.draft?.value==='Dgarbage','invalid text committed or lost');});
await test('Text composition Enter does not commit',async()=>{await clickChord('verse',0);await p.locator('#score-edit').fill('Dm');await p.locator('#score-edit').dispatchEvent('keydown',{key:'Enter',code:'Enter',isComposing:true,bubbles:true});assert((await state()).draft,'Enter committed during composition');});
await test('Three added chords use representable quarter positions',async()=>{await clickChord('verse',0);await p.locator('#score-edit').fill('D G A');await p.locator('#score-edit').press('Enter');const s=await state(),b=s.model.sections[1].bars[0];assert(s.draft||b.chords.every(c=>Number.isInteger(c.start*4)),'unsupported beat fractions '+b.chords.map(c=>c.start).join(','));});
await test('One click on next chord saves current edit and selects next chord',async()=>{await clickChord('verse',0);await p.locator('#score-edit').fill('Dm');const s=await state(),id=s.model.sections[1].bars[1].chords[0].id;await p.locator(`[data-chord="${id}"]`).click();const z=await state();assert(z.model.sections[1].bars[0].chords[0].name==='Dm','prior edit lost');assert(!z.draft&&z.chordId===id,'next chord not activated in one click');});

const tool=name=>p.locator(`.toolbar [data-action="tool:${name}"]`).click();
const source=s=>s.model.sections.find(x=>x.id==='verse');
await test('Escape discards direct typing without changing score',async()=>{await clickChord('verse',0);await p.locator('#score-edit').fill('Em');await p.locator('#score-edit').press('Escape');const s=await state();assert(!s.draft&&source(s).bars[0].chords[0].name==='D','Escape changed score');});
await test('Empty direct input clears the chord line',async()=>{await clickChord('verse',0);await p.locator('#score-edit').fill('');await p.locator('#score-edit').press('Enter');assert(!(await state()).draft&&!source(await state()).bars[0].chords.length,'empty input rejected');});
await test('Chord input rejects prematurely closing parentheses',async()=>{await clickChord('verse',0);await p.locator('#score-edit').fill('D)(');await p.locator('#score-edit').press('Enter');assert((await state()).draft?.error,'D)( incorrectly accepted');});
await test('Grouped parentheses are normalized to individual chords',async()=>{const s=await state(),b=source(s).bars[0];await p.locator(`[data-chord-area="${b.id}"]`).click({position:{x:4,y:5}});await p.locator('#score-edit').fill('(Dm G7)');await p.locator('#score-edit').press('Enter');const c=source(await state()).bars[0].chords;assert(c.length===2&&c.every(x=>x.parenthetical),'group lost parentheses');});
await test('Chord and rhythm placement grids provide 4/8/16 positions',async()=>{await clickChord('verse',4);await tool('chord');for(const n of [4,8,16]){await p.locator(`[data-action="resolution:${n}"]`).click();const c=source(await state()).bars[4].chords[1];const count=await p.locator(`[data-start="${c.id}"] option`).count();assert(count===n,'wrong chord resolution '+n+': '+count);}await tool('rhythm');assert(await p.locator('[data-action^="attack:"]').count()===16,'rhythm grid wrong');});
await test('Chord position, reorder, recent chord and variant update the model',async()=>{await clickChord('verse',4);await tool('chord');await p.locator('[data-action="resolution:16"]').click();let c=source(await state()).bars[4].chords[1];await p.locator(`[data-start="${c.id}"]`).selectOption('1.25');assert(source(await state()).bars[4].chords[1].start===1.25,'position not stored');await p.locator(`[data-action="chord-up:${c.id}"]`).click();assert(source(await state()).bars[4].chords[0].name==='A/C#','order not changed');await p.locator('#variant').fill('Bm7');await p.locator('#variant-pass').fill('3');await p.locator('#variant-following').check();assert(source(await state()).bars[4].chords.some(x=>x.variant==='Bm7'&&x.variantPass===3&&x.variantFollowing),'variant not stored');});
await test('N.C. replaces selected chord without erasing rhythm or neighbor',async()=>{await clickChord('verse',4);await tool('rhythm');await p.locator('[data-action="attack:1"]').click();await tool('chord');await p.locator('[data-action="nc"]').click();const b=source(await state()).bars[4];assert(b.chords[0].name==='N.C.'&&b.chords[1].name==='A/C#'&&b.attacks.length===1,'N.C. erased other data');});
await test('Rhythm rejects overlapping durations and keeps existing notes',async()=>{await clickChord('verse',0);await tool('rhythm');await p.locator('[data-action="resolution:16"]').click();await p.locator('[data-action="attack:1"]').click();await p.locator('[data-action="attack:1.25"]').click();await p.locator('[data-duration="1"]').selectOption('8');const s=await state();assert(source(s).bars[0].attacks.find(x=>x.start===1).duration===16&&s.error,'overlapping note accepted');});
await test('6/8 grid uses denominator-aware start points',async()=>{await clickChord('verse',0);await tool('insert');await p.locator('#local-meter').selectOption('6/8');await p.locator('[data-action="local-apply"]').click();await tool('rhythm');for(const [n,count] of [[4,3],[8,6],[16,12]]){await p.locator(`[data-action="resolution:${n}"]`).click();assert(await p.locator('[data-action^="attack:"]').count()===count,'wrong 6/8 grid '+n);}await p.locator('[data-action="attack:6.5"]').click();await p.locator('[data-duration="6.5"]').selectOption('8');const z=await state();assert(source(z).bars[0].attacks[0].duration===16&&z.error,'note crossed 6/8 boundary');});
await test('House back button and exact selected range work',async()=>{let s=await state(),bars=source(s).bars;await p.locator(`[data-bar="${bars[2].id}"]`).click({position:{x:70,y:78}});await p.locator(`[data-bar="${bars[4].id}"]`).click({modifiers:['Shift'],position:{x:70,y:78}});await tool('repeats');await p.locator('[data-action="house:1"]').click();await p.locator('.back-button').click();assert((await state()).tool==='repeats','back did not return to main');await p.locator('[data-action="house:1"]').click();await p.locator('[data-action="house-apply"]').click();s=await state();assert(source(s).bars[2].houseSpan?.length===3,'span length wrong');assert(await p.locator('.marker').count()===2,'house not continued correctly across row');});
await test('Form includes all parts and a linked recurrence with settings',async()=>{await p.locator('.panel-nav [data-action="tab:form"]').click();assert(await p.locator('.form-block').count()===3,'form missing parts');await p.locator('[data-action="reuse"]').click();assert(await p.locator('.form-block.reuse').count()===1,'reuse not visibly distinguished');await p.locator('#reuse-count').fill('2');await p.locator('#reuse-instruction').fill('Instrumentalt');await p.locator('[data-action="reuse-apply"]').click();const f=(await state()).model.form.at(-1);assert(f.reuse&&f.count===2&&f.instruction==='Instrumentalt','reuse settings not stored');assert(await p.locator('.reuse-score').textContent().then(x=>x.includes('Instrumentalt')),'preview did not update');});
await test('Recurrence moves before original and undo restores order',async()=>{await p.locator('.panel-nav [data-action="tab:form"]').click();await p.locator('[data-action="reuse"]').click();let f=(await state()).model.form.at(-1);await p.locator(`[data-action="move:${f.id}:-1"]`).click();assert((await state()).model.form[2].id===f.id,'valid move failed');await p.locator(`[data-action="move:${f.id}:-1"]`).click();const s=await state();assert(s.model.form[1].id===f.id&&!s.error,'before-original move failed');await p.locator('[data-action="undo"]').click();assert((await state()).model.form[2].id===f.id,'undo did not restore order');await p.locator('[data-action="redo"]').click();assert((await state()).model.form[1].id===f.id,'redo failed');});
await test('Drag reorder changes preview and written bar numbering',async()=>{await p.locator('.panel-nav [data-action="tab:form"]').click();await p.locator('[data-block="f3"]').dragTo(p.locator('[data-block="f2"]'));const s=await state();assert(s.model.form[1].source==='chorus','drag failed');const first=await p.locator('#section-chorus .bar-number').first().textContent();assert(first==='5','bar numbering follows old definition order: '+first);});
await test('Insert and layout share local changes and row breaks work',async()=>{await clickChord('verse',1);await tool('insert');assert(await p.locator('#local-key').count()===1&&await p.locator('#local-meter').count()===1,'insert changes absent');await p.locator('#local-key').selectOption('E');await p.locator('[data-action="local-apply"]').click();assert(source(await state()).bars[1].key==='E','local key not stored');await tool('layout');await p.locator('[data-action="break:row"]').click();assert(source(await state()).bars[1].rowBreak,'row break missing');assert(await p.locator('#local-key').inputValue()==='E','layout has different local state');});
await test('Song edits update title and invalid key does not commit',async()=>{await p.locator('.panel-nav [data-action="tab:song"]').click();await p.locator('#song-title').fill('Min låt');await p.locator('[data-action="song-apply"]').click();assert(await p.locator('h1').textContent()==='Min låt','title not updated');await p.locator('#song-key').fill('banan');await p.locator('[data-action="song-apply"]').click();assert((await state()).model.key==='D','invalid key committed');});
await test('Mobile supports direct typing and popup instead of fixed panel',async()=>{await p.setViewportSize({width:430,height:760});await fresh();await clickChord('verse',0);assert(await p.locator('#score-edit').evaluate(e=>document.activeElement===e),'mobile text field not focused');assert(await p.locator('.panel').evaluate(e=>getComputedStyle(e).display)==='none','fixed panel remains on mobile');await p.locator('#score-edit').fill('Em');await p.locator('#score-edit').press('Enter');await p.locator('.toolbar [data-action="tab:music"]').click();assert(await p.locator('.panel').evaluate(e=>getComputedStyle(e).position)==='fixed','popup not active');await p.locator('.panel [data-action="tool:chord"]').click();await p.locator('[data-action="close-panel"].sheet-close').click();assert(await p.locator('.panel').evaluate(e=>getComputedStyle(e).display)==='none','popup did not close');assert(await p.evaluate(()=>document.documentElement.scrollWidth)<=430,'mobile horizontal overflow');await p.setViewportSize({width:1512,height:1050});});
console.log('BROAD REVIEW COMPLETE');

await p.screenshot({path:'/tmp/harmis-hybrid-first-review.png'});
const report={errors,results};await (await import('node:fs/promises')).writeFile(new URL('independent-review-core.json',import.meta.url),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();
