import {createRequire} from 'node:module';
const require=createRequire('/home/kevin/ai/workspaces/harmisgenerator/package.json');
const {chromium}=require('@playwright/test');
const browser=await chromium.launch({executablePath:'/home/kevin/.cache/ms-playwright/chromium-1246/chrome-linux64/chrome',args:['--no-sandbox']});
const p=await browser.newPage({viewport:{width:1512,height:1050}});
const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto('file:///home/kevin/ai/workspaces/harmisgenerator/design/mockups/hybrid/prototype.html');
await p.evaluate(()=>document.fonts.ready);
p.setDefaultTimeout(3500);
const state=()=>p.evaluate(()=>window.hybrid.getState());
const results=[];
async function closeParameters(){if((await state()).contextView)await p.keyboard.press('Escape');}
async function parameter(view){const st=await state();if(st.draft)await p.locator('#score-edit').press('Enter');if(['variant','add','order'].includes(view)&&!(await state()).chordId){const z=await state(),b=z.model.sections.flatMap(x=>x.bars).find(b=>b.id===z.selected[0]);if(b?.chords.length)await p.locator(`[data-chord="${b.chords[0].id}"]`).click();}if((await state()).contextView!==view)await p.locator(`button[data-action="context:${view}"]`).filter({visible:true}).first().click();}

async function fresh(){await p.reload();await p.evaluate(()=>document.fonts.ready);}
async function clickChord(section,index,chordIndex=0){await closeParameters();const s=await state();const b=s.model.sections.find(x=>x.id===section).bars[index];await p.locator(`[data-chord="${b.chords[chordIndex].id}"]`).dblclick();}
async function test(name,fn){try{await fresh();await fn();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:e.message});}}
function assert(condition,msg){if(!condition)throw Error(msg);}
await test('Global tab click commits valid draft and opens requested tab',async()=>{await clickChord('verse',0);await p.locator('#score-edit').fill('Dm');await p.locator('button[data-action="tab:song"]').filter({visible:true}).first().click();const s=await state();assert(s.tab==='song'&&s.model.sections.find(x=>x.id==='verse').bars[0].chords[0].name==='Dm','global tab lost draft');});
await test('Second chord activation replaces the full measure line',async()=>{await clickChord('verse',4);await p.locator('#score-edit').fill('Dm F');await p.locator('#score-edit').press('Enter');const c=(await state()).model.sections[1].bars[4].chords;assert(c.map(x=>x.name).join(' ')==='Dm F','got '+c.map(x=>x.name).join(' '));});
await test('Blank area replaces whole bar',async()=>{const s=await state(),b=s.model.sections[1].bars[4];await p.locator(`[data-chord-area="${b.id}"]`).click({position:{x:4,y:5}});await p.locator('#score-edit').fill('Dm F');await p.locator('#score-edit').press('Enter');assert((await state()).model.sections[1].bars[4].chords.length===2,'neighbors not replaced');});
await test('Production chord extension syntax accepted',async()=>{await clickChord('verse',0);await p.locator('#score-edit').fill('(Fm(maj9)/Ab)');await p.locator('#score-edit').press('Enter');assert(!(await state()).draft,'valid extension rejected');});
await test('Invalid chord remains draft after global tab click',async()=>{await clickChord('verse',0);await p.locator('#score-edit').fill('Dgarbage');await p.locator('button[data-action="tab:song"]').filter({visible:true}).first().click();assert((await state()).draft?.value==='Dgarbage','invalid draft committed or lost');});
await test('Text composition Enter does not commit',async()=>{await clickChord('verse',0);await p.locator('#score-edit').fill('Dm');await p.locator('#score-edit').dispatchEvent('keydown',{key:'Enter',code:'Enter',isComposing:true,bubbles:true});assert((await state()).draft,'Enter committed during composition');});
await test('Three added chords use representable quarter positions',async()=>{await clickChord('verse',0);await p.locator('#score-edit').fill('D G A');await p.locator('#score-edit').press('Enter');const s=await state(),b=s.model.sections[1].bars[0];assert(s.draft||b.chords.every(c=>Number.isInteger(c.start*4)),'unsupported beat fractions '+b.chords.map(c=>c.start).join(','));});
await test('One click on next chord saves current edit and selects next chord',async()=>{await clickChord('verse',0);await p.locator('#score-edit').fill('Dm');const s=await state(),id=s.model.sections[1].bars[1].chords[0].id;await p.locator(`[data-chord="${id}"]`).click();const z=await state();assert(z.model.sections[1].bars[0].chords[0].name==='Dm','prior edit lost');assert(!z.draft&&z.chordId===id,'next chord not activated in one click');});

const tool=async name=>{if(name==='chord')await parameter('order');else if(name==='rhythm')await parameter('rhythm');else if(name==='insert')await parameter('changes');};
const source=s=>s.model.sections.find(x=>x.id==='verse');
await test('Escape discards direct typing without changing score',async()=>{await clickChord('verse',0);await p.locator('#score-edit').fill('Em');await p.locator('#score-edit').press('Escape');const s=await state();assert(!s.draft&&source(s).bars[0].chords[0].name==='D','Escape changed score');});
await test('Empty direct input clears the chord line',async()=>{await clickChord('verse',0);await p.locator('#score-edit').fill('');await p.locator('#score-edit').press('Enter');assert(!(await state()).draft&&!source(await state()).bars[0].chords.length,'empty input rejected');});
await test('Chord input rejects prematurely closing parentheses',async()=>{await clickChord('verse',0);await p.locator('#score-edit').fill('D)(');await p.locator('#score-edit').press('Enter');assert((await state()).draft?.error,'D)( incorrectly accepted');});
await test('Grouped parentheses are normalized to individual chords',async()=>{const s=await state(),b=source(s).bars[0];await p.locator(`[data-chord-area="${b.id}"]`).click({position:{x:4,y:5}});await p.locator('#score-edit').fill('(Dm G7)');await p.locator('#score-edit').press('Enter');const c=source(await state()).bars[0].chords;assert(c.length===2&&c.every(x=>x.parenthetical),'group lost parentheses');});
await test('Chord and rhythm placement grids provide 4/8/16 positions',async()=>{await clickChord('verse',4);await tool('chord');for(const n of [4,8,16]){await p.locator(`[data-action="resolution:${n}"]`).click();const c=source(await state()).bars[4].chords[1];const count=await p.locator(`[data-start="${c.id}"] option`).count();assert(count===n,'wrong chord resolution '+n+': '+count);}await tool('rhythm');assert(await p.locator('[data-action^="attack:"]').count()===16,'rhythm grid wrong');});
await test('Chord position, reorder, recent chord and variant update the model',async()=>{await clickChord('verse',4);await tool('chord');await p.locator('[data-action="resolution:16"]').click();let c=source(await state()).bars[4].chords[1];await p.locator(`[data-start="${c.id}"]`).selectOption('1.25');assert(source(await state()).bars[4].chords[1].start===1.25,'position not stored');await p.locator(`[data-action="chord-up:${c.id}"]`).click();assert(source(await state()).bars[4].chords[0].name==='A/C#','order not changed');await parameter('variant');await p.locator('#context-variant').fill('Bm7');await p.locator('#context-variant-pass').fill('3');await p.locator('#context-variant-following').check();assert(source(await state()).bars[4].chords.some(x=>x.variant==='Bm7'&&x.variantPass===3&&x.variantFollowing),'variant not stored');});
await test('N.C. replaces selected chord without erasing rhythm or neighbor',async()=>{await clickChord('verse',4);await tool('rhythm');await p.locator('[data-action="attack:1"]').click();await tool('chord');await closeParameters();await p.locator('[data-action="nc"]').click();const b=source(await state()).bars[4];assert(b.chords[0].name==='N.C.'&&b.chords[1].name==='A/C#'&&b.attacks.length===1,'N.C. erased other data');});
await test('Rhythm rejects overlapping durations and keeps existing notes',async()=>{await clickChord('verse',0);await tool('rhythm');await p.locator('[data-action="resolution:16"]').click();await p.locator('[data-action="attack:1"]').click();await p.locator('[data-action="attack:1.25"]').click();await p.locator('[data-duration="1"]').selectOption('8');const s=await state();assert(source(s).bars[0].attacks.find(x=>x.start===1).duration===16&&s.error,'overlapping note accepted');});
await test('6/8 grid uses denominator-aware start points',async()=>{await clickChord('verse',0);await tool('insert');await p.locator('#local-meter').selectOption('6/8');await p.locator('[data-action="local-apply"]').click();await tool('rhythm');for(const [n,count] of [[4,3],[8,6],[16,12]]){await p.locator(`[data-action="resolution:${n}"]`).click();assert(await p.locator('[data-action^="attack:"]').count()===count,'wrong 6/8 grid '+n);}await p.locator('[data-action="attack:6.5"]').click();await p.locator('[data-duration="6.5"]').selectOption('8');const z=await state();assert(source(z).bars[0].attacks[0].duration===16&&z.error,'note crossed 6/8 boundary');});
await test('Custom house close and exact checkbox range work',async()=>{const bars=source(await state()).bars;await p.locator(`[data-select-bar="${bars[2].id}"]`).click({position:{x:3,y:5}});for(let i=3;i<=4;i++)await p.locator(`[data-bar-check="${bars[i].id}"]`).check();await p.locator('[data-action="context:house-number"]').click();await p.locator('[data-action="close-context"]').click();assert(!(await state()).contextView,'close leaves parameters');await p.locator('[data-action="context-house:1"]').click();assert(source(await state()).bars[2].houseSpan.length===3,'span wrong');assert(await p.locator('.marker').count()===2,'house continuation missing');});
await test('Form includes all parts and a linked recurrence with settings',async()=>{await p.locator('button[data-action="tab:form"]').filter({visible:true}).first().click();assert(await p.locator('.form-block').count()===3,'form missing parts');await closeParameters();await p.locator('[data-action="select-part:verse"]').click();await p.locator('[data-action="context-reuse:verse"]').click();assert(await p.locator('.form-block.reuse').count()===1,'reuse not visibly distinguished');await p.locator('#context-reuse-count').fill('2');await p.locator('#context-reuse-instruction').fill('Instrumentalt');await p.locator('[data-action="context-reuse-apply"]').click();const f=(await state()).model.form.at(-1);assert(f.reuse&&f.count===2&&f.instruction==='Instrumentalt','reuse settings not stored');assert(await p.locator('.reuse-score').textContent().then(x=>x.includes('Instrumentalt')),'preview did not update');});
await test('Recurrence moves before original and undo restores order',async()=>{await p.locator('button[data-action="tab:form"]').filter({visible:true}).first().click();await closeParameters();await p.locator('[data-action="select-part:verse"]').click();await p.locator('[data-action="context-reuse:verse"]').click();let f=(await state()).model.form.at(-1);await p.locator(`[data-action="move:${f.id}:-1"]`).click();assert((await state()).model.form[2].id===f.id,'valid move failed');await p.locator(`[data-action="move:${f.id}:-1"]`).click();const s=await state();assert(s.model.form[1].id===f.id&&!s.error,'before-original move failed');await p.locator('[data-action="undo"]').click();assert((await state()).model.form[2].id===f.id,'undo did not restore order');await p.locator('[data-action="redo"]').click();assert((await state()).model.form[1].id===f.id,'redo failed');});
await test('Drag reorder changes preview and written bar numbering',async()=>{await p.locator('button[data-action="tab:form"]').filter({visible:true}).first().click();await p.locator('[data-block="f3"]').dragTo(p.locator('[data-block="f2"]'));const s=await state();assert(s.model.form[1].source==='chorus','drag failed');const first=await p.locator('#section-chorus .bar-number').first().textContent();assert(first==='5','bar numbering follows old definition order: '+first);});
await test('Direct changes and row-break controls share selected measure',async()=>{await clickChord('verse',1);await tool('insert');await p.locator('#local-key').selectOption('E');await p.locator('[data-action="local-apply"]').click();await closeParameters();await p.locator('[data-action="break:row"]').click();assert(source(await state()).bars[1].key==='E'&&source(await state()).bars[1].rowBreak,'direct changes lost selected scope');await parameter('changes');assert(await p.locator('#local-key').inputValue()==='E','reopened changes lost value');});
await test('Song edits update title and invalid key does not commit',async()=>{await p.locator('button[data-action="tab:song"]').filter({visible:true}).first().click();await p.locator('#song-title').fill('Min låt');await p.locator('[data-action="song-apply"]').click();assert(await p.locator('h1').textContent()==='Min låt','title not updated');await p.locator('#song-key').fill('banan');await p.locator('[data-action="song-apply"]').click();assert((await state()).model.key==='D','invalid key committed');});
await test('Mobile supports direct typing and native parameter popup',async()=>{await p.setViewportSize({width:430,height:760});await fresh();await clickChord('verse',0);assert(await p.locator('#score-edit').evaluate(e=>document.activeElement===e),'mobile editor not focused');await p.locator('#score-edit').fill('Em');await p.locator('#score-edit').press('Enter');const c=source(await state()).bars[0].chords[0];await p.locator(`[data-chord="${c.id}"]`).click();await parameter('variant');assert(await p.locator('#context-popup').evaluate(d=>d.open),'mobile parameter dialog closed');await p.locator('[data-action="close-context"]').click();assert(!await p.locator('#context-popup').count(),'parameter close failed');assert(await p.evaluate(()=>document.documentElement.scrollWidth)<=430,'mobile overflow');await p.setViewportSize({width:1512,height:1050});});
console.log('BROAD REVIEW COMPLETE');

await p.screenshot({path:'/tmp/harmis-hybrid-first-review.png'});
const report={errors,results};await (await import('node:fs/promises')).writeFile(new URL('independent-review-core.json',import.meta.url),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();
