/* Score-native variant editing and readable rhythm notation. */
let selectedVariantId=null,variantOwnerId=null;
const variantOwner=()=>singleBar()?.chords.find(c=>c.id===variantOwnerId)||currentChord();
const currentVariant=()=>variantOwner()?.variantChords?.find(c=>c.id===selectedVariantId)||null;
const variantEnd=(b,c)=>b.chords[b.chords.indexOf(c)+1]?.start??meterUnits(b)+1;
const variantText=c=>(c.variantChords||[]).map(v=>v.parenthetical?'('+v.name+')':v.name).join(' ');
const variantPassLabel=c=>{const n=c.variantPass||2;return n+(n===2?':a':':e')+(c.variantFollowing?'+':'');};
function variantList(b,c,parsed){
 const old=draft?.kind==='variant'&&draft.ownerId===c.id&&draft.originalChords.length===parsed.length?draft.originalChords:(c.variantChords||[]),end=variantEnd(b,c),span=end-c.start;
 let step=span>=parsed.length?1:[.5,.25].find(n=>c.start+n*(parsed.length-1)<end);
 if(parsed.length===2&&span>=4)step=2;
 if(parsed.length&&step==null)throw Error('Variantackorden ryms inte mellan grundackordets byten. Skriv färre ackord eller flytta grundackorden.');
 const next=parsed.map((v,i)=>({...v,id:old[i]?.id||++uid,start:old.length===parsed.length?old[i].start:c.start+i*step}));
 if(next.some((v,i)=>v.start<c.start||v.start>=end||(i&&v.start<=next[i-1].start)))throw Error('Variantens byten måste rymmas mellan grundackordets start och nästa byte.');
 return next;
}
function beginVariantEdit(ownerId,caret=null){
 if(!commitRename()||!commitDraft(false))return;const b=singleBar(),c=b?.chords.find(c=>c.id===Number(ownerId));if(!c)return;
 const originalSelected=variantOwnerId===c.id?selectedVariantId:null;resetContext();variantOwnerId=c.id;chordId=c.id;selectedVariantId=c.variantChords?.[0]?.id||null;panelOpen=false;
 draft={kind:'variant',barId:b.id,ownerId:c.id,value:c.variant||'',original:c.variant||'',originalChords:clone(c.variantChords||[]),originalAttacks:clone(c.variantAttacks||[]),originalOwner:clone(c),originalSelected,undoDepth:past.length,originalFuture:clone(future),changed:false,error:''};
 render();focusVariantDraft(caret);
}
function focusVariantDraft(caret=null){const input=$('#variant-edit');if(!input)return;input.focus({preventScroll:true});const point=caret??input.value.length;input.setSelectionRange(point,point);input.closest('.variant-lane').scrollIntoView({block:'nearest',inline:'nearest'});}
function updateVariantDraft(){
 if(draft?.kind!=='variant')return false;const c=barById(draft.barId)?.chords.find(c=>c.id===draft.ownerId);if(!c)return false;
 try{const next=variantList(barById(draft.barId),c,parseChordText(draft.value)),text=next.map(v=>v.parenthetical?'('+v.name+')':v.name).join(' ');draft.error='';
  if(text!==c.variant||JSON.stringify(next)!==JSON.stringify(c.variantChords||[])){if(!draft.changed){past.push(clone(model));future=[];draft.changed=true;}c.variant=text;c.variantChords=next;selectedVariantId=next[0]?.id||null;}
 }catch(e){draft.error=e.message;}
 const frame=$('#variant-edit')?.closest('.variant-frame');if(frame){let feedback=frame.querySelector('.variant-error');if(draft.error){if(!feedback){feedback=document.createElement('div');feedback.className='variant-error';feedback.setAttribute('role','alert');frame.append(feedback);}feedback.textContent=draft.error;}else feedback?.remove();const ruler=frame.querySelector('.variant-beat-ruler');if(ruler)ruler.innerHTML=variantRulerHTML(barById(draft.barId),c);}
 positionChordTools();syncUndoButtons();return !draft.error;
}
function commitVariantDraft(fullRender=true){
 if(!updateVariantDraft()){focusVariantDraft();return false;}const c=variantOwner();draft=null;selectedVariantId=c?.variantChords?.[0]?.id||null;message='Variantackorden uppdaterades på bladet.';error='';if(fullRender)render();else renderScore();return true;
}
function cancelVariantDraft(){if(draft?.kind!=='variant')return;const c=barById(draft.barId).chords.find(c=>c.id===draft.ownerId),originalSelected=draft.originalSelected;Object.keys(c).forEach(key=>delete c[key]);Object.assign(c,draft.originalOwner);past.length=draft.undoDepth;future=draft.originalFuture;draft=null;selectedVariantId=c.variantChords?.find(v=>v.id===originalSelected)?.id||c.variantChords?.[0]?.id||null;if(!c.variant&&!c.variantAttacks?.length)variantOwnerId=null;render();$(selectedVariantId?`[data-variant-chord="${selectedVariantId}"]`:`[data-chord="${c.id}"]`)?.focus({preventScroll:true});}

function selectVariant(barId,ownerId,id,caret=null){
 if(!commitRename()||!commitDraft(false))return;
 if(selectedVariantId===id&&variantOwnerId===ownerId&&selected[0]===barId){const c=barById(barId).chords.find(c=>c.id===ownerId),i=c.variantChords.findIndex(v=>v.id===id),prefix=c.variantChords.slice(0,i).map(v=>v.parenthetical?'('+v.name+')':v.name).join(' ');beginVariantEdit(ownerId,caret==null?null:prefix.length+(i?1:0)+caret);return;}
 resetContext();selectedPart=null;selected=[barId];chordId=ownerId;variantOwnerId=ownerId;selectedVariantId=id;panelOpen=false;pendingHouse=null;error='';message='Variantackord markerat. Klicka igen för att skriva på raden.';render();queueChordReveal(caret===null);
}
function variantRowsHTML(b){
 return b.chords.filter(c=>c.variant||c.variantAttacks?.length||variantOwnerId===c.id).map(c=>{const editing=draft?.kind==='variant'&&draft.ownerId===c.id;
  return `<div class="variant-lane ${variantOwnerId===c.id?'variant-active':''}" data-variant-lane="${c.id}"><div class="variant-row-label"><span title="Spelas ${variantPassLabel(c).replace('+','')} gången${c.variantFollowing?' och följande gånger':''} i stället för ${esc(c.name)}">${variantPassLabel(c)} <span class="variant-source">· ${esc(c.name)}</span></span>${!editing?btn('Inställningar för variant till '+c.name,'variant-settings:'+c.id,'variant-settings'):''}</div><div class="variant-frame"><div class="variant-chord-area" data-variant-area="${c.id}" role="button" tabindex="0" aria-label="Redigera varianten till ${esc(c.name)} i takt ${numberOf(b.id)}"></div>${(c.variantChords||[]).map(v=>`<span class="chord variant-chord ${selectedVariantId===v.id&&!draft?'chord-selected':''}" data-variant-chord="${v.id}" data-variant-owner="${c.id}" style="left:${8+(v.start-c.start)/(variantEnd(b,c)-c.start)*80}%" role="button" tabindex="0" aria-pressed="${selectedVariantId===v.id&&!draft}" aria-label="Markera variantackord ${esc(v.name)} i takt ${numberOf(b.id)}">${esc(v.parenthetical?'('+v.name+')':v.name)}</span>`).join('')}${rhythmNotationHTML(b,c.variantAttacks||[],c.id)}<div class="variant-beat-ruler" aria-label="Grundackordets spann: slag ${beatLabel(c.start)} till ${beatLabel(variantEnd(b,c))}">${variantRulerHTML(b,c)}</div>${editing?`<input id="variant-edit" class="variant-edit" aria-label="Skriv variantackord till ${esc(c.name)} i takt ${numberOf(b.id)}" value="${esc(draft.value)}" placeholder="Skriv variantackord" autocomplete="off" spellcheck="false">${draft.error?`<div class="variant-error" role="alert">${esc(draft.error)}</div>`:''}`:''}</div></div>`;
 }).join('');
}
function variantRulerHTML(b,c){const end=variantEnd(b,c),labels=[c.start,...(c.variantChords||[]).map(v=>v.start)];return [...new Set(labels)].map(n=>`<span style="left:${8+(n-c.start)/(end-c.start)*80}%">${beatLabel(n)}</span>`).join('');}
function rhythmSVG(duration,beamed=false){return `<svg class="rhythm-note" data-note-duration="${duration}" viewBox="0 0 24 38" preserveAspectRatio="none" aria-hidden="true"><path d="M6 30 12 20h5L11 30Z" fill="currentColor"/><path d="M16 25V3" fill="none" stroke="currentColor" stroke-width="1.4" vector-effect="non-scaling-stroke"/>${!beamed&&duration>=8?'<path d="M16 4c9 3 8 8 5 11" fill="none" stroke="currentColor" stroke-width="1.7"/>':''}${!beamed&&duration===16?'<path d="M16 10c9 3 8 8 5 11" fill="none" stroke="currentColor" stroke-width="1.7"/>':''}</svg>`;}
function rhythmNotationHTML(b,attacks,ownerId=null){
 if(!attacks.length)return '';const owner=ownerId?b.chords.find(c=>c.id===ownerId):null,start=owner?.start??1,span=owner?variantEnd(b,owner)-start:meterUnits(b),scale=owner?80:88,x=n=>8+(n-start)/span*scale,notes=[...attacks].sort((a,z)=>a.start-z.start),beamed=new Set(),beams=[];
 const group=n=>Math.floor((n-1)/(denominator(b)===8&&meterUnits(b)%3===0?3:1));
 for(let i=0;i<notes.length-1;i++){const a=notes[i],z=notes[i+1];if(a.duration<8||z.duration<8||group(a.start)!==group(z.start)||z.start-a.start>denominator(b)/a.duration+.001)continue;beamed.add(i);beamed.add(i+1);beams.push({start:a.start,end:z.start,level:1});if(a.duration===16&&z.duration===16)beams.push({start:a.start,end:z.start,level:2});}
 // A short secondary beam distinguishes a sixteenth next to an eighth.
 for(const i of beamed)if(notes[i].duration===16&&!beams.some(v=>v.level===2&&(v.start===notes[i].start||v.end===notes[i].start))){const right=beams.find(v=>v.level===1&&v.start===notes[i].start),left=beams.find(v=>v.level===1&&v.end===notes[i].start);const other=right?.end??left?.start;beams.push({start:Math.min(notes[i].start,notes[i].start+(other-notes[i].start)*.3),end:Math.max(notes[i].start,notes[i].start+(other-notes[i].start)*.3),level:2});}
 return `<div class="rhythm-notation" data-rhythm-owner="${ownerId||'base'}" aria-label="${ownerId?'Variantens rytm':'Taktens rytm'}">${beams.map(v=>`<span class="rhythm-beam level-${v.level}" aria-hidden="true" style="left:calc(${x(v.start)}% + 1.33px);width:${(v.end-v.start)/span*scale}%"></span>`).join('')}${notes.map((a,i)=>`<button class="rhythm-attack ${beamed.has(i)?'is-beamed':''}" data-action="edit-rhythm:${b.id}:${ownerId||0}" data-note-start="${a.start}" data-note-value="${a.duration}" style="left:${x(a.start)}%" aria-label="${ownerId?'Variantens anslag':'Anslag'} på slag ${beatLabel(a.start)}, ${a.duration===4?'fjärdedel':a.duration===8?'åttondel':'sextondel'}" title="Slag ${beatLabel(a.start)} · 1/${a.duration}">${rhythmSVG(a.duration,beamed.has(i))}</button>`).join('')}</div>`;
}
function variantParamsHTML(c){return `${parameterHeading('Variant till '+c.name)}<div class="variant-parameters">${field('Spelas gång','context-variant-pass',c.variantPass||2,'type="number" min="2" max="16"')}<label class="variant-follow"><input id="context-variant-following" type="checkbox" ${c.variantFollowing?'checked':''}> Även följande gånger</label></div>`;}
function updateVariantParams(){const c=variantOwner(),input=$('#context-variant-pass');if(!c||!input)return;const pass=Number(input.value),following=$('#context-variant-following').checked;if(!Number.isInteger(pass)||pass<2||pass>16){input.setCustomValidity('Välj gång 2 till 16.');input.reportValidity();return;}input.setCustomValidity('');if(pass===c.variantPass&&following===!!c.variantFollowing)return;mutate(()=>{c.variantPass=pass;c.variantFollowing=following;},'Variantens spelomgång ändrades.');}
function variantPositions(b,c){return positions(b).filter(n=>n>=c.start&&n<variantEnd(b,c));}
function variantNextPosition(b,c,v,direction){const list=c.variantChords,i=list.indexOf(v),grid=variantPositions(b,c).filter(n=>n>(list[i-1]?.start??c.start-.001)&&n<(list[i+1]?.start??variantEnd(b,c)));return direction<0?grid.filter(n=>n<v.start-.0001).at(-1):grid.find(n=>n>v.start+.0001);}
function setVariantStart(id,value){const b=singleBar(),c=variantOwner(),v=c?.variantChords?.find(v=>v.id===Number(id)),start=Number(value);if(!b||!v)return;const next=c.variantChords.map(v=>({...v,start:v.id===Number(id)?start:v.start}));if(next.some((v,i)=>v.start<c.start||v.start>=variantEnd(b,c)||(i&&v.start<=next[i-1].start)))return fail('Variantackorden måste ligga i ordning inom grundackordets spann.');mutate(()=>v.start=start,'Variantackordet placerades på slag '+beatLabel(start)+'.');}
function variantOrderHTML(b,c){return `${parameterHeading('Variantens ordning och startpunkter')}${resolutionHTML()}${c.variantChords.map((v,i)=>`<div class="beat-row"><span class="name">${esc(v.name)}</span><select data-variant-start="${v.id}" aria-label="Variant ${esc(v.name)} börjar på">${[...new Set([...variantPositions(b,c),v.start])].sort((a,b)=>a-b).map(n=>`<option value="${n}" ${n===v.start?'selected':''}>Slag ${beatLabel(n)}</option>`).join('')}</select>${btn('Flytta variantackord före föregående','variant-up:'+v.id,'',i===0?'disabled':'')}</div>`).join('')}`;}
function variantAttacksValid(b,c,attacks){return attacksValid(b,attacks)&&attacks.every(a=>a.start>=c.start&&a.start+denominator(b)/a.duration<=variantEnd(b,c));}
function barMusicValid(b){return b.chords.every((c,i)=>c.start>=1&&c.start<meterUnits(b)+1&&(!i||c.start>b.chords[i-1].start)&&(c.variantChords||[]).every((v,j,list)=>v.start>=c.start&&v.start<variantEnd(b,c)&&(!j||v.start>list[j-1].start))&&variantAttacksValid(b,c,c.variantAttacks||[]))&&attacksValid(b,b.attacks);}
function copyChordIdentities(b){for(const c of b.chords){c.id=++uid;for(const v of c.variantChords||[])v.id=++uid;}}
function handleNotationAction(action){
 if(action?.startsWith('variant-settings:')){const id=Number(action.slice(17)),b=model.sections.flatMap(s=>s.bars).find(b=>b.chords.some(c=>c.id===id)),c=b?.chords.find(c=>c.id===id);if(!c)return true;if(!singleBar()||selected[0]!==b.id)selectBar(b.id);chordId=id;variantOwnerId=id;selectedVariantId=c.variantChords?.[0]?.id||null;contextView='';return handleContextAction('context:variant');}
 if(action==='context:variant'&&!currentVariant()){const c=currentChord();if(c)beginVariantEdit(c.id);return true;}
 if(action==='context-edit'&&currentVariant()){beginVariantEdit(variantOwnerId);return true;}
 if(action?.startsWith('edit-rhythm:')){const [,barId,owner]=action.split(':');selectBar(Number(barId));if(Number(owner)){const c=selectedBar().chords.find(c=>c.id===Number(owner));chordId=c.id;variantOwnerId=c.id;selectedVariantId=c.variantChords?.[0]?.id||null;}return handleContextAction(Number(owner)?'context:variant-rhythm':'context:rhythm');}
 if(action?.startsWith('variant-step:')){const [,id,direction]=action.split(':'),b=singleBar(),c=variantOwner(),v=currentVariant(),start=variantNextPosition(b,c,v,Number(direction));if(start!=null)setVariantStart(id,start);return true;}
 if(action?.startsWith('variant-up:')){const c=variantOwner(),i=c.variantChords.findIndex(v=>v.id===Number(action.slice(11)));if(i<1)return true;mutate(()=>{const a=c.variantChords[i-1],z=c.variantChords[i],start=a.start;a.start=z.start;z.start=start;c.variantChords.splice(i-1,2,z,a);c.variant=variantText(c);},'Variantackordens ordning ändrades.');return true;}
 if(action?.startsWith('variant-attack:')){const b=singleBar(),c=variantOwner(),start=Number(action.slice(15)),attacks=c.variantAttacks||[],existing=attacks.find(a=>a.start===start),next=existing?attacks.filter(a=>a!==existing):[...attacks,{start,duration:resolution}];if(!variantAttacksValid(b,c,next)){fail('Variantens anslag överlappar eller går utanför grundackordets spann. Välj ett kortare notvärde.');return true;}mutate(()=>c.variantAttacks=next,'Variantens anslag uppdaterades.');return true;}
 if(currentVariant()&&['context-parentheses','nc','context-delete-chord'].includes(action)){const c=variantOwner(),v=currentVariant();mutate(()=>{if(action==='context-parentheses')v.parenthetical=!v.parenthetical;if(action==='nc')v.name='N.C.';if(action==='context-delete-chord'){c.variantChords=c.variantChords.filter(a=>a!==v);selectedVariantId=c.variantChords[0]?.id||null;}c.variant=variantText(c);},'Variantackordet uppdaterades.');return true;}
 if(currentVariant()&&action?.startsWith('recent:')){const b=singleBar(),c=variantOwner(),v=currentVariant(),start=variantNextPosition(b,c,v,1);if(c.variantChords.length>=4||start==null){fail('Det finns ingen ledig startpunkt efter variantackordet. Välj ett finare placeringssteg.');return true;}mutate(()=>{const index=c.variantChords.indexOf(v)+1,newChord={id:++uid,name:action.slice(7),start,parenthetical:false};c.variantChords.splice(index,0,newChord);selectedVariantId=newChord.id;c.variant=variantText(c);},'Ackordet lades till på variantraden.');return true;}
 return false;
}
