/* Isolated design study. Model changes stay in this page's memory. */
const $ = (s, root = document) => root.querySelector(s);
const esc = v => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone = x => JSON.parse(JSON.stringify(x));
const btn = (text, action, kind = '', attrs = '') => `<button class="${kind}" data-action="${action}" ${attrs}>${text}</button>`;
const opt = (text, action, description = '') => btn(`${text}${description ? `<small>${description}</small>` : ''}`, action);
const field = (text, id, value, extra = '') => `<div class="field"><label for="${id}">${text}</label><input id="${id}" value="${esc(value)}" ${extra}></div>`;
let uid = 100;
const chords = values => values.map((name, i) => ({id:++uid, name, parenthetical:false, start:values.length === 2 ? i*2+1 : i+1, variant:''}));
const makeBar = values => ({id:++uid, chords:chords(values), attacks:[], house:'', houseSpan:null, rowBreak:false, pageBreak:false, repeatStart:false, repeatEnd:false, key:'', meter:''});
const initial = () => ({title:'Tro', artist:'Marie Fredriksson', key:'D', meter:'4/4', tempo:72, version:'Grundarrangemang', status:'Arbetsutkast', recent:['D','A','Bm','G','A/C#'], sections:[
 {id:'intro', name:'Intro', bars:[['D'],['G'],['D','A'],['D']].map(makeBar)},
 {id:'verse', name:'Vers', bars:[['D'],['G'],['Bm'],['A'],['D','A/C#'],['Bm','G'],['D','A'],['D']].map(makeBar)},
 {id:'chorus', name:'Refräng', bars:[['G'],['D'],['A'],['Bm'],['G'],['D','A'],['G','A'],['D']].map(makeBar)}
], form:[{id:'f1',source:'intro',count:1,instruction:''},{id:'f2',source:'verse',count:1,instruction:''},{id:'f3',source:'chorus',count:1,instruction:''}]});
let preferences={selectAll:false};try{preferences.selectAll=JSON.parse(localStorage.getItem('harmis-editor-preferences')||'{}').selectAll===true;}catch{}
let rangeAnchor=null,pendingHouse=null,pendingPart=null,liveUndoKey=null,variantError='',selectedPart=null,renameState=null;
let model = initial(), past = [], future = [], tab = 'music', tool = '', panelOpen = false, selected = [], chordId = null, selectedBlock = 'f2', draft = null, message = '', error = '', resolution = 4, returnFocus = null;
const barById = id => model.sections.flatMap(s=>s.bars).find(b=>b.id===Number(id));
const sectionOf = id => model.sections.find(s=>s.bars.some(b=>b.id===Number(id)));
const selectedBar = () => barById(selected[0]);
const sourceBlock = block => model.form.find(b=>b.source===block.source&&!b.reuse);
const sectionById = id => model.sections.find(s=>s.id===id);
const selectedForm = () => model.form.find(b=>b.id===selectedBlock);
const visibleBars = () => model.form.filter(f=>!f.reuse).flatMap(f=>sectionById(f.source).bars);
const numberOf = id => visibleBars().findIndex(b=>b.id===Number(id))+1;
function sourceEndMeter(source){return source.bars.reduce((meter,b)=>b.meter||meter,source.entryMeter||model.meter);}
function meterFor(bar){let meter=model.meter;for(const block of model.form){const source=sectionById(block.source);if(block.reuse){meter=sourceEndMeter(source);continue;}for(const b of source.bars){if(b.meter)meter=b.meter;if(b.id===bar.id)return meter;}}return meter;}
const meterUnits = bar => Number(meterFor(bar).split('/')[0]);
const denominator = bar => Number(meterFor(bar).split('/')[1]);
const positions = bar => Array.from({length:Math.round(meterUnits(bar)*resolution/denominator(bar))},(_,i)=>1+i*denominator(bar)/resolution);
function beatLabel(n){const w=Math.floor(n),f=n-w;return f===0?String(w):`${w} + ${f===.25?'¼':f===.5?'½':'¾'}`;}
const selectionText = () => selectedPart&&sectionById(selectedPart)?sectionById(selectedPart).name+' · hela delen':selected.length ? `${sectionOf(selected[0]).name} · takt ${numberOf(selected[0])}${selected.length>1?' till '+numberOf(selected.at(-1)):''}${chordId?' · ackord':''}` : 'Välj ett ackord eller en takt i bladet';
function mutate(fn, text){liveUndoKey=null;past.push(clone(model));future=[];fn();message=text;error='';render();}
function fail(text){error=text;renderPanel();}
function currentChord(){const b=selectedBar();return b?.chords.find(c=>c.id===chordId)||b?.chords[0];}
function parseChordText(text){
 let parenthetical=false,groupDepth=0,out=[];
 for(const token of text.trim().split(/\s+/).filter(Boolean)){
  let name=token;if(name.startsWith('(')){if(groupDepth)throw Error('En parentes är redan öppen.');groupDepth=1;parenthetical=true;name=name.slice(1);}
  const balance=[...name].reduce((sum,ch)=>sum+(ch==='('?1:ch===')'?-1:0),0);
  const closes=balance===-1&&name.endsWith(')');if(closes)name=name.slice(0,-1);
  if(balance < -1 || balance > 0)throw Error('Kontrollera parenteserna i ackordet.');
  let depth=0;for(const char of name){if(char==='(')depth++;if(char===')'&&--depth<0)throw Error('Kontrollera parenteserna i ackordet.');}if(depth!==0)throw Error('Kontrollera parenteserna i ackordet.');
  const ascii=name.replaceAll('♯','#').replaceAll('♭','b');const match=ascii.match(/^([A-G][b#]?)(.*?)(?:\/([A-G][b#]?))?$/);
  if(!/^N\.?C\.?$/i.test(ascii)&&!['%','-'].includes(ascii)&&(!match||!/^(?:(?:maj|Maj|M|m|min|dim|aug|sus|add|alt|omit|no)|[0-9b#()+°ø/\-])*$/u.test(match[2])))throw Error('Skriv ett ackord, till exempel D, Bm eller A/C#.');
  if(closes&&!groupDepth)throw Error('En avslutande parentes saknar början.');
  out.push({name,parenthetical});if(closes){groupDepth=0;parenthetical=false;}
 }
 if(groupDepth)throw Error('Stäng parentesen innan du går vidare.');
 if(out.length>4)throw Error('Högst fyra ackord ryms i den här prototypens takt.');
 return out;
}
function serialize(bar){return bar.chords.map(c=>c.parenthetical?`(${c.name})`:c.name).join(' ');}
function commitDraft(fullRender=true,variantChoice=null){
 if(!draft)return true;
 const d=draft,b=barById(d.barId),input=$(d.kind==='panel'?'#panel-chords':'#score-edit');if(input)d.value=input.value;
 let parsed;try{parsed=parseChordText(d.value);}catch(e){draft.error=e.message;renderScore();if(d.kind==='panel'&&$('#panel-chord-feedback'))$('#panel-chord-feedback').textContent=draft.error;focusDraft(false);return false;}
 const targetIndex=d.chordId?b.chords.findIndex(c=>c.id===d.chordId):-1;
 const remaining=targetIndex<0?0:b.chords.length-1;if(parsed.length+remaining>4){draft.error='Högst fyra ackord i en takt. Välj hela takten för att ersätta alla.';renderScore();if(d.kind==='panel'&&$('#panel-chord-feedback'))$('#panel-chord-feedback').textContent=draft.error;focusDraft(false);return false;}
 const old=targetIndex<0?b.chords:b.chords.slice(targetIndex,targetIndex+1);
 if(d.value===d.original){draft=null;renderScore();return true;}
 const next=parsed.map((c,i)=>({...old[i],...c,id:old[i]?.id||++uid,variant:old[i]?.variant||'',start:parsed.length===old.length?old[i].start:(parsed.length===2&&targetIndex<0?i*2+1:i+1)}));
 const changes=next.flatMap((c,i)=>old[i]?.variant&&old[i].name!==c.name?[{before:old[i].name,after:c.name,variant:old[i].variant}]:[]);
 if(changes.length&&!variantChoice){draft.variantChanges=changes;renderPanel();if(innerWidth<761){panelOpen=true;render();$('.panel').focus();}return false;}
 if(variantChoice==='remove')next.forEach((c,i)=>{if(old[i]?.name!==c.name){c.variant='';delete c.variantPass;delete c.variantFollowing;delete c.variantVoice;}});
 if(targetIndex>=0){const start=b.chords[targetIndex].start,end=b.chords[targetIndex+1]?.start??meterUnits(b)+1;next.forEach((c,i)=>c.start=start+i*(end-start)/next.length);const step=denominator(b)/resolution;if(next.some(c=>Math.abs((c.start-1)/step-Math.round((c.start-1)/step))>.001)){draft.error='Bytena ryms inte på valt rutnät. Välj hela takten eller ändra placeringen i Ändra ackord.';renderScore();if(d.kind==='panel'&&$('#panel-chord-feedback'))$('#panel-chord-feedback').textContent=draft.error;focusDraft(false);return false;}}
 else if(next.some(c=>c.start>meterUnits(b))){draft.error='Ackorden ryms inte med standardplaceringen i taktarten.';renderScore();if(d.kind==='panel'&&$('#panel-chord-feedback'))$('#panel-chord-feedback').textContent=draft.error;focusDraft(false);return false;}
 draft=null;past.push(clone(model));future=[];if(targetIndex<0)b.chords=next;else b.chords.splice(targetIndex,1,...next);if(!b.chords.some(c=>c.id===chordId))chordId=null;for(const c of next)model.recent=[c.name,...model.recent.filter(n=>n!==c.name)].slice(0,8);message='Ackorden uppdaterades i bladet.';error='';if(fullRender)render();else{renderScore();const undo=document.querySelector('[data-action=undo]');if(undo)undo.disabled=false;}return true;
}
function beginEdit(barId,target,shift=false,caret=null){
 if(!commitRename()||!commitDraft(false))return;selectedPart=null;
 const b=barById(barId);chordId=target?Number(target):null;
 if(shift&&selected.length){const bars=sectionOf(barId).bars,anchor=bars.findIndex(v=>v.id===selected[0]),end=bars.findIndex(v=>v.id===barId);if(anchor<0){selected=[barId];message='Markera ett spann inom samma del.';}else selected=bars.slice(Math.min(anchor,end),Math.max(anchor,end)+1).map(v=>v.id);chordId=null;render();return;}
 selected=[barId];let original=chordId?(b.chords.find(c=>c.id===chordId)?.parenthetical?`(${b.chords.find(c=>c.id===chordId).name})`:b.chords.find(c=>c.id===chordId)?.name||''):serialize(b);
 rangeAnchor=null;pendingHouse=null;panelOpen=false;draft={barId,chordId,value:original,original,error:''};error='';message='Redigera ackordraden. Enter sparar; Escape avbryter.';render();focusDraft(preferences.selectAll,caret);
}
function focusDraft(all,caret=null){const input=$(draft?.kind==='panel'?'#panel-chords':'#score-edit');if(!input)return;input.focus({preventScroll:true});if(all)input.select();else input.setSelectionRange(caret??input.value.length,caret??input.value.length);input.closest('.bar')?.scrollIntoView({block:'nearest',inline:'nearest'});}
function selectBar(barId,extend=false){
 if(!commitRename()||!commitDraft(false))return;selectedPart=null;const b=barById(barId);if(!b)return;
 const anchor=rangeAnchor??(extend?selected[0]:null);chordId=null;pendingHouse=null;
 if(anchor!=null){const section=sectionOf(barId);if(!section.bars.some(b=>b.id===anchor)){message='Välj sista takten inom samma del.';render();return;}const a=section.bars.findIndex(b=>b.id===anchor),z=section.bars.findIndex(b=>b.id===barId);selected=section.bars.slice(Math.min(a,z),Math.max(a,z)+1).map(b=>b.id);rangeAnchor=null;message=selected.length+' takter markerade.';}
 else{selected=[barId];message='Takten är markerad. Klicka på ackorden för att skriva.';}
 error='';render();
}
function selectChord(barId,id,caret=null){
 if(!commitRename()||!commitDraft(false))return;const b=barById(barId),c=b?.chords.find(c=>c.id===id);if(!c)return;
 if(chordId===id&&selected.length===1&&selected[0]===barId){const index=b.chords.indexOf(c),prefix=b.chords.slice(0,index).map(c=>c.parenthetical?'('+c.name+')':c.name).join(' ');beginEdit(barId,null,false,caret===null?null:prefix.length+(index?1:0)+caret);return;}
 selectedPart=null;selected=[barId];chordId=id;rangeAnchor=null;pendingHouse=null;panelOpen=false;error='';message='Ackordet är markerat. Klicka igen för att redigera taktens ackordrad.';render();
}
function selectPart(id){if(!commitDraft(false))return;const part=sectionById(id);if(!part)return;selectedPart=id;selected=part.bars.map(b=>b.id);chordId=null;rangeAnchor=null;pendingHouse=null;selectedBlock=model.form.find(f=>f.source===id&&!f.reuse)?.id;panelOpen=false;error='';message='Hela '+part.name+' är markerad.';render();}
function commitRename(){if(!renameState)return true;const part=sectionById(renameState.id),value=($('#part-name')?.value??renameState.value).trim();if(!value||value.length>80||model.sections.some(s=>s.id!==part.id&&s.name.toLocaleLowerCase('sv')===value.toLocaleLowerCase('sv'))){renameState.value=value;renameState.error=!value?'Skriv ett namn för delen.':'Välj ett eget namn, högst 80 tecken.';renderScore();$('#part-name')?.focus();return false;}renameState=null;if(part.name===value){render();return true;}mutate(()=>part.name=value,'Delens namn uppdaterades även i låtformen.');return true;}
function clickCaret(chord,clientX){const text=chord.textContent,font=getComputedStyle(chord),canvas=document.createElement('canvas'),context=canvas.getContext('2d');context.font=font.font;const x=clientX-chord.getBoundingClientRect().left-parseFloat(font.paddingLeft);let best=0,distance=Infinity;for(let i=0;i<=text.length;i++){const d=Math.abs(context.measureText(text.slice(0,i)).width-x);if(d<distance){distance=d;best=i;}}return best;}
function barActions(b){if(selectedPart||chordId||draft||rangeAnchor!==null||selected.length!==1||!selected.includes(b.id)||b.id!==selected.at(-1))return '';return `<div class="bar-actions" role="group" aria-label="Åtgärder för markerad takt">${btn('×','delete-bar:'+b.id,'bar-delete',`aria-label="Ta bort takt ${numberOf(b.id)}" title="${sectionOf(b.id).bars.length===1?'Töm delens sista takt':'Ta bort takt '+numberOf(b.id)}"`)}${btn('<svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true"><rect x="8" y="8" width="11" height="12" rx="2" fill="none" stroke="currentColor" stroke-width="1.6"/><path d="M15 5V4H4v12h1" fill="none" stroke="currentColor" stroke-width="1.6"/><path d="M13.5 11v6m-3-3h6" stroke="currentColor" stroke-width="1.3"/></svg>','duplicate-bar:'+b.id,'',`aria-label="Duplicera takt ${numberOf(b.id)} och infoga efter" title="Duplicera och infoga efter"`)}</div>`;}
function deleteBar(id){const section=sectionOf(id),index=section.bars.findIndex(b=>b.id===id),b=section.bars[index],all=visibleBars(),globalIndex=all.findIndex(b=>b.id===id),next=all[globalIndex+1],repeatTarget=next||all[globalIndex-1],nextMeter=next?meterFor(next):null,spans=section.bars.filter(b=>b.houseSpan).map(b=>clone(b.houseSpan)),last=section.bars.length===1,hasRepeat=b.repeatStart||b.repeatEnd;mutate(()=>{if(repeatTarget){repeatTarget.repeatStart ||= b.repeatStart;repeatTarget.repeatEnd ||= b.repeatEnd;}if(next){if(b.meter&&!next.meter)next.meter=nextMeter;if(b.key&&!next.key)next.key=b.key;}if(last){const empty=makeBar([]);empty.id=b.id;empty.meter=b.meter;empty.key=b.key;Object.assign(b,empty);}else section.bars.splice(index,1);section.bars.forEach(b=>b.houseSpan=null);for(const span of spans){span.barIds=span.barIds.filter(barId=>barId!==id);span.length=span.barIds.length;if(span.length)barById(span.barIds[0]).houseSpan=span;}selected=[section.bars[Math.min(index,section.bars.length-1)].id];chordId=null;rangeAnchor=null;},last?'Sista takten tömdes. Delens X tar bort hela delen.':hasRepeat?'Takten togs bort. Repristecknet flyttades till '+(next?'nästa':'föregående')+' takt.':'Takten togs bort. Ångra återställer den.');}
function partHasContent(section){return section.bars.some(b=>b.chords.length||b.attacks.length||b.repeatStart||b.repeatEnd||b.houseSpan||b.key||(b.meter&&b.meter!==(section.entryMeter||model.meter)));}
function requestDeletePart(id){const source=sectionById(id);if(!source)return;if(partHasContent(source)){pendingPart=id;render();return;}deletePart(id);}
function deletePart(id){const entryMeters=new Map(model.sections.filter(s=>s.id!==id&&s.bars.length).map(s=>[s.id,meterFor(s.bars[0])]));mutate(()=>{model.form=model.form.filter(f=>f.source!==id);model.sections=model.sections.filter(s=>s.id!==id);for(const block of model.form.filter(f=>!f.reuse)){const section=sectionById(block.source),first=section.bars[0];if(first&&!first.meter&&meterFor(first)!==entryMeters.get(section.id))first.meter=entryMeters.get(section.id);}selected=selected.filter(barId=>barById(barId));if(!selected.length)chordId=null;if(!model.form.some(f=>f.id===selectedBlock))selectedBlock=model.form[0]?.id||null;pendingPart=null;selectedPart=null;renameState=null;rangeAnchor=null;pendingHouse=null;},'Delen och dess återanvändningar togs bort. Ångra återställer dem.');}
function deletePartDialog(){if(!pendingPart)return '';const part=sectionById(pendingPart),refs=model.form.filter(f=>f.source===part.id&&f.reuse).length;return `<dialog class="delete-part-dialog" aria-labelledby="delete-part-title"><h2 id="delete-part-title">Ta bort ${esc(part.name)}?</h2><p>Delen innehåller musik och har ${part.bars.length} takter.</p>${refs?`<p>${refs} återanvändning${refs===1?'':'ar'} av delen tas också bort från formen.</p>`:''}<p>Du kan återställa allt med Ångra.</p><div class="row wrap">${btn('Behåll delen','part-delete-cancel','outline','autofocus')}${btn('Ta bort delen','part-delete-confirm','danger')}</div></dialog>`;}
function variantLabel(c){const pass=c.variantPass||2,prefix=pass===2?(c.variantFollowing?'Från andra gången':'Andra gången'):(c.variantFollowing?'Från gång '+pass:'Gång '+pass);return prefix+': '+c.variant+(c.variantVoice?' · '+c.variantVoice:'');}
function liveVariant(){const c=currentChord(),b=selectedBar();if(!c||!b)return;const value=$('#variant').value.trim(),pass=Number($('#variant-pass').value),following=$('#variant-following').checked,voice=$('#variant-voice').value.trim();let parsed;try{parsed=value?parseChordText(value):[];if(value&&(!Number.isInteger(pass)||pass<2||pass>16))throw Error('Spelomgången måste vara 2 till 16.');variantError='';}catch(e){variantError=e.message;}const feedback=$('#variant-feedback');if(variantError){if(feedback){feedback.textContent=variantError;feedback.classList.add('warning');}return;}const variant=parsed.map(v=>v.parenthetical?'('+v.name+')':v.name).join(' '),next={variant,variantPass:pass,variantFollowing:following,variantVoice:voice};if(Object.entries(next).every(([key,value])=>c[key]===value))return;const key='variant:'+c.id;if(liveUndoKey!==key){past.push(clone(model));future=[];liveUndoKey=key;}Object.assign(c,next);message=variant?'Varianten uppdateras direkt.':'Varianten togs bort.';if(feedback){feedback.textContent=variant?variantLabel(c):'Tomt fält tar bort varianten.';feedback.classList.remove('warning');}renderScore();syncUndoButtons();}
function syncUndoButtons(){const undo=$('[data-action="undo"]'),redo=$('[data-action="redo"]');if(undo)undo.disabled=!past.length;if(redo)redo.disabled=!future.length;}
function captureFocus(){const active=document.activeElement;return active?{id:active.id,action:active.dataset?.action,selector:active.dataset?.chord?`[data-chord="${active.dataset.chord}"]`:active.dataset?.start?`[data-start="${active.dataset.start}"]`:active.dataset?.duration?`[data-duration="${active.dataset.duration}"]`:active.hasAttribute('data-chord-grid')?'[data-chord-grid]':null,start:typeof active.selectionStart==='number'?active.selectionStart:null,end:typeof active.selectionEnd==='number'?active.selectionEnd:null}:null;}
function restoreFocus(saved){const target=saved?.id?document.getElementById(saved.id):saved?.action?$(`[data-action="${saved.action}"]`):saved?.selector?$(saved.selector):null;if(target){target.focus({preventScroll:true});if(saved.start!==null&&target.setSelectionRange&&target.type!=='number')try{target.setSelectionRange(saved.start,saved.end);}catch{}}}
function nextChordPosition(b,c,direction){const i=b.chords.indexOf(c),grid=positions(b).filter(n=>n>=(b.chords[i-1]?.start??0)&&n>(b.chords[i-1]?.start??0)&&n<(b.chords[i+1]?.start??meterUnits(b)+1));return direction<0?grid.filter(n=>n<c.start-.0001).at(-1):grid.find(n=>n>c.start+.0001);}
function chordTools(b){const c=b.chords.find(c=>c.id===chordId);if(!c||draft||selected[0]!==b.id)return '';const left=nextChordPosition(b,c,-1),right=nextChordPosition(b,c,1);return `<div class="chord-tools" role="group" aria-label="Placera ${esc(c.name)}"><button data-action="chord-step:${c.id}:-1" aria-label="Flytta ${esc(c.name)} åt vänster" ${left==null?'disabled':''}>←</button><button data-action="chord-step:${c.id}:1" aria-label="Flytta ${esc(c.name)} åt höger" ${right==null?'disabled':''}>→</button><select data-chord-grid aria-label="Notvärde för ackordets placeringssteg">${[4,8,16].map(n=>`<option value="${n}" ${n===resolution?'selected':''}>1/${n}</option>`).join('')}</select><span>Slag ${beatLabel(c.start)}</span></div>`;}
function positionChordTools(){for(const row of document.querySelectorAll('.score-row')){const base=innerWidth<761?87:85;let needed=base;for(const variant of row.querySelectorAll('.variant'))needed=Math.max(needed,variant.offsetTop+variant.scrollHeight+13);row.style.setProperty('--bar-needed-height',needed+'px');}const tools=$('.chord-tools');if(!tools)return;const b=tools.closest('.bar'),bounds=b.getBoundingClientRect(),scene=$('.scene').getBoundingClientRect(),width=tools.getBoundingClientRect().width,x=bounds.left;tools.style.left=(Math.max(scene.left+8,Math.min(x,scene.right-width-8))-bounds.left)+'px';}
function addRecent(name){if(!needBar())return;const b=selectedBar();if(b.chords.length>=4)return fail('Högst fyra ackord ryms i denna mockups takt.');const anchor=b.chords.find(c=>c.id===chordId),index=anchor?b.chords.indexOf(anchor)+1:b.chords.length,previous=b.chords[index-1],end=b.chords[index]?.start??meterUnits(b)+1;let start=!previous?1:positions(b).find(n=>n>previous.start&&n<end);if(b.chords.length===1&&index===1&&previous.start===1&&meterUnits(b)>=3&&end>3)start=3;if(start==null)return fail('Ingen ledig startpunkt efter ackordet på valt rutnät. Välj ett finare notvärde.');mutate(()=>{const c={id:++uid,name,parenthetical:false,start,variant:''};b.chords.splice(index,0,c);chordId=c.id;model.recent=[name,...model.recent.filter(v=>v!==name)].slice(0,8);},name+' lades till på slag '+beatLabel(start)+'.');}

function duplicateBars(ids){const section=sectionOf(ids[0]),index=section.bars.findIndex(b=>b.id===ids.at(-1));mutate(()=>{const spans=section.bars.filter(b=>b.houseSpan).map(owner=>({owner,first:owner.houseSpan.barIds[0],last:owner.houseSpan.barIds.at(-1)}));const bars=ids.map(id=>{const b=clone(barById(id));b.id=++uid;b.houseSpan=null;b.repeatStart=false;b.repeatEnd=false;b.rowBreak=false;b.pageBreak=false;b.chords.forEach(c=>c.id=++uid);return b;});section.bars.splice(index+1,0,...bars);for(const span of spans){const first=section.bars.findIndex(b=>b.id===span.first),last=section.bars.findIndex(b=>b.id===span.last);span.owner.houseSpan.barIds=section.bars.slice(first,last+1).map(b=>b.id);span.owner.houseSpan.length=span.owner.houseSpan.barIds.length;}selected=bars.map(b=>b.id);chordId=null;},'Kopian infogades efter markeringen. Repristecken och radbrytningar kopieras inte.');}
function applyHouse(number){mutate(()=>{visibleBars().filter(b=>b.houseSpan?.barIds.some(id=>selected.includes(id))).forEach(b=>b.houseSpan=null);barById(selected[0]).houseSpan={number,length:selected.length,barIds:[...selected]};pendingHouse=null;},'Huset visas över markerade takter.');}
function variantDecisionHTML(){return draft?.variantChanges?`<section class="variant-review"><h3>Variantackord behöver ett val</h3>${draft.variantChanges.map(c=>`<p class="hint">${esc(c.before)} blir ${esc(c.after)}. Varianten är ${esc(c.variant)}.</p>`).join('')}<p class="hint">Ingen ändring sparas förrän du väljer.</p><div class="options">${opt('Ta bort berörda varianter','variant-choice:remove')}${opt('Behåll berörda varianter','variant-choice:keep')}${opt('Återgå till texten','variant-choice:edit')}</div></section>`:'';}
function settingsBody(){return `<section><h3>När ackord öppnas för redigering</h3><label class="preference-option"><input type="radio" name="text-behavior" value="caret" ${preferences.selectAll?'':'checked'}> Skrivmarkör för små rättningar</label><label class="preference-option"><input type="radio" name="text-behavior" value="select" ${preferences.selectAll?'checked':''}> Markera all text i det öppnade fältet</label><p class="hint">Första klicket markerar ett ackord. Nästa klick på samma ackord öppnar taktens ackordrad. Klick i tom ackordyta öppnar raden direkt. Inställningen sparas i denna webbläsare.</p></section><section><h3>Markera takter</h3><p class="hint">Klicka på raden med taktnummer. För ett spann väljer du första takten, Markera flera och sedan sista takten.</p></section>`;}
function detachReuse(){const block=selectedForm(),source=sectionById(block.source);if(!block?.reuse)return;mutate(()=>{const copy=clone(source),ids=new Map();copy.id='part'+(++uid);let n=1;while(model.sections.some(s=>s.name===source.name+' · egen '+n))n++;copy.name=source.name+' · egen '+n;copy.bars.forEach(b=>{const old=b.id;b.id=++uid;ids.set(old,b.id);b.chords.forEach(c=>c.id=++uid);});copy.bars.forEach(b=>{if(b.houseSpan)b.houseSpan.barIds=b.houseSpan.barIds.map(id=>ids.get(id));});if(copy.bars.length&&!copy.bars[0].meter)copy.bars[0].meter=copy.entryMeter||meterFor(source.bars[0]);model.sections.push(copy);block.source=copy.id;block.reuse=false;selected=copy.bars.length?[copy.bars[0].id]:[];chordId=null;},'Delen är nu självständig. Antal gånger och anvisning är kvar.');}
function houseMarker(b){const section=sectionOf(b.id),start=section.bars.find(v=>v.houseSpan?.barIds.includes(b.id));if(!start)return '';const span=start.houseSpan,index=span.barIds.indexOf(b.id),row=scoreRowData(section).find(r=>r.some(v=>v.id===b.id)),col=row.findIndex(v=>v.id===b.id);if(index>0&&col>0)return '';let cells=0;while(col+cells<row.length&&row[col+cells].id===span.barIds[index+cells])cells++;const end=index+cells===span.barIds.length;return `<span class="marker" style="width:calc(${cells*100}% + ${cells-1}px);${end?'border-right:1px solid var(--ink)':''}">${index===0?esc(span.number)+'.':''}</span>`;}
function scoreBar(b){
 const selectedClass=selected.includes(b.id)?'selected':'';const editing=draft?.barId===b.id&&draft.kind!=='panel';
 return `<div class="bar ${selectedClass} ${editing?'editing':''} ${b.repeatStart?'repeat-start':''} ${b.repeatEnd?'repeat-end':''}" data-bar="${b.id}" tabindex="0" role="group" aria-label="Takt ${numberOf(b.id)}, ${esc(serialize(b)||'tom')}"><button class="bar-number" data-select-bar="${b.id}" aria-label="Markera takt ${numberOf(b.id)}" title="Markera takt ${numberOf(b.id)}">${numberOf(b.id)}</button>${houseMarker(b)}${b.rowBreak||b.pageBreak?`<span class="break-marker">${b.pageBreak?'Sidbrytning':'Radbrytning'}</span>`:''}${b.key||b.meter?`<span class="bar-change">${esc([b.key,b.meter].filter(Boolean).join(' · '))}</span>`:''}${`<div class="chord-area" data-chord-area="${b.id}" role="button" tabindex="0" aria-label="Redigera ackordraden i takt ${numberOf(b.id)}"></div>`}${b.chords.map(c=>`<span class="chord ${chordId===c.id&&!draft?'chord-selected':''}" data-chord="${c.id}" style="left:${8+(c.start-1)/meterUnits(b)*88}%" role="button" tabindex="0" aria-pressed="${chordId===c.id&&!draft}" aria-label="Markera ${esc(c.name)} i takt ${numberOf(b.id)}; klicka igen för att redigera ackordraden">${esc(c.parenthetical?'('+c.name+')':c.name)}</span>`).join('')}${b.chords.some(c=>c.variant)?`<div class="variant">${b.chords.filter(c=>c.variant).map(c=>`<div>${esc(variantLabel(c))}</div>`).join('')}</div>`:''}${b.attacks.length?`<div class="rhythm-line">${b.attacks.map(a=>`<span class="beat-tick" title="Anslag ${beatLabel(a.start)}, notvärde 1/${a.duration}">${beatLabel(a.start)}</span>`).join('')}</div>`:''}${barActions(b)}${chordTools(b)}${editing?`<input id="score-edit" class="score-edit" aria-label="Skriv ackord direkt i takt ${numberOf(b.id)}" value="${esc(draft.value)}" autocomplete="off" spellcheck="false">${draft.chordId?'':`<span class="editing-help">Hela takten · Mellanslag = nytt · Enter = klart</span>`}${draft.error?`<div class="score-error" role="alert">${esc(draft.error)}</div>`:''}`:''}</div>`;
}
function scoreRowData(s){let rows=[],row=[];for(const b of s.bars){if((b.rowBreak||b.pageBreak)&&row.length){rows.push(row);row=[];}row.push(b);if(row.length===4){rows.push(row);row=[];}}if(row.length)rows.push(row);return rows;}
function scoreRows(s){return scoreRowData(s).map(r=>`<div class="score-row ${r[0].pageBreak?'page-start':''}" style="--variant-lines:${Math.max(...r.map(b=>b.chords.filter(c=>c.variant).length))}">${r.map(scoreBar).join('')}</div>`).join('');}
function scoreHTML(){return `<h2 class="paper-title">${esc(model.title)}</h2><div class="credits"><span>${esc(model.artist)}</span><span>${esc(model.key)} · ${esc(model.meter)} · ${model.tempo} bpm</span></div>${!model.form.length?'<div class="empty-score">Inga delar kvar. Ångra återställer den senaste borttagningen.</div>':''}${model.form.map(block=>{const s=sectionById(block.source);if(block.reuse)return `<div class="reuse-score" data-score-block="${block.id}"><strong>${esc(s.name)} × ${block.count}</strong><p>Återanvänd del · följer originalets ackord${block.instruction?' · '+esc(block.instruction):''}</p>${btn('Visa originaldelen', 'goto-source:'+s.id)}</div>`;return `<section class="score-section ${selectedPart===s.id?'part-selected':''}" id="section-${s.id}" data-score-block="${block.id}"><div class="section-title">${renameState?.id===s.id?`<input id="part-name" aria-label="Delens namn" maxlength="80" value="${esc(renameState.value)}">${btn('Spara','part-rename-save','outline')}${btn('Avbryt','part-rename-cancel')}${renameState.error?`<span class="title-error" role="alert">${esc(renameState.error)}</span>`:''}`:btn(`${esc(s.name)}${block.count>1?' × '+block.count:''}`,'select-part:'+s.id,'part-name',`aria-pressed="${selectedPart===s.id}" title="Markera hela delen"`)}<span>${s.bars.length} takter${block.instruction?' · '+esc(block.instruction):''}</span>${selectedPart===s.id&&!renameState?`<div class="part-actions">${btn('Ändra titel','rename-part:'+s.id,'outline')}${btn('×','delete-part:'+s.id,'part-delete',`aria-label="Ta bort delen ${esc(s.name)}" title="Ta bort delen ${esc(s.name)}"`)}</div>`:''}</div>${scoreRows(s)}</section>`;}).join('')}`;}
function renderScore(){const saved=captureFocus(),paper=$('.paper'),scroll=$('.scene')?.scrollTop||0;if(paper)paper.innerHTML=scoreHTML();if($('.scene'))$('.scene').scrollTop=scroll;restoreFocus(saved);positionChordTools();}
function changeStartsHTML(b){if(!b?.chords.length)return '<p class="hint">Skriv ackord i takten först.</p>';return `<h3>Ordning på ackordsbyten</h3><p class="hint">Startpunkterna går från vänster till höger.</p>${b.chords.map((c,i)=>`<div class="beat-row"><span class="name" title="${esc(c.name)}">${esc(c.name)}</span><select aria-label="${esc(c.name)} börjar på" data-start="${c.id}">${[...new Set([...positions(b),c.start])].sort((a,b)=>a-b).map(n=>`<option value="${n}" ${n===c.start?'selected':''}>Slag ${beatLabel(n)}</option>`).join('')}</select>${btn('↑','chord-up:'+c.id,'',`aria-label="Flytta ${esc(c.name)} före föregående ackord" ${i===0?'disabled':''}`)}</div>`).join('')}`;}
function resolutionHTML(){return `<label class="eyebrow">Placera på</label><div class="resolution">${[4,8,16].map(n=>btn('1/'+n+'-delar','resolution:'+n,n===resolution?'active':'')).join('')}</div><p class="hint">Rutnät för startpunkter. Anslagens notvärden väljs separat.</p>`;}
function localChangesHTML(){return `<section><h3>Byten i markerad takt</h3><div class="two"><div class="field"><label for="local-key">Tonart</label><select id="local-key"><option value="">Inget byte</option>${['C','D','E','F','G','A','Bb','Bm','Dm','Em'].map(v=>`<option ${selectedBar()?.key===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label for="local-meter">Taktart</label><select id="local-meter"><option value="">Inget byte</option>${['4/4','3/4','6/8'].map(v=>`<option ${selectedBar()?.meter===v?'selected':''}>${v}</option>`).join('')}</select></div></div>${btn('Använd byten','local-apply','outline',selected.length===1?'':'disabled')}<p class="hint">Bytet börjar vid taktens första slag.</p></section>`;}
function musicBody(){const b=selectedBar(),c=currentChord();
 if(tool==='chord')return `<section><h3>Ackord i markerad takt</h3>${field('Ackord','panel-chords',draft?.kind==='panel'?draft.value:b?serialize(b):'','placeholder="Till exempel D A" '+(b?'':'disabled'))}<p class="hint">Mellanslag lägger till ackord. Parenteser skrivs direkt. Enter eller klick utanför sparar.</p><div id="panel-chord-feedback" class="hint" role="status">${draft?.kind==='panel'?esc(draft.error||''):''}</div></section><section><h3>Tidigare ackord</h3><div class="chips">${model.recent.map(n=>btn(esc(n),'recent:'+n,'',b?'':'disabled')).join('')}</div><p class="hint">Läggs till efter markerat ackord, eller sist i takten.</p>${btn('N.C.','nc','outline',b?'':'disabled')}</section><section><h3>Variantackord</h3>${field('Alternativ till '+(c?.name||'markerat ackord'),'variant',c?.variant||'','placeholder="Till exempel G Am" '+(c?'':'disabled'))}<div class="two">${field('Spelas gången','variant-pass',c?.variantPass||2,'type="number" min="2" max="16" '+(c?'':'disabled'))}${field('Stämma, valfritt','variant-voice',c?.variantVoice||'')}</div><label class="row small"><input type="checkbox" id="variant-following" ${c?.variantFollowing?'checked':''}> Även följande gånger</label><p class="hint variant-description">Skriv flera ackord med mellanslag. Giltiga ändringar uppdateras direkt.</p><div id="variant-feedback" class="hint" role="status">${c?.variant?esc(variantLabel(c)):'Tomt fält tar bort varianten.'}</div></section><section>${resolutionHTML()}${changeStartsHTML(b)}</section>`;
 if(tool==='rhythm')return `<section>${resolutionHTML()}${changeStartsHTML(b)}</section><section><h3>Anslag i ${b?meterFor(b):'markerad takt'}</h3><p class="hint">Klicka på en startpunkt. Varje anslag får ett eget notvärde.</p>${b?`<div class="beat-grid">${Array.from({length:meterUnits(b)},(_,beat)=>`<div class="beat-group"><span>Slag ${beat+1}</span>${positions(b).filter(n=>Math.floor(n)===beat+1).map(n=>btn(beatLabel(n),'attack:'+n,b.attacks.some(a=>a.start===n)?'on':'',`aria-label="Anslag på ${beatLabel(n)}" aria-pressed="${b.attacks.some(a=>a.start===n)}"`)).join('')}</div>`).join('')}</div><div class="attacks">${b.attacks.sort((a,z)=>a.start-z.start).map(a=>`<div class="beat-row"><span>${beatLabel(a.start)}</span><select data-duration="${a.start}" aria-label="Notvärde för anslag ${beatLabel(a.start)}">${[4,8,16].map(n=>`<option value="${n}" ${a.duration===n?'selected':''}>1/${n}</option>`).join('')}</select>${btn('×','attack:'+a.start,'',`aria-label="Ta bort anslag ${beatLabel(a.start)}"`)}</div>`).join('')}</div>`:'<div class="notice">Välj en takt i bladet för att ange anslag.</div>'}</section>`;
 if(tool==='repeats')return `<section><h3>Repris</h3><div class="options">${opt('Repris runt markeringen','repeat:both','Start i första takten, slut i sista')}${opt('Bara reprisstart','repeat:start')}${opt('Bara reprisslut','repeat:end')}</div></section><section><h3>Hus</h3><div class="two">${btn('Första hus','house:1','outline')}${btn('Andra hus','house:2','outline')}</div><div class="options" style="margin-top:8px">${opt('Eget hus…','house:custom','Välj eget nummer och granska spannet')}${opt('Ta bort hus i markeringen','house-remove')}</div></section>`;
 if(tool.startsWith('house')){const number=tool.split(':')[1]||'1';return `${btn('← Tillbaka till Repris & hus','tool:repeats','back-button')}<section>${field('Husnummer','house-number',number==='custom'?'1, 2':number)}<div class="notice">Gäller ${selectionText()}. Markera med taktnummerraden och Markera flera.</div><p class="hint">Hus läggs på markerade takter. Repristecken ändras separat.</p>${btn('Lägg till hus','house-apply','primary',selected.length?'':'disabled')}</section>`;}
 if(tool==='insert')return `<section><h3>Innehåll</h3><div class="options">${opt('Skriv ackord i takten','continue-edit','Klicka också direkt i bladet för att skriva')}${opt('Ny tom takt efter markeringen','insert-bar')}${opt('Duplicera markerade takter','duplicate-bars')}</div></section>${localChangesHTML()}`;
 if(tool==='layout')return `<section><h3>Rad och sida</h3><div class="options">${opt('Radbrytning före vald takt','break:row','Ny rad från markeringen')}${opt('Sidbrytning före vald takt','break:page','Visar en tydlig ny sida i mockupen')}${opt('Ta bort brytning','break:remove')}</div></section>`+localChangesHTML();
 return `<section><h3>Redigera direkt i bladet</h3><p class="hint">Klicka på ett ackord för att markera det. Klicka igen för att redigera hela ackordraden. Tomt utrymme i ackordraden öppnar skrivfältet direkt.</p><div class="notice">D A → två ackord<br>(D A) → båda inom parentes<br>Taktnummerrad → markera takten</div></section><section><h3>Verktyg</h3><div class="options">${opt('Ändra ackord','tool:chord','Tidigare ackord, N.C., varianter och byten')}${opt('Infoga','tool:insert','Takter, tonartsbyte och taktartsbyte')}${opt('Rytm','tool:rhythm','4-delar, 8-delar och 16-delar')}${opt('Repris & hus','tool:repeats','Repristecken och numrerade hus')}${opt('Layout','tool:layout','Lokala byten')}</div></section>`;
}
function formBody(){const block=selectedForm(),s=block?sectionById(block.source):null;return `<section><h3>Hela låtens form</h3><p class="hint">Klicka på en del. Flytta block upp eller ner för att ändra ordningen.</p><div class="form-list">${model.form.map((f,i)=>`<div class="form-block ${f.id===selectedBlock?'selected':''} ${f.reuse?'reuse':''}" data-block="${f.id}" draggable="true"><span class="drag-hint" aria-hidden="true">⋮⋮</span><span class="block-index">${String(i+1).padStart(2,'0')}</span>${btn(`<strong>${esc(sectionById(f.source).name)}${f.count>1?' × '+f.count:''}</strong><small>${f.reuse?'Återanvänd del · länkad':sectionById(f.source).bars.length+' takter'}${f.instruction?' · '+esc(f.instruction):''}</small>`,'block:'+f.id,'select-block',`aria-pressed="${f.id===selectedBlock}"`)}<div class="moves">${btn('↑','move:'+f.id+':-1','',`aria-label="Flytta block ${i+1} upp" ${i===0?'disabled':''}`)}${btn('↓','move:'+f.id+':1','',`aria-label="Flytta block ${i+1} ner" ${i===model.form.length-1?'disabled':''}`)}</div></div>`).join('')}</div><p class="reorder-note">Dra blocket eller använd pilarna. Återanvändningar kan placeras före och efter originaldelen.</p></section>${block&&!block.reuse?`<section><h3>${esc(s.name)}</h3><p class="hint">${s.bars.length} takter${block.count>1?' · spelas '+block.count+' gånger':''}${block.instruction?' · '+esc(block.instruction):''}. Ändringar i originaldelen följer med till alla återanvändningar.</p>${btn('Återanvänd','reuse','primary')}${btn('Visa i bladet','goto-source:'+s.id,'outline')}</section>`:''}${block?.reuse?`<section class="reuse-settings"><h3>Återanvänd del</h3><div class="context-pill">${esc(s.name)} · följer originaldelen</div>${field('Antal gånger','reuse-count',block.count,'type="number" min="1" max="16"')}${field('Anvisning','reuse-instruction',block.instruction,'placeholder="Till exempel instrumentalt"')}${btn('Använd inställningar','reuse-apply','primary')}<p class="hint">Markeringens färg och text visar att delen återanvänds. Flytta den genom att flytta blocket ovanför.</p>${btn('Visa originaldelen','goto-source:'+s.id,'outline')}${btn('Gör till egen del','detach-reuse','outline')}${btn('Ta bort återanvändning','reuse-remove','outline')}</section>`:''}`;}
function songBody(){return `<section>${field('Titel','song-title',model.title)}${field('Artist','song-artist',model.artist)}<div class="two">${field('Grundtonart','song-key',model.key)}${field('Tempo','song-tempo',model.tempo,'type="number" min="20" max="300"')}</div><div class="two"><div class="field"><label for="song-meter">Grundtaktart</label><select id="song-meter">${['4/4','3/4','6/8'].map(v=>`<option ${v===model.meter?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label for="song-status">Status</label><select id="song-status">${['Arbetsutkast','Granskad'].map(v=>`<option ${v===model.status?'selected':''}>${v}</option>`).join('')}</select></div></div>${field('Version','song-version',model.version)}${btn('Använd låtuppgifter','song-apply','primary')}</section><p class="hint">Låtuppgifter och form finns alltid på sina egna flikar. Textfilen är gömd i det föreslagna redigeringsläget.</p>`;}
function panelHTML(){const heading=tab==='settings'?'Inställningar':tab==='form'?'Låtform':tab==='song'?'Låtuppgifter':({'chord':'Ändra ackord','rhythm':'Rytm och ackordsbyten','repeats':'Repris & hus','insert':'Infoga','layout':'Layout'})[tool]||(tool.startsWith('house')?'Hus':'Musik');return `<div class="panel-nav" role="tablist" aria-label="Verktygsgrupper">${[['music','Musik'],['form','Form'],['song','Låt']].map(([id,label])=>btn(label,'tab:'+id,tab===id?'active':'',`role="tab" aria-selected="${tab===id}"`)).join('')}${btn('×','close-panel','sheet-close','aria-label="Stäng verktyg"')}</div><div class="panel-heading"><h2>${heading}</h2><p class="context">${tab==='music'?selectionText():esc(model.title)+' · hela arrangemanget'}</p></div><div class="panel-body">${variantDecisionHTML()}${tab==='settings'?settingsBody():tab==='music'?musicBody():tab==='form'?formBody():songBody()}${pendingHouse?`<section class="house-conflict"><h3>Husen överlappar</h3><p class="hint">Nytt hus ${esc(pendingHouse.number)}: takt ${numberOf(selected[0])} till ${numberOf(selected.at(-1))}.</p>${pendingHouse.spans.map(span=>`<p class="hint">Befintligt hus ${esc(span.number)}: takt ${numberOf(span.barIds[0])} till ${numberOf(span.barIds.at(-1))}.</p>`).join('')}${btn('Ersätt befintligt hus','house-replace','primary')}${btn('Behåll befintliga hus','house-cancel','outline')}</section>`:''}${error?`<div class="notice warning" role="alert">${esc(error)}</div>`:''}</div>${message?`<p class="live-message" role="status">${esc(message)}</p>`:''}`;}
function renderPanel(){const scroll=$('.panel-body')?.scrollTop||0,saved=captureFocus(),p=$('.panel');if(p)p.innerHTML=panelHTML();if($('.panel-body'))$('.panel-body').scrollTop=scroll;restoreFocus(saved);positionChordTools();}
function render(){const saved=captureFocus(),scroll=$('.scene')?.scrollTop||0,panelScroll=$('.panel-body')?.scrollTop||0;$('#app').innerHTML=`<div class="demo-strip"><strong>Harmis · hybridförslag</strong><a href="index.html">Design och bilder</a><span>Interaktiv mockup · ändringar stannar i minnet</span></div><div class="app-shell"><header class="header"><div class="row"><div class="grow"><div class="eyebrow">Bibliotek / Ackordblad</div><h1>${esc(model.title)}</h1><p class="hint">${esc(model.artist)} · Grundarrangemang</p></div><span class="hint small demo-description">Arbetsprototyp</span>${btn('Inställningar','tab:settings','outline')}${btn('Nollställ demo','reset','outline')}</div><div class="row meta"><span>Tonart <strong>${esc(model.key)}</strong></span><span>Taktart <strong>${esc(model.meter)}</strong></span><span>Tempo <strong>${model.tempo} bpm</strong></span><span class="grow"></span><span>${past.length?'Ändrat i minnet':'Demolåt'}</span></div></header><div class="toolbar">${[['chord','Ändra ackord'],['insert','Infoga'],['rhythm','Rytm'],['repeats','Repris & hus'],['layout','Layout']].map(([id,label])=>btn(label,'tool:'+id,'music-tool '+(tab==='music'&&tool===id?'active':''))).join('')}${btn('Musik','tab:music','mobile-only')}${btn('Form','tab:form','mobile-only')}${btn('Låt','tab:song','mobile-only')}<span class="spacer"></span>${btn('↶','undo','',`aria-label="Ångra" ${past.length?'':'disabled'}`)}${btn('↷','redo','',`aria-label="Gör om" ${future.length?'':'disabled'}`)}</div><div class="content"><main class="preview"><div class="preview-top"><span>Redigera i bladet</span><span>${rangeAnchor!==null?'Välj sista takten i samma del':selected.length?selectionText():'Klick markerar ackord · klick igen redigerar'}</span>${selected.length&&!selectedPart&&!draft&&!chordId?btn(rangeAnchor!==null?'Avbryt markering':'Markera flera',rangeAnchor!==null?'range-cancel':'range-start','range-button'):''}</div><div class="scene"><article class="paper" aria-label="Redigerbart ackordblad">${scoreHTML()}</article></div><footer class="footer"><span>${draft?'Enter sparar · Escape avbryter · klick utanför sparar':'Klick markerar ackord · klick igen redigerar'}</span><span class="desktop-help">Shift + klick markerar takter · ⌘/Ctrl + Z ångrar</span></footer></main><div class="panel-scrim ${panelOpen?'open':''}" data-action="close-panel"></div><aside class="panel ${panelOpen?'open':''}" aria-label="Verktygspanel" tabindex="-1">${panelHTML()}</aside></div></div>${deletePartDialog()}`;$('.scene').scrollTop=scroll;$('.panel-body').scrollTop=panelScroll;restoreFocus(saved);positionChordTools();if(pendingPart){$('.delete-part-dialog').showModal();$('.delete-part-dialog [autofocus]').focus();}}
function openPanel(){panelOpen=true;if(innerWidth<761){returnFocus=document.activeElement;render();$('.panel').focus();}}
function setTool(next){const same=tab==='music'&&tool===next;if(!commitDraft())return;tab='music';tool=next;error='';panelOpen=true;render();if(!same)$('.panel-body').scrollTop=0;if(innerWidth<761)$('.panel').focus();}
function needBar(){if(!selectedBar()){fail('Välj först en takt i bladet.');return false;}return true;}
function setChordStart(id,value){const b=selectedBar(),i=b.chords.findIndex(c=>c.id===Number(id)),start=Number(value);if(i<0||start<1||(i>0&&start<=b.chords[i-1].start)||(b.chords[i+1]&&start>=b.chords[i+1].start)||start>=meterUnits(b)+1)return fail('Ackordbyten måste ligga i ordning, utan samma startpunkt.');mutate(()=>b.chords[i].start=start,'Ackordbytet placerades på slag '+beatLabel(start)+'.');}
function attacksValid(b,attacks){return attacks.every(a=>a.start>=1&&a.start+denominator(b)/a.duration<=meterUnits(b)+1&&attacks.every(other=>other===a||a.start+denominator(b)/a.duration<=other.start||other.start+denominator(b)/other.duration<=a.start));}
function moveBlock(id,newIndex){const index=model.form.findIndex(b=>b.id===id);if(newIndex<0||newIndex>=model.form.length)return;const next=clone(model.form),[moving]=next.splice(index,1);next.splice(newIndex,0,moving);const previous=model.form;model.form=next;const invalid=visibleBars().some(b=>b.chords.some(c=>c.start>=meterUnits(b)+1)||!attacksValid(b,b.attacks));model.form=previous;if(invalid){fail('Flytten skulle ändra ärvd taktart och placera ackord eller anslag utanför en takt. Ange ett lokalt taktartsbyte först.');return;}mutate(()=>model.form=next,'Låtformens ordning uppdaterades.');}
document.addEventListener('click',e=>{
 if(e.target.matches('#part-name,#score-edit,#panel-chords,#variant,#variant-pass,#variant-voice,input[name="text-behavior"]'))return;
 const action=e.target.closest('[data-action]')?.dataset.action;
 if(e.target.closest('.chord-tools')&&!action)return;
 if(action?.startsWith('variant-choice:')){const choice=action.split(':')[1];if(choice==='edit'){delete draft.variantChanges;panelOpen=false;render();focusDraft(false);return;}commitDraft(true,choice);return;}
 if(action==='part-rename-cancel'){renameState=null;render();return;}
 if(action==='part-rename-save'){commitRename();return;}
 if(renameState&&!commitRename())return;
 const bar=e.target.closest('[data-bar]');if(bar&&!action){const id=Number(bar.dataset.bar),strip=e.target.closest('[data-select-bar]'),chord=e.target.closest('[data-chord]');if(strip||rangeAnchor!==null||e.shiftKey){selectBar(id,e.shiftKey);return;}if(chord){selectChord(id,Number(chord.dataset.chord),clickCaret(chord,e.clientX));return;}if(e.target.closest('[data-chord-area]')||!barById(id).chords.length)beginEdit(id,null);else selectBar(id);return;}
 if(draft&&!commitDraft(false))return;
 if(!action)return;
 if(action?.startsWith('select-part:')){selectPart(action.slice(12));return;}
 if(action?.startsWith('rename-part:')){const part=sectionById(action.slice(12));renameState={id:part.id,value:part.name,error:''};render();$('#part-name').focus();$('#part-name').select();return;}
 if(action?.startsWith('delete-part:')){requestDeletePart(action.slice(12));return;}
 if(action==='part-delete-confirm'){if(pendingPart)deletePart(pendingPart);return;}
 if(action==='part-delete-cancel'){const id=pendingPart;pendingPart=null;render();$(`[data-action="delete-part:${id}"]`)?.focus({preventScroll:true});return;}
 if(action?.startsWith('chord-step:')){const [,id,direction]=action.split(':'),b=selectedBar(),c=b.chords.find(c=>c.id===Number(id)),start=nextChordPosition(b,c,Number(direction));if(start!=null)setChordStart(id,start);return;}
 if(action==='range-start'){rangeAnchor=selected[0];panelOpen=false;message='Välj sista takten i samma del.';render();return;}
 if(action==='range-cancel'){rangeAnchor=null;message='Spannmarkeringen avbröts.';render();return;}
 if(action.startsWith('delete-bar:')){deleteBar(Number(action.split(':')[1]));return;}
 if(action.startsWith('duplicate-bar:')){duplicateBars([Number(action.split(':')[1])]);return;}
 if(action==='detach-reuse'){detachReuse();return;}
 if(action==='house-replace'){if(pendingHouse)applyHouse(pendingHouse.number);return;}
 if(action==='house-cancel'){pendingHouse=null;renderPanel();return;}
 if(action==='reset'){model=initial();past=[];future=[];selected=[];chordId=null;draft=null;rangeAnchor=null;pendingHouse=null;pendingPart=null;selectedPart=null;renameState=null;liveUndoKey=null;tab='music';tool='';panelOpen=false;message='';error='';render();return;}
 if(action==='undo'||action==='redo'){liveUndoKey=null;const from=action==='undo'?past:future,to=action==='undo'?future:past;if(from.length){to.push(clone(model));model=from.pop();renameState=null;if(!sectionById(selectedPart))selectedPart=null;if(selectedPart)selected=sectionById(selectedPart).bars.map(b=>b.id);selected=selected.filter(id=>barById(id));if(chordId&&!model.sections.some(s=>s.bars.some(b=>b.chords.some(c=>c.id===chordId))))chordId=null;message=action==='undo'?'Ändringen ångrades.':'Ändringen gjordes om.';error='';render();}return;}
 if(action.startsWith('tab:')){tab=action.slice(4);error='';panelOpen=true;render();$('.panel-body').scrollTop=0;if(innerWidth<761)$('.panel').focus();return;}
 if(action.startsWith('tool:')){setTool(action.slice(5));return;}
 if(action==='close-panel'){panelOpen=false;render();returnFocus?.focus?.();return;}
 if(action==='continue-edit'){if(needBar()){panelOpen=false;beginEdit(selected[0],chordId);}return;}
 if(action.startsWith('resolution:')){resolution=Number(action.slice(11));renderPanel();return;}
 if(action.startsWith('recent:')){addRecent(action.slice(7));return;}
 if(action==='nc'){if(!needBar())return;const b=selectedBar(),c=currentChord();beginEdit(b.id,c?.id);draft.value='N.C.';$('#score-edit').value='N.C.';commitDraft();return;}

 if(action.startsWith('chord-up:')){const b=selectedBar(),i=b.chords.findIndex(c=>c.id===Number(action.slice(9)));if(i<1)return;mutate(()=>{const a=b.chords[i-1],z=b.chords[i],start=a.start;a.start=z.start;z.start=start;b.chords.splice(i-1,2,z,a);},'Ackordens ordning ändrades. Startpunkterna ligger kvar.');return;}
 if(action.startsWith('attack:')){if(!needBar())return;const b=selectedBar(),start=Number(action.slice(7)),existing=b.attacks.find(a=>a.start===start);let next=existing?b.attacks.filter(a=>a!==existing):[...b.attacks,{start,duration:resolution}];if(!attacksValid(b,next))return fail('Anslaget överlappar ett annat anslag. Välj ett kortare notvärde först.');mutate(()=>b.attacks=next,existing?'Anslaget togs bort.':'Anslaget lades till.');return;}
 if(action.startsWith('house:')){if(!needBar())return;setTool(action);return;}
 if(action==='house-apply'){const value=$('#house-number').value.trim();if(!/^\d+(?:\s*,\s*\d+)*$/.test(value))return fail('Skriv husnummer, till exempel 1 eller 1, 2.');const overlaps=visibleBars().filter(b=>b.houseSpan?.barIds.some(id=>selected.includes(id)));if(overlaps.some(b=>JSON.stringify(b.houseSpan.barIds)!==JSON.stringify(selected))){pendingHouse={number:value,spans:overlaps.map(b=>clone(b.houseSpan))};renderPanel();return;}applyHouse(value);return;}
 if(action==='house-remove'){if(!needBar())return;mutate(()=>visibleBars().filter(b=>b.houseSpan?.barIds.some(id=>selected.includes(id))).forEach(b=>b.houseSpan=null),'Hela huset togs bort.');return;}
 if(action.startsWith('repeat:')){if(!needBar())return;const type=action.slice(7);mutate(()=>{if(type!=='end')barById(selected[0]).repeatStart=true;if(type!=='start')barById(selected.at(-1)).repeatEnd=true;},'Repristecknen visas i bladet.');return;}
 if(action.startsWith('block:')){selectedBlock=action.slice(6);error='';renderPanel();return;}
 if(action==='reuse'){const original=selectedForm();if(!original||original.reuse)return;const block={id:'reuse'+(++uid),source:original.source,reuse:true,count:1,instruction:''};mutate(()=>{const source=sectionById(original.source);if(source.bars.length){source.entryMeter=meterFor(source.bars[0]);if(!source.bars[0].meter)source.bars[0].meter=source.entryMeter;}model.form.push(block);selectedBlock=block.id;},'Delen återanvänds sist i formen. Flytta blocket till önskad plats.');return;}
 if(action==='reuse-apply'){const block=selectedForm(),count=Number($('#reuse-count').value),instruction=$('#reuse-instruction').value.trim();if(!Number.isInteger(count)||count<1||count>16)return fail('Välj ett heltal mellan 1 och 16.');mutate(()=>{block.count=count;block.instruction=instruction;},'Återanvändningens inställningar uppdaterades.');return;}
 if(action==='reuse-remove'){const block=selectedForm();if(!block?.reuse)return;mutate(()=>{model.form=model.form.filter(b=>b!==block);selectedBlock=sourceBlock(block).id;},'Återanvändningen togs bort.');return;}
 if(action.startsWith('move:')){const [,id,delta]=action.split(':');moveBlock(id,model.form.findIndex(b=>b.id===id)+Number(delta));return;}
 if(action.startsWith('goto-source:')){$('#section-'+action.slice(12))?.scrollIntoView({block:'start'});panelOpen=false;render();return;}
 if(action==='duplicate-bars'){if(needBar())duplicateBars([...selected]);return;}
 if(action==='insert-bar'){if(!needBar())return;const section=sectionOf(selected[0]),index=section.bars.findIndex(b=>b.id===selected.at(-1));mutate(()=>{const spans=section.bars.filter(b=>b.houseSpan).map(owner=>({owner,first:owner.houseSpan.barIds[0],last:owner.houseSpan.barIds.at(-1)}));const bars=action==='insert-bar'?[makeBar([])]:selected.map(id=>{const b=clone(barById(id));b.id=++uid;b.houseSpan=null;b.chords.forEach(c=>c.id=++uid);return b;});section.bars.splice(index+1,0,...bars);for(const span of spans){const first=section.bars.findIndex(b=>b.id===span.first),last=section.bars.findIndex(b=>b.id===span.last);span.owner.houseSpan.barIds=section.bars.slice(first,last+1).map(b=>b.id);span.owner.houseSpan.length=span.owner.houseSpan.barIds.length;}},action==='insert-bar'?'En tom takt lades till.':'Markerade takter duplicerades.');return;}
 if(action.startsWith('break:')){if(!needBar())return;const b=selectedBar(),type=action.slice(6);mutate(()=>{b.rowBreak=type==='row';b.pageBreak=type==='page';},'Brytningen uppdaterades i bladet.');return;}
 if(action==='local-apply'){if(!needBar())return;const b=selectedBar(),key=$('#local-key').value,meter=$('#local-meter').value,oldKey=b.key,oldMeter=b.meter;b.key=key;b.meter=meter;const invalid=model.sections.flatMap(s=>s.bars).some(bar=>bar.chords.some(c=>c.start>=meterUnits(bar)+1)||!attacksValid(bar,bar.attacks));b.key=oldKey;b.meter=oldMeter;if(invalid)return fail('Taktarten skulle placera ackord eller anslag utanför takten. Flytta dem först.');mutate(()=>{b.key=key;b.meter=meter;},'Lokala byten visas i bladet.');return;}
 if(action==='song-apply'){const title=$('#song-title').value.trim(),artist=$('#song-artist').value.trim(),key=$('#song-key').value.trim(),tempo=Number($('#song-tempo').value),meter=$('#song-meter').value,status=$('#song-status').value,version=$('#song-version').value.trim();if(!title||!/^[A-G](?:#|b|♯|♭)?m?$/.test(key)||!Number.isFinite(tempo)||tempo<20||tempo>300)return fail('Ange titel, tonart och tempo mellan 20 och 300.');const old=model.meter;model.meter=meter;const invalid=visibleBars().some(b=>b.chords.some(c=>c.start>=meterUnits(b)+1)||!attacksValid(b,b.attacks));model.meter=old;if(invalid)return fail('Grundtaktarten skulle placera ackord eller anslag utanför en takt. Flytta dem först.');mutate(()=>Object.assign(model,{title,artist,key,tempo,meter,status,version}),'Låtuppgifterna uppdaterades.');return;}
});
document.addEventListener('focusout',e=>{if(e.target.id==='part-name'&&renameState){const pending=renameState;setTimeout(()=>{if(renameState===pending&&document.activeElement?.id!=='part-name')commitRename();},0);}if(['variant','variant-pass','variant-voice','variant-following'].includes(e.target.id))liveUndoKey=null;if(['score-edit','panel-chords'].includes(e.target.id)&&draft){const pending=draft;setTimeout(()=>{if(draft===pending&&!['score-edit','panel-chords'].includes(document.activeElement?.id))commitDraft(false);},0);}});
document.addEventListener('input',e=>{
 if(e.target.id==='part-name'&&renameState){renameState.value=e.target.value;renameState.error='';return;}
 if(['variant','variant-pass','variant-voice'].includes(e.target.id)){liveVariant();return;}
 if(e.target.id==='panel-chords'){const b=selectedBar();if(!b)return;if(!draft||draft.kind!=='panel')draft={barId:b.id,chordId:null,kind:'panel',original:serialize(b),error:''};draft.value=e.target.value;draft.error='';delete draft.variantChanges;return;}
 if(e.target.id==='score-edit'&&draft){draft.value=e.target.value;draft.error='';delete draft.variantChanges;}
});
document.addEventListener('change',e=>{
 if(e.target.id==='variant-following'){liveVariant();liveUndoKey=null;return;}
 if(e.target.hasAttribute('data-chord-grid')){if(draft&&!commitDraft(false))return;resolution=Number(e.target.value);renderScore();renderPanel();return;}
 if(e.target.name==='text-behavior'){preferences.selectAll=e.target.value==='select';try{localStorage.setItem('harmis-editor-preferences',JSON.stringify(preferences));}catch{}message='Inställningen gäller nästa gång du öppnar ackordtext.';renderPanel();return;}
 if(e.target.dataset.start){setChordStart(e.target.dataset.start,e.target.value);return;}
 if(e.target.dataset.duration){const b=selectedBar(),start=Number(e.target.dataset.duration),duration=Number(e.target.value),next=b.attacks.map(a=>a.start===start?{...a,duration}:a);if(!attacksValid(b,next))return fail('Notvärdet överlappar nästa anslag eller går förbi taktens slut.');mutate(()=>b.attacks=next,'Anslagets notvärde ändrades.');}
});
document.addEventListener('keydown',e=>{
 if(e.target.id==='part-name'){if(e.isComposing)return;if(e.key==='Enter'){e.preventDefault();commitRename();}if(e.key==='Escape'){e.preventDefault();renameState=null;render();}return;}
 if(['score-edit','panel-chords'].includes(e.target.id)){if(e.isComposing)return;if(e.key==='Enter'){e.preventDefault();commitDraft();}if(e.key==='Escape'){e.preventDefault();draft=null;panelOpen=false;message='Textändringen avbröts.';render();}return;}
 if(e.key==='Escape'&&pendingPart){e.preventDefault();pendingPart=null;render();return;}
 if(e.key==='Escape'){rangeAnchor=null;pendingHouse=null;if(panelOpen&&innerWidth<761){panelOpen=false;render();}else{selected=[];chordId=null;selectedPart=null;renameState=null;error='';render();}return;}
 if(e.target.matches('input,textarea,select'))return;
 if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();document.querySelector(`[data-action="${e.shiftKey?'redo':'undo'}"]`).click();return;}
 if(e.target.closest('button'))return;
 const bar=e.target.closest('[data-bar]');if(bar&&(e.key==='Enter'||e.key===' ')){e.preventDefault();if(e.target.closest('[data-select-bar]'))selectBar(Number(bar.dataset.bar),e.shiftKey);else if(e.target.dataset.chord)selectChord(Number(bar.dataset.bar),Number(e.target.dataset.chord));else beginEdit(Number(bar.dataset.bar),null);}
});
let dragging='';document.addEventListener('dragstart',e=>{const block=e.target.closest('[data-block]');if(block){dragging=block.dataset.block;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',dragging);}});document.addEventListener('dragover',e=>{if(e.target.closest('[data-block]'))e.preventDefault();});document.addEventListener('drop',e=>{const block=e.target.closest('[data-block]');if(block&&dragging){e.preventDefault();moveBlock(dragging,model.form.findIndex(b=>b.id===block.dataset.block));dragging='';}});
window.hybrid={getState:()=>clone({model,selected,chordId,draft,tab,tool,panelOpen,resolution,pastCount:past.length,futureCount:future.length,message,error,preferences,rangeAnchor,pendingHouse,pendingPart,selectedPart,renameState}),select:(section,index)=>beginEdit(sectionById(section).bars[index].id,null),reset:()=>{model=initial();past=[];future=[];selected=[];chordId=null;selectedPart=null;renameState=null;draft=null;rangeAnchor=null;pendingHouse=null;render();}};
render();

document.fonts.ready.then(positionChordTools);
window.addEventListener('resize',positionChordTools);
