/* Isolated design study. Model changes stay in this page's memory. */
const $ = (s, root = document) => root.querySelector(s);
const esc = v => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone = x => JSON.parse(JSON.stringify(x));
const btn = iconButtonHTML;
const opt = (text, action, description = '') => btn(`${text}${description ? `<small>${description}</small>` : ''}`, action);
const field = (text, id, value, extra = '') => `<div class="field"><label for="${id}">${text}</label><input id="${id}" value="${esc(value)}" ${extra}></div>`;
let uid = 100;
const chords = values => values.map((name, i) => ({id:++uid, name, parenthetical:false, start:values.length === 2 ? i*2+1 : i+1, variant:''}));
const makeBar = values => ({id:++uid, chords:chords(values), attacks:[], house:'', houseSpan:null, rowBreak:false, pageBreak:false, repeatStart:false, repeatEnd:false, key:'', meter:''});
const initial = () => ({title:'Tro', artist:'Marie Fredriksson', key:'D', meter:'4/4', tempo:72, version:'Grundarrangemang', status:'Arbetsutkast', recent:['D','A','Bm','G','A/C#'], sections:[
 {id:'intro', name:'Intro', bars:[['D'],['G'],['D','A'],['D']].map(makeBar)},
 {id:'verse', name:'Vers', bars:[['D'],['G'],['Bm'],['A'],['D','A/C#'],['Bm','G'],['D','A'],['D']].map(makeBar)},
 {id:'chorus', name:'Refräng', bars:[['G'],['D'],['A'],['Bm'],['G'],['D','A'],['G','A'],['D']].map(makeBar)}
], form:[{id:'f1',source:'intro',count:1,instruction:''},{id:'f2',source:'verse',count:1,instruction:''},{id:'f3',source:'chorus',count:1,instruction:''}]});
let rangeAnchor=null,pendingHouse=null,pendingPart=null,selectedPart=null,renameState=null;
let model = initial(), past = [], future = [], tab = 'form', panelOpen = false, panelCollapsed = false, selected = [], chordId = null, selectedBlock = 'f2', draft = null, message = '', error = '', resolution = 4;
const barById = id => model.sections.flatMap(s=>s.bars).find(b=>b.id===Number(id));
const sectionOf = id => model.sections.find(s=>s.bars.some(b=>b.id===Number(id)));
const selectedBar = () => barById(selected[0]);
const sourceBlock = block => model.form.find(b=>b.source===block.source&&!b.reuse);
const sectionById = id => model.sections.find(s=>s.id===id);
const selectedForm = () => model.form.find(b=>b.id===selectedBlock);
const visibleBars = () => model.form.filter(f=>!f.reuse).flatMap(f=>sectionById(f.source).bars);
const numberOf = id => visibleBars().findIndex(b=>b.id===Number(id))+1;
function sourceEndMeter(source){return source.bars.reduce((meter,b)=>b.meter||meter,source.entryMeter||model.meter);}
function meterFor(bar){let meter=model.meter;for(const block of model.form){const source=sectionById(block.source);if(block.reuse){meter=sourceEndMeter(source);continue;}for(const b of source.bars){if(b.meter)meter=b.meter;if(b.id===bar.id)return meter;}}return meter;}
const meterUnits = bar => Number(meterFor(bar).split('/')[0]);
const denominator = bar => Number(meterFor(bar).split('/')[1]);
const positions = bar => Array.from({length:Math.round(meterUnits(bar)*resolution/denominator(bar))},(_,i)=>1+i*denominator(bar)/resolution);
function beatLabel(n){const w=Math.floor(n),f=n-w;return f===0?String(w):`${w} + ${f===.25?'¼':f===.5?'½':'¾'}`;}
const selectionText = () => selectedReuse&&selectedForm()?.reuse?sectionById(selectedForm().source).name+' · återanvänd del':selectedPart&&sectionById(selectedPart)?sectionById(selectedPart).name+' · hela delen':selected.length ? `${sectionOf(selected[0]).name} · takt ${numberOf(selected[0])}${selected.length>1?(selectionContiguous()?' till '+numberOf(selected.at(-1)):' · valda '+selectionNumbers()):''}${selectedVariantId?' · variant '+variantPassLabel(variantOwner()):chordId?' · ackord':''}` : 'Välj ett ackord eller en takt i bladet';
function mutate(fn, text){past.push(clone(model));future=[];fn();message=text;error='';render();}
function fail(text){error=text;render();}
function currentChord(){const b=singleBar();return b?.chords.find(c=>c.id===chordId)||b?.chords[0];}
function parseChordText(text){
 let parenthetical=false,groupDepth=0,out=[];
 for(const token of text.trim().split(/\s+/).filter(Boolean)){
  let name=token;if(name.startsWith('(')){if(groupDepth)throw Error('En parentes är redan öppen.');groupDepth=1;parenthetical=true;name=name.slice(1);}
  const balance=[...name].reduce((sum,ch)=>sum+(ch==='('?1:ch===')'?-1:0),0);
  const closes=balance===-1&&name.endsWith(')');if(closes)name=name.slice(0,-1);
  if(balance < -1 || balance > 0)throw Error('Kontrollera parenteserna i ackordet.');
  let depth=0;for(const char of name){if(char==='(')depth++;if(char===')'&&--depth<0)throw Error('Kontrollera parenteserna i ackordet.');}if(depth!==0)throw Error('Kontrollera parenteserna i ackordet.');
  const ascii=name.replaceAll('♯','#').replaceAll('♭','b');const match=ascii.match(/^([A-G][b#]?)(.*?)(?:\/([A-G][b#]?))?$/);
  if(!/^N\.?C\.?$/i.test(ascii)&&!['%','-'].includes(ascii)&&(!match||!/^(?:(?:maj|Maj|M|m|min|dim|aug|sus|add|alt|omit|no)|[0-9b#()+°ø/\-])*$/u.test(match[2])))throw Error('Skriv ett ackord, till exempel D, Bm eller A/C#.');
  if(closes&&!groupDepth)throw Error('En avslutande parentes saknar början.');
  out.push({name,parenthetical});if(closes){groupDepth=0;parenthetical=false;}
 }
 if(groupDepth)throw Error('Stäng parentesen innan du går vidare.');
 if(out.length>4)throw Error('Högst fyra ackord ryms i den här prototypens takt.');
 return out;
}
function serialize(bar){return bar.chords.map(c=>c.parenthetical?`(${c.name})`:c.name).join(' ');}
function commitDraft(fullRender=true,variantChoice=null){
 if(!draft)return true;if(draft.kind==='variant')return commitVariantDraft(fullRender);
 const d=draft,b=barById(d.barId),input=$('#score-edit');if(input)d.value=input.value;
 let parsed;try{parsed=parseChordText(d.value);}catch(e){draft.error=e.message;renderScore();focusDraft(false);return false;}
 const targetIndex=d.chordId?b.chords.findIndex(c=>c.id===d.chordId):-1;
 const remaining=targetIndex<0?0:b.chords.length-1;if(parsed.length+remaining>4){draft.error='Högst fyra ackord i en takt. Välj hela takten för att ersätta alla.';renderScore();focusDraft(false);return false;}
 const old=targetIndex<0?b.chords:b.chords.slice(targetIndex,targetIndex+1);
 if(d.value===d.original){draft=null;renderScore();return true;}
 const next=parsed.map((c,i)=>({...old[i],...c,id:old[i]?.id||++uid,variant:old[i]?.variant||'',start:parsed.length===old.length?old[i].start:(parsed.length===2&&targetIndex<0?i*2+1:i+1)}));
 const changes=next.flatMap((c,i)=>old[i]?.variant&&old[i].name!==c.name?[{before:old[i].name,after:c.name,variant:old[i].variant}]:[]);
 if(changes.length&&!variantChoice){draft.variantChanges=changes;contextView='';render();return false;}
 if(variantChoice==='remove')next.forEach((c,i)=>{if(old[i]?.name!==c.name){c.variant='';delete c.variantPass;delete c.variantFollowing;delete c.variantChords;delete c.variantAttacks;}});
 if(targetIndex>=0){const start=b.chords[targetIndex].start,end=b.chords[targetIndex+1]?.start??meterUnits(b)+1;next.forEach((c,i)=>c.start=start+i*(end-start)/next.length);const step=denominator(b)/resolution;if(next.some(c=>Math.abs((c.start-1)/step-Math.round((c.start-1)/step))>.001)){draft.error='Bytena ryms inte på valt rutnät. Välj hela takten eller ändra placeringen i Ändra ackord.';renderScore();focusDraft(false);return false;}}
 else if(next.some(c=>c.start>meterUnits(b))){draft.error='Ackorden ryms inte med standardplaceringen i taktarten.';renderScore();focusDraft(false);return false;}
 for(let i=0;i<next.length;i++){const delta=next[i].start-(old[i]?.start??next[i].start);next[i].variantChords=clone(next[i].variantChords||[]);next[i].variantAttacks=clone(next[i].variantAttacks||[]);next[i].variantChords.forEach(v=>v.start+=delta);next[i].variantAttacks.forEach(a=>a.start+=delta);}const beforeChords=b.chords;b.chords=targetIndex<0?next:[...b.chords.slice(0,targetIndex),...next,...b.chords.slice(targetIndex+1)];const valid=barMusicValid(b);b.chords=beforeChords;if(!valid){draft.error='En befintlig variant ryms inte efter ändringen. Justera varianten eller välj att ta bort den.';renderScore();focusDraft(false);return false;}
 draft=null;past.push(clone(model));future=[];if(targetIndex<0)b.chords=next;else b.chords.splice(targetIndex,1,...next);if(!b.chords.some(c=>c.id===chordId))chordId=null;for(const c of next)model.recent=[c.name,...model.recent.filter(n=>n!==c.name)].slice(0,8);message='Ackorden uppdaterades i bladet.';error='';if(fullRender)render();else{renderScore();const undo=document.querySelector('[data-action=undo]');if(undo)undo.disabled=false;}return true;
}
function beginEdit(barId,target,shift=false,caret=null){
 if(!commitRename()||!commitDraft(false))return;resetContext();selectedPart=null;
 const b=barById(barId);chordId=target?Number(target):null;
 if(shift&&selected.length){const bars=sectionOf(barId).bars,anchor=bars.findIndex(v=>v.id===selected[0]),end=bars.findIndex(v=>v.id===barId);if(anchor<0){selected=[barId];message='Markera ett spann inom samma del.';}else selected=bars.slice(Math.min(anchor,end),Math.max(anchor,end)+1).map(v=>v.id);chordId=null;render();return;}
 selected=[barId];let original=chordId?(b.chords.find(c=>c.id===chordId)?.parenthetical?`(${b.chords.find(c=>c.id===chordId).name})`:b.chords.find(c=>c.id===chordId)?.name||''):serialize(b);
 rangeAnchor=null;pendingHouse=null;panelOpen=false;draft={barId,chordId,value:original,original,error:''};error='';message='Redigera ackordraden. Enter sparar; Escape avbryter.';render();focusDraft(false,caret);
}
function focusDraft(all,caret=null){const input=$('#score-edit');if(!input)return;input.focus({preventScroll:true});if(all)input.select();else input.setSelectionRange(caret??input.value.length,caret??input.value.length);input.closest('.bar')?.scrollIntoView({block:'nearest',inline:'nearest'});}
function selectBar(barId,extend=false){
 if(!commitRename()||!commitDraft(false))return;resetContext();selectedPart=null;const b=barById(barId);if(!b)return;
 const anchor=rangeAnchor??(extend?selected[0]:null);chordId=null;pendingHouse=null;
 if(anchor!=null){const section=sectionOf(barId);if(!section.bars.some(b=>b.id===anchor)){message='Välj sista takten inom samma del.';render();return;}const a=section.bars.findIndex(b=>b.id===anchor),z=section.bars.findIndex(b=>b.id===barId);selected=section.bars.slice(Math.min(a,z),Math.max(a,z)+1).map(b=>b.id);rangeAnchor=null;message=selected.length+' takter markerade.';}
 else{selected=[barId];message='Takten är markerad. Klicka på ackorden för att skriva.';}
 error='';render();
}
function selectChord(barId,id,caret=null){
 if(!commitRename()||!commitDraft(false))return;const b=barById(barId),c=b?.chords.find(c=>c.id===id);if(!c)return;
 if(!selectedVariantId&&chordId===id&&selected.length===1&&selected[0]===barId){const index=b.chords.indexOf(c),prefix=b.chords.slice(0,index).map(c=>c.parenthetical?'('+c.name+')':c.name).join(' ');beginEdit(barId,null,false,caret===null?null:prefix.length+(index?1:0)+caret);return;}
 resetContext();selectedPart=null;selected=[barId];chordId=id;rangeAnchor=null;pendingHouse=null;panelOpen=false;error='';message='Ackordet är markerat. Klicka igen för att redigera taktens ackordrad.';render();queueChordReveal(caret===null);
}
function selectPart(id){if(!commitDraft(false))return;const part=sectionById(id);if(!part)return;resetContext();selectedPart=id;selected=part.bars.map(b=>b.id);chordId=null;rangeAnchor=null;pendingHouse=null;selectedBlock=model.form.find(f=>f.source===id&&!f.reuse)?.id;panelOpen=false;error='';message='Hela '+part.name+' är markerad.';render();}
function commitRename(){if(!renameState)return true;const part=sectionById(renameState.id),value=($('#part-name')?.value??renameState.value).trim();if(!value||value.length>80||model.sections.some(s=>s.id!==part.id&&s.name.toLocaleLowerCase('sv')===value.toLocaleLowerCase('sv'))){renameState.value=value;renameState.error=!value?'Skriv ett namn för delen.':'Välj ett eget namn, högst 80 tecken.';renderScore();$('#part-name')?.focus();return false;}renameState=null;if(part.name===value){render();return true;}mutate(()=>part.name=value,'Delens namn uppdaterades även i låtformen.');return true;}
function clickCaret(chord,clientX){const text=chord.textContent,font=getComputedStyle(chord),canvas=document.createElement('canvas'),context=canvas.getContext('2d');context.font=font.font;const x=clientX-chord.getBoundingClientRect().left-parseFloat(font.paddingLeft);let best=0,distance=Infinity;for(let i=0;i<=text.length;i++){const d=Math.abs(context.measureText(text.slice(0,i)).width-x);if(d<distance){distance=d;best=i;}}return best;}
function deleteBar(id){contextView='';const section=sectionOf(id),index=section.bars.findIndex(b=>b.id===id),b=section.bars[index],all=visibleBars(),globalIndex=all.findIndex(b=>b.id===id),next=all[globalIndex+1],repeatTarget=next||all[globalIndex-1],nextMeter=next?meterFor(next):null,spans=section.bars.filter(b=>b.houseSpan).map(b=>clone(b.houseSpan)),last=section.bars.length===1,hasRepeat=b.repeatStart||b.repeatEnd;mutate(()=>{if(repeatTarget){repeatTarget.repeatStart ||= b.repeatStart;repeatTarget.repeatEnd ||= b.repeatEnd;}if(next){if(b.meter&&!next.meter)next.meter=nextMeter;if(b.key&&!next.key)next.key=b.key;}if(last){const empty=makeBar([]);empty.id=b.id;empty.meter=b.meter;empty.key=b.key;Object.assign(b,empty);}else section.bars.splice(index,1);section.bars.forEach(b=>b.houseSpan=null);for(const span of spans){span.barIds=span.barIds.filter(barId=>barId!==id);span.length=span.barIds.length;if(span.length)barById(span.barIds[0]).houseSpan=span;}selected=[section.bars[Math.min(index,section.bars.length-1)].id];chordId=null;rangeAnchor=null;},last?'Sista takten tömdes. Delens X tar bort hela delen.':hasRepeat?'Takten togs bort. Repristecknet flyttades till '+(next?'nästa':'föregående')+' takt.':'Takten togs bort. Ångra återställer den.');}
function partHasContent(section){return section.bars.some(b=>b.chords.length||b.attacks.length||b.repeatStart||b.repeatEnd||b.houseSpan||b.key||(b.meter&&b.meter!==(section.entryMeter||model.meter)));}
function requestDeletePart(id){const source=sectionById(id);if(!source)return;if(partHasContent(source)){pendingPart=id;render();return;}deletePart(id);}
function deletePart(id){const entryMeters=new Map(model.sections.filter(s=>s.id!==id&&s.bars.length).map(s=>[s.id,meterFor(s.bars[0])]));mutate(()=>{model.form=model.form.filter(f=>f.source!==id);model.sections=model.sections.filter(s=>s.id!==id);for(const block of model.form.filter(f=>!f.reuse)){const section=sectionById(block.source),first=section.bars[0];if(first&&!first.meter&&meterFor(first)!==entryMeters.get(section.id))first.meter=entryMeters.get(section.id);}selected=selected.filter(barId=>barById(barId));if(!selected.length)chordId=null;if(!model.form.some(f=>f.id===selectedBlock))selectedBlock=model.form[0]?.id||null;pendingPart=null;resetContext();selectedPart=null;renameState=null;rangeAnchor=null;pendingHouse=null;},'Delen och dess återanvändningar togs bort. Ångra återställer dem.');}
function deletePartDialog(){if(!pendingPart)return '';const part=sectionById(pendingPart),refs=model.form.filter(f=>f.source===part.id&&f.reuse).length;return `<dialog class="delete-part-dialog" aria-labelledby="delete-part-title"><h2 id="delete-part-title">Ta bort ${esc(part.name)}?</h2><p>Delen innehåller musik och har ${part.bars.length} takter.</p>${refs?`<p>${refs} återanvändning${refs===1?'':'ar'} av delen tas också bort från formen.</p>`:''}<p>Du kan återställa allt med Ångra.</p><div class="row wrap">${btn('Behåll delen','part-delete-cancel','outline','autofocus')}${btn('Ta bort delen','part-delete-confirm','danger')}</div></dialog>`;}
function variantLabel(c){return variantPassLabel(c)+' · '+c.variant;}
function syncUndoButtons(){const undo=$('[data-action="undo"]'),redo=$('[data-action="redo"]');if(undo)undo.disabled=!past.length;if(redo)redo.disabled=!future.length;}
function captureFocus(){const active=document.activeElement;return active?{id:active.id,action:active.dataset?.action,selector:active.dataset?.variantChord?`[data-variant-chord="${active.dataset.variantChord}"]`:active.dataset?.variantStart?`[data-variant-start="${active.dataset.variantStart}"]`:active.dataset?.variantDuration?`[data-variant-duration="${active.dataset.variantDuration}"]`:active.dataset?.barCheck?`[data-bar-check="${active.dataset.barCheck}"]`:active.dataset?.chord?`[data-chord="${active.dataset.chord}"]`:active.dataset?.start?`[data-start="${active.dataset.start}"]`:active.dataset?.duration?`[data-duration="${active.dataset.duration}"]`:active.hasAttribute('data-chord-grid')?'[data-chord-grid]':null,start:typeof active.selectionStart==='number'?active.selectionStart:null,end:typeof active.selectionEnd==='number'?active.selectionEnd:null}:null;}
function restoreFocus(saved){let target=saved?.id?document.getElementById(saved.id):saved?.action?$(`[data-action="${saved.action}"]`):saved?.selector?$(saved.selector):null;if(target?.disabled&&saved?.action?.startsWith('chord-up:'))target=$(`[data-start="${saved.action.slice(9)}"]`);if(target?.disabled&&saved?.action?.startsWith('variant-up:'))target=$(`[data-variant-start="${saved.action.slice(11)}"]`);if(target&&!target.disabled){target.focus({preventScroll:true});if(saved.start!==null&&target.setSelectionRange&&target.type!=='number')try{target.setSelectionRange(saved.start,saved.end);}catch{}}}
function nextChordPosition(b,c,direction){const i=b.chords.indexOf(c),grid=positions(b).filter(n=>n>=(b.chords[i-1]?.start??0)&&n>(b.chords[i-1]?.start??0)&&n<(b.chords[i+1]?.start??meterUnits(b)+1));return direction<0?grid.filter(n=>n<c.start-.0001).at(-1):grid.find(n=>n>c.start+.0001);}
function addRecent(name){if(!needSingleBar())return;const b=selectedBar();if(b.chords.length>=4)return fail('Högst fyra ackord ryms i denna mockups takt.');const anchor=b.chords.find(c=>c.id===chordId),index=anchor?b.chords.indexOf(anchor)+1:b.chords.length,previous=b.chords[index-1],end=b.chords[index]?.start??meterUnits(b)+1;let start=!previous?1:positions(b).find(n=>n>previous.start&&n<end);if(b.chords.length===1&&index===1&&previous.start===1&&meterUnits(b)>=3&&end>3)start=3;if(start==null)return fail('Ingen ledig startpunkt efter ackordet på valt rutnät. Välj ett finare notvärde.');mutate(()=>{const c={id:++uid,name,parenthetical:false,start,variant:''};b.chords.splice(index,0,c);chordId=c.id;model.recent=[name,...model.recent.filter(v=>v!==name)].slice(0,8);},name+' lades till på slag '+beatLabel(start)+'.');}

function duplicateBars(ids){const section=sectionOf(ids[0]),index=section.bars.findIndex(b=>b.id===ids.at(-1));mutate(()=>{const spans=section.bars.filter(b=>b.houseSpan).map(owner=>({owner,first:owner.houseSpan.barIds[0],last:owner.houseSpan.barIds.at(-1)}));const bars=ids.map(id=>{const b=clone(barById(id));b.id=++uid;b.houseSpan=null;b.repeatStart=false;b.repeatEnd=false;b.rowBreak=false;b.pageBreak=false;copyChordIdentities(b);return b;});section.bars.splice(index+1,0,...bars);for(const span of spans){const first=section.bars.findIndex(b=>b.id===span.first),last=section.bars.findIndex(b=>b.id===span.last);span.owner.houseSpan.barIds=section.bars.slice(first,last+1).map(b=>b.id);span.owner.houseSpan.length=span.owner.houseSpan.barIds.length;}selected=bars.map(b=>b.id);chordId=null;contextView='';},'Kopian infogades efter markeringen. Repristecken och radbrytningar kopieras inte.');}
function applyHouse(number){mutate(()=>{visibleBars().filter(b=>b.houseSpan?.barIds.some(id=>selected.includes(id))).forEach(b=>b.houseSpan=null);barById(selected[0]).houseSpan={number,length:selected.length,barIds:[...selected]};pendingHouse=null;},'Huset visas över markerade takter.');}
function variantDecisionHTML(){return draft?.variantChanges?`<section class="variant-review"><h3>Variantackord behöver ett val</h3>${draft.variantChanges.map(c=>`<p class="hint">${esc(c.before)} blir ${esc(c.after)}. Varianten är ${esc(c.variant)}.</p>`).join('')}<p class="hint">Ingen ändring sparas förrän du väljer.</p><div class="options">${opt('Ta bort berörda varianter','variant-choice:remove')}${opt('Behåll berörda varianter','variant-choice:keep')}${opt('Återgå till texten','variant-choice:edit')}</div></section>`:'';}
function detachReuse(){const block=selectedForm(),source=sectionById(block.source);if(!block?.reuse)return;mutate(()=>{const copy=clone(source),ids=new Map();copy.id='part'+(++uid);let n=1;while(model.sections.some(s=>s.name===source.name+' · egen '+n))n++;copy.name=source.name+' · egen '+n;copy.bars.forEach(b=>{const old=b.id;b.id=++uid;ids.set(old,b.id);copyChordIdentities(b);});copy.bars.forEach(b=>{if(b.houseSpan)b.houseSpan.barIds=b.houseSpan.barIds.map(id=>ids.get(id));});if(copy.bars.length&&!copy.bars[0].meter)copy.bars[0].meter=copy.entryMeter||meterFor(source.bars[0]);model.sections.push(copy);block.source=copy.id;block.reuse=false;resetContext();selectedPart=copy.id;selected=copy.bars.map(b=>b.id);chordId=null;},'Delen är nu självständig. Antal gånger och anvisning är kvar.');}
function houseMarker(b){const section=sectionOf(b.id),start=section.bars.find(v=>v.houseSpan?.barIds.includes(b.id));if(!start)return '';const span=start.houseSpan,index=span.barIds.indexOf(b.id),row=scoreRowData(section).find(r=>r.some(v=>v.id===b.id)),col=row.findIndex(v=>v.id===b.id);if(index>0&&col>0)return '';let cells=0;while(col+cells<row.length&&row[col+cells].id===span.barIds[index+cells])cells++;const end=index+cells===span.barIds.length;return `<span class="marker" style="width:calc(${cells*100}% + ${cells-1}px);${end?'border-right:1px solid var(--ink)':''}">${index===0?esc(span.number)+'.':''}</span>`;}
function scoreBar(b){
 const selectedClass=selected.includes(b.id)?'selected':'';const editing=draft?.barId===b.id&&draft.kind!=='variant';
 return `<div class="bar ${selectedClass} ${editing?'editing':''} ${b.repeatStart?'repeat-start':''} ${b.repeatEnd?'repeat-end':''}" data-bar="${b.id}" tabindex="0" role="group" aria-label="Takt ${numberOf(b.id)}, ${esc(serialize(b)||'tom')}"><div class="measure-frame">${rhythmNotationHTML(b,b.attacks)}</div><button class="bar-number" data-select-bar="${b.id}" aria-label="Markera takt ${numberOf(b.id)}" title="Markera takt ${numberOf(b.id)}">${numberOf(b.id)}</button>${barCheckHTML(b)}${houseMarker(b)}${b.rowBreak||b.pageBreak?`<span class="break-marker">${b.pageBreak?'Sidbrytning':'Radbrytning'}</span>`:''}${b.key||b.meter?`<span class="bar-change">${esc([b.key,b.meter].filter(Boolean).join(' · '))}</span>`:''}${`<div class="chord-area" data-chord-area="${b.id}" role="button" tabindex="0" aria-label="Redigera ackordraden i takt ${numberOf(b.id)}"></div>`}${b.chords.map(c=>`<span class="chord ${chordId===c.id&&!selectedVariantId&&!draft?'chord-selected':''}" data-chord="${c.id}" style="left:${8+(c.start-1)/meterUnits(b)*88}%" role="button" tabindex="0" aria-pressed="${chordId===c.id&&!selectedVariantId&&!draft}" aria-label="Markera ${esc(c.name)} i takt ${numberOf(b.id)}; klicka igen för att redigera ackordraden">${esc(c.parenthetical?'('+c.name+')':c.name)}</span>`).join('')}<div class="variant-stack">${variantRowsHTML(b)}</div>${barCornerActions(b)}${chordTools(b)}${editing?`<input id="score-edit" class="score-edit" aria-label="Skriv ackord direkt i takt ${numberOf(b.id)}" value="${esc(draft.value)}" autocomplete="off" spellcheck="false">${draft.chordId?'':`<span class="editing-help">Hela takten · Mellanslag = nytt · Enter = klart</span>`}${draft.error?`<div class="score-error" role="alert">${esc(draft.error)}</div>`:''}`:''}</div>`;
}
function scoreColumns(s){return innerWidth<761&&s.bars.some(b=>b.chords.some(c=>c.variant||c.variantAttacks?.length||variantOwnerId===c.id))?2:4;}
function scoreRowData(s){const columns=scoreColumns(s);let rows=[],row=[];for(const b of s.bars){if((b.rowBreak||b.pageBreak)&&row.length){rows.push(row);row=[];}row.push(b);if(row.length===columns){rows.push(row);row=[];}}if(row.length)rows.push(row);return rows;}
function scoreRows(s){return scoreRowData(s).map(r=>`<div class="score-row ${r[0].pageBreak?'page-start':''}" style="--columns:${scoreColumns(s)}">${r.map(scoreBar).join('')}</div>`).join('');}
function scoreHTML(){return `<h2 class="paper-title">${esc(model.title)}</h2><div class="credits"><span>${esc(model.artist)}</span><span>${esc(model.key)} · ${esc(model.meter)} · ${model.tempo} bpm</span></div>${!model.form.length?'<div class="empty-score">Inga delar kvar. Ångra återställer den senaste borttagningen.</div>':''}${model.form.map(block=>{const s=sectionById(block.source);if(block.reuse)return reuseScoreHTML(block,s);return `<section class="score-section ${selectedPart===s.id?'part-selected':''}" id="section-${s.id}" data-score-block="${block.id}"><div class="section-title">${renameState?.id===s.id?`<input id="part-name" aria-label="Delens namn" maxlength="80" value="${esc(renameState.value)}">${btn('Spara','part-rename-save','outline')}${btn('Avbryt','part-rename-cancel')}${renameState.error?`<span class="title-error" role="alert">${esc(renameState.error)}</span>`:''}`:btn(`${esc(s.name)}${block.count>1?' × '+block.count:''}`,'select-part:'+s.id,'part-name',`aria-pressed="${selectedPart===s.id}" title="Markera hela delen"`)}<span>${s.bars.length} takter${block.instruction?' · '+esc(block.instruction):''}</span>${partActionsHTML(s,block)}</div>${scoreRows(s)}</section>`;}).join('')}`;}
function renderScore(){const stripScroll=captureStripScroll();const contextScroll=$('.context-body')?.scrollTop||0,saved=captureFocus(),paper=$('.paper'),scroll=$('.scene')?.scrollTop||0;if(paper)paper.innerHTML=scoreHTML();if($('.scene'))$('.scene').scrollTop=scroll;restoreFocus(saved);positionChordTools();restoreStripScroll(stripScroll);if($('.context-body'))$('.context-body').scrollTop=contextScroll;}
function changeStartsHTML(b){if(!b?.chords.length)return '<p class="hint">Skriv ackord i takten först.</p>';return `${b.chords.map((c,i)=>`<div class="beat-row"><span class="name" title="${esc(c.name)}">${esc(c.name)}</span><select aria-label="${esc(c.name)} börjar på" data-start="${c.id}">${[...new Set([...positions(b),c.start])].sort((a,b)=>a-b).map(n=>`<option value="${n}" ${n===c.start?'selected':''}>Slag ${beatLabel(n)}</option>`).join('')}</select>${btn('↑','chord-up:'+c.id,'',`aria-label="Flytta ${esc(c.name)} före föregående ackord" ${i===0?'disabled':''}`)}</div>`).join('')}`;}
function resolutionHTML(){return `<label class="eyebrow">Placera på</label><div class="resolution">${[4,8,16].map(n=>btn('1/'+n,'resolution:'+n,n===resolution?'active':'')).join('')}</div>`;}
function localChangesHTML(){return `<section><h3>Byten i markerad takt</h3><div class="two"><div class="field"><label for="local-key">Tonart</label><select id="local-key"><option value="">Inget byte</option>${['C','D','E','F','G','A','Bb','Bm','Dm','Em'].map(v=>`<option ${singleBar()?.key===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label for="local-meter">Taktart</label><select id="local-meter"><option value="">Inget byte</option>${['4/4','3/4','6/8'].map(v=>`<option ${singleBar()?.meter===v?'selected':''}>${v}</option>`).join('')}</select></div></div>${btn('Använd byten','local-apply','outline',singleBar()?'':'disabled')}<p class="hint">Bytet börjar vid taktens första slag.</p></section>`;}
function formBody(){return `<section><h3>Hela låtens form</h3><p class="hint">Välj ett block för att markera delen på bladet. Delens verktyg visas vid dess rubrik.</p><div class="form-list">${model.form.map((f,i)=>`<div class="form-block ${f.id===selectedBlock?'selected':''} ${f.reuse?'reuse':''}" data-block="${f.id}" draggable="true"><span class="drag-hint" aria-hidden="true">⋮⋮</span><span class="block-index">${String(i+1).padStart(2,'0')}</span>${btn(`<strong>${esc(sectionById(f.source).name)}${f.count>1?' × '+f.count:''}</strong><small>${f.reuse?'Återanvänd del · länkad':sectionById(f.source).bars.length+' takter'}${f.instruction?' · '+esc(f.instruction):''}</small>`,'block:'+f.id,'select-block',`aria-pressed="${f.id===selectedBlock}"`)}</div>`).join('')}</div><p class="reorder-note">Dra blocket för att ändra spelordningen. Ackord och lokala inställningar redigeras på bladet.</p></section>`;}
function songBody(){return `<section>${field('Titel','song-title',model.title)}${field('Artist','song-artist',model.artist)}<div class="two">${field('Grundtonart','song-key',model.key)}${field('Tempo','song-tempo',model.tempo,'type="number" min="20" max="300"')}</div><div class="two"><div class="field"><label for="song-meter">Grundtaktart</label><select id="song-meter">${['4/4','3/4','6/8'].map(v=>`<option ${v===model.meter?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label for="song-status">Status</label><select id="song-status">${['Arbetsutkast','Granskad'].map(v=>`<option ${v===model.status?'selected':''}>${v}</option>`).join('')}</select></div></div>${field('Version','song-version',model.version)}${btn('Använd låtuppgifter','song-apply','primary')}</section><p class="hint">Låtuppgifter och form finns alltid på sina egna flikar. Textfilen är gömd i det föreslagna redigeringsläget.</p>`;}
function panelHTML(){const heading=tab==='song'?'Låtuppgifter':'Låtform';return `<div class="panel-nav" role="tablist" aria-label="Globala verktyg">${[['form','Form'],['song','Låt']].map(([id,label])=>btn(label,'tab:'+id,tab===id?'active':'',`role="tab" aria-selected="${tab===id}"`)).join('')}${btn('×','close-panel','sheet-close',`aria-label="${innerWidth<761?'Stäng menyn':'Fäll in menyn'}"`)}</div><div class="panel-heading"><h2>${heading}</h2><p class="context">${esc(model.title)} · hela arrangemanget</p></div><div class="panel-body">${tab==='song'?songBody():formBody()}${error&&!contextView?`<div class="notice warning" role="alert">${esc(error)}</div>`:''}</div>`;}
function renderPanel(){const scroll=$('.panel-body')?.scrollTop||0,saved=captureFocus(),p=$('.panel');if(p)p.innerHTML=panelHTML();if($('.panel-body'))$('.panel-body').scrollTop=scroll;restoreFocus(saved);positionChordTools();}
function render(){const stripScroll=captureStripScroll(),popupScroll=$('.popup-parameters')?.scrollTop||0;const contextScroll=$('.context-body')?.scrollTop||0,saved=captureFocus(),scroll=$('.scene')?.scrollTop||0,panelScroll=$('.panel-body')?.scrollTop||0;$('#app').innerHTML=`<div class="demo-strip"><strong>Harmis · hybridförslag</strong><a href="index.html">Design och bilder</a><span>Interaktiv mockup · ändringar stannar i minnet</span></div><div class="app-shell"><div class="toolbar">${btn('Form','tab:form','mobile-only')}${btn('Låt','tab:song','mobile-only')}<span class="spacer"></span>${btn('↶','undo','',`aria-label="Ångra" ${past.length?'':'disabled'}`)}${btn('↷','redo','',`aria-label="Gör om" ${future.length?'':'disabled'}`)}${panelToggleHTML()}${btn('Nollställ demo','reset','outline')}</div><div class="content ${panelCollapsed?'panel-collapsed':''}"><main class="preview"><div class="preview-top"><span>Redigera i bladet</span><span>${rangeAnchor!==null?'Välj sista takten i samma del':selected.length||selectedReuse?selectionText():'Klick markerar ackord · klick igen redigerar'}</span></div><div class="scene"><article class="paper" aria-label="Redigerbart ackordblad">${scoreHTML()}</article></div><footer class="footer"><span>${draft?'Enter sparar · Escape avbryter · klick utanför sparar':'Klick markerar ackord · klick igen redigerar'}</span><span class="desktop-help">Shift + klick markerar takter · ⌘/Ctrl + Z ångrar</span></footer></main><div class="panel-scrim ${panelOpen?'open':''}" data-action="close-panel"></div><aside id="editor-panel" class="panel ${panelOpen?'open':''}" aria-label="Verktygspanel" tabindex="-1">${panelHTML()}</aside></div></div>${contextPopupHTML()}${draft?.variantChanges?`<dialog class="variant-choice-dialog" aria-label="Hantera variantackord">${variantDecisionHTML()}</dialog>`:''}${deletePartDialog()}<span class="sr-only" role="status">${esc(message)}</span>`;$('.scene').scrollTop=scroll;$('.panel-body').scrollTop=panelScroll;restoreFocus(saved);positionChordTools();restoreStripScroll(stripScroll);if($('.context-body'))$('.context-body').scrollTop=contextScroll;const popup=$('#context-popup');if(popup){popup.showModal();restoreFocus(saved);$('.popup-parameters').scrollTop=popupScroll;}const variantDialog=$('.variant-choice-dialog');if(variantDialog){variantDialog.showModal();$('[data-action="variant-choice:edit"]')?.focus({preventScroll:true});}if(pendingPart){$('.delete-part-dialog').showModal();$('.delete-part-dialog [autofocus]').focus();}}
function needBar(){if(!selectedBar()){fail('Välj först en takt i bladet.');return false;}return true;}
function setChordStart(id,value){const b=selectedBar(),i=b.chords.findIndex(c=>c.id===Number(id)),start=Number(value);if(i<0||start<1||(i>0&&start<=b.chords[i-1].start)||(b.chords[i+1]&&start>=b.chords[i+1].start)||start>=meterUnits(b)+1)return fail('Ackordbyten måste ligga i ordning, utan samma startpunkt.');const c=b.chords[i],before=clone(c),delta=start-c.start;c.start=start;(c.variantChords||[]).forEach(v=>v.start+=delta);(c.variantAttacks||[]).forEach(a=>a.start+=delta);const valid=barMusicValid(b),after=clone(c);Object.assign(c,before);if(!valid)return fail('Flytten skulle placera en variant utanför grundackordets spann. Justera varianten först.');mutate(()=>Object.assign(c,after),'Ackordbytet placerades på slag '+beatLabel(start)+'.');}
function attacksValid(b,attacks){return attacks.every(a=>a.start>=1&&a.start+denominator(b)/a.duration<=meterUnits(b)+1&&attacks.every(other=>other===a||a.start+denominator(b)/a.duration<=other.start||other.start+denominator(b)/other.duration<=a.start));}
function moveBlock(id,newIndex){const index=model.form.findIndex(b=>b.id===id);if(newIndex<0||newIndex>=model.form.length)return;const next=clone(model.form),[moving]=next.splice(index,1);next.splice(newIndex,0,moving);const previous=model.form;model.form=next;const invalid=visibleBars().some(b=>!barMusicValid(b));model.form=previous;if(invalid){fail('Flytten skulle ändra ärvd taktart och placera ackord eller anslag utanför en takt. Ange ett lokalt taktartsbyte först.');return;}mutate(()=>model.form=next,'Låtformens ordning uppdaterades.');}
document.addEventListener('click',e=>{
 if(e.target.closest('.bar-check'))return;
 if(e.target.matches('#part-name,#score-edit,#variant-edit'))return;
 const action=e.target.closest('[data-action]')?.dataset.action;
 if(e.target.closest('.context-tools,.bar-corner-actions')&&!action)return;
 if(action?.startsWith('variant-choice:')){const choice=action.split(':')[1];if(choice==='edit'){delete draft.variantChanges;panelOpen=false;render();focusDraft(false);return;}commitDraft(true,choice);return;}
 if(action==='part-rename-cancel'){renameState=null;render();return;}
 if(action==='part-rename-save'){commitRename();return;}
 if(renameState&&!commitRename())return;
 const variant=e.target.closest('[data-variant-chord]'),variantArea=e.target.closest('[data-variant-area]');if(variant){selectVariant(Number(variant.closest('[data-bar]').dataset.bar),Number(variant.dataset.variantOwner),Number(variant.dataset.variantChord),clickCaret(variant,e.clientX));return;}if(variantArea){if(!commitDraft(false))return;const b=variantArea.closest('[data-bar]');if(selected[0]!==Number(b.dataset.bar))selectBar(Number(b.dataset.bar));beginVariantEdit(Number(variantArea.dataset.variantArea));return;}if(e.target.closest('.variant-lane')&&!action)return;
 const bar=e.target.closest('[data-bar]');if(bar&&!action){const id=Number(bar.dataset.bar),strip=e.target.closest('[data-select-bar]'),chord=e.target.closest('[data-chord]');if(strip||rangeAnchor!==null||e.shiftKey){selectBar(id,e.shiftKey);return;}if(chord){selectChord(id,Number(chord.dataset.chord),clickCaret(chord,e.clientX));return;}if(e.target.closest('[data-chord-area]')||!barById(id).chords.length)beginEdit(id,null);else selectBar(id);return;}
 if(draft&&!commitDraft(false))return;
 if(!action)return;
 if(handleNotationAction(action)||handleContextAction(action))return;
 if(action?.startsWith('select-part:')){selectPart(action.slice(12));return;}
 if(action?.startsWith('rename-part:')){const part=sectionById(action.slice(12));renameState={id:part.id,value:part.name,error:''};render();$('#part-name').focus();$('#part-name').select();return;}
 if(action?.startsWith('delete-part:')){requestDeletePart(action.slice(12));return;}
 if(action==='part-delete-confirm'){if(pendingPart)deletePart(pendingPart);return;}
 if(action==='part-delete-cancel'){const id=pendingPart;pendingPart=null;render();$(`[data-action="delete-part:${id}"]`)?.focus({preventScroll:true});return;}
 if(action?.startsWith('chord-step:')){const [,id,direction]=action.split(':'),b=selectedBar(),c=b.chords.find(c=>c.id===Number(id)),start=nextChordPosition(b,c,Number(direction));if(start!=null)setChordStart(id,start);return;}
 if(action.startsWith('delete-bar:')){deleteBar(Number(action.split(':')[1]));return;}
 if(action.startsWith('duplicate-bar:')){duplicateBars([Number(action.split(':')[1])]);return;}
 if(action==='detach-reuse'){resetContext();detachReuse();return;}
 if(action==='house-replace'){if(pendingHouse)applyHouse(pendingHouse.number);return;}
 if(action==='house-cancel'){pendingHouse=null;renderPanel();renderScore();return;}
 if(action==='reset'){model=initial();past=[];future=[];selected=[];chordId=null;draft=null;rangeAnchor=null;pendingHouse=null;pendingPart=null;resetContext();selectedPart=null;renameState=null;tab='form';panelOpen=false;message='';error='';render();return;}
 if(action==='undo'||action==='redo'){const from=action==='undo'?past:future,to=action==='undo'?future:past;if(from.length){to.push(clone(model));model=from.pop();if(selectedVariantId&&!currentVariant())selectedVariantId=null;if(selectedReuse&&!model.form.some(f=>f.id===selectedReuse))resetContext();renameState=null;if(!sectionById(selectedPart))selectedPart=null;if(selectedPart)selected=sectionById(selectedPart).bars.map(b=>b.id);selected=selected.filter(id=>barById(id));if(chordId&&!model.sections.some(s=>s.bars.some(b=>b.chords.some(c=>c.id===chordId))))chordId=null;message=action==='undo'?'Ändringen ångrades.':'Ändringen gjordes om.';error='';render();}return;}
 if(action.startsWith('tab:')){tab=action.slice(4);error='';panelCollapsed=false;panelOpen=true;render();$('.panel-body').scrollTop=0;if(innerWidth<761)$('.panel').focus();return;}
 if(action==='toggle-panel'){const mobile=innerWidth<761;const opening=mobile?!panelOpen:panelCollapsed;panelOpen=opening;panelCollapsed=!opening;render();if(mobile&&opening)$('.panel').focus();else $('[data-action="toggle-panel"]')?.focus({preventScroll:true});return;}
 if(action==='close-panel'){panelOpen=false;if(innerWidth>=761)panelCollapsed=true;render();$('[data-action="toggle-panel"]')?.focus({preventScroll:true});return;}
 if(action.startsWith('resolution:')){resolution=Number(action.slice(11));render();return;}
 if(action.startsWith('recent:')){addRecent(action.slice(7));return;}
 if(action==='nc'){if(!needSingleBar())return;const b=selectedBar(),c=currentChord();beginEdit(b.id,c?.id);draft.value='N.C.';$('#score-edit').value='N.C.';commitDraft();return;}

 if(action.startsWith('chord-up:')){const b=selectedBar(),i=b.chords.findIndex(c=>c.id===Number(action.slice(9)));if(i<1)return;const before=clone(b.chords),a=b.chords[i-1],z=b.chords[i],first=a.start,last=z.start;for(const [c,start] of [[a,last],[z,first]]){const delta=start-c.start;c.start=start;(c.variantChords||[]).forEach(v=>v.start+=delta);(c.variantAttacks||[]).forEach(v=>v.start+=delta);}b.chords.splice(i-1,2,z,a);const valid=barMusicValid(b),after=clone(b.chords);b.chords=before;if(!valid)return fail('Omordningen skulle placera en variant utanför sitt grundackords spann.');mutate(()=>b.chords=after,'Ackordens ordning ändrades. Startpunkterna ligger kvar.');return;}
 if(action.startsWith('attack:')){if(!needSingleBar())return;const b=selectedBar(),start=Number(action.slice(7)),existing=b.attacks.find(a=>a.start===start);let next=existing?b.attacks.filter(a=>a!==existing):[...b.attacks,{start,duration:resolution}];if(!attacksValid(b,next))return fail('Anslaget överlappar ett annat anslag. Välj ett kortare notvärde först.');mutate(()=>b.attacks=next,existing?'Anslaget togs bort.':'Anslaget lades till.');return;}
 if(action==='house-remove'){if(!needBar())return;mutate(()=>visibleBars().filter(b=>b.houseSpan?.barIds.some(id=>selected.includes(id))).forEach(b=>b.houseSpan=null),'Hela huset togs bort.');return;}
 if(action.startsWith('repeat:')){if(!needBar())return;const type=action.slice(7);if(type==='both'&&!selectionContiguous())return fail('Markera sammanhängande takter för en repris runt markeringen.');mutate(()=>{if(type!=='end')barById(selected[0]).repeatStart=true;if(type!=='start')barById(selected.at(-1)).repeatEnd=true;},'Repristecknen visas i bladet.');return;}
 if(action.startsWith('block:')){const id=action.slice(6),block=model.form.find(f=>f.id===id),open=panelOpen;if(!block)return;if(block.reuse)handleContextAction('context-select-reuse:'+id);else selectPart(block.source);tab='form';selectedBlock=id;panelOpen=open;render();$('[data-score-block="'+id+'"]')?.scrollIntoView({block:'nearest'});return;}
 if(action==='reuse-remove'){const block=selectedForm();resetContext();if(!block?.reuse)return;mutate(()=>{model.form=model.form.filter(b=>b!==block);selectedBlock=sourceBlock(block).id;},'Återanvändningen togs bort.');return;}
 if(action.startsWith('move:')){const [,id,delta]=action.split(':');moveBlock(id,model.form.findIndex(b=>b.id===id)+Number(delta));return;}
 if(action.startsWith('goto-source:')){const id=action.slice(12);selectPart(id);$('#section-'+id)?.scrollIntoView({block:'start'});return;}
 if(action==='duplicate-bars'){if(needBar())duplicateBars([...selected]);return;}
 if(action.startsWith('break:')){if(!needBar())return;const b=selectedBar(),type=action.slice(6),active=type==='row'?b.rowBreak:type==='page'?b.pageBreak:false;mutate(()=>{b.rowBreak=type==='row'&&!active;b.pageBreak=type==='page'&&!active;},'Brytningen uppdaterades i bladet.');return;}
 if(action==='local-apply'){if(!needSingleBar())return;const b=selectedBar(),key=$('#local-key').value,meter=$('#local-meter').value,oldKey=b.key,oldMeter=b.meter;b.key=key;b.meter=meter;const invalid=model.sections.flatMap(s=>s.bars).some(bar=>!barMusicValid(bar));b.key=oldKey;b.meter=oldMeter;if(invalid)return fail('Taktarten skulle placera ackord eller anslag utanför takten. Flytta dem först.');mutate(()=>{b.key=key;b.meter=meter;},'Lokala byten visas i bladet.');return;}
 if(action==='song-apply'){const title=$('#song-title').value.trim(),artist=$('#song-artist').value.trim(),key=$('#song-key').value.trim(),tempo=Number($('#song-tempo').value),meter=$('#song-meter').value,status=$('#song-status').value,version=$('#song-version').value.trim();if(!title||!/^[A-G](?:#|b|♯|♭)?m?$/.test(key)||!Number.isFinite(tempo)||tempo<20||tempo>300)return fail('Ange titel, tonart och tempo mellan 20 och 300.');const old=model.meter;model.meter=meter;const invalid=visibleBars().some(b=>!barMusicValid(b));model.meter=old;if(invalid)return fail('Grundtaktarten skulle placera ackord eller anslag utanför en takt. Flytta dem först.');mutate(()=>Object.assign(model,{title,artist,key,tempo,meter,status,version}),'Låtuppgifterna uppdaterades.');return;}
});
document.addEventListener('focusout',e=>{if(e.target.id==='part-name'&&renameState){const pending=renameState;setTimeout(()=>{if(renameState===pending&&document.activeElement?.id!=='part-name')commitRename();},0);}if(['score-edit','variant-edit'].includes(e.target.id)&&draft){const pending=draft;setTimeout(()=>{if(draft===pending&&!['score-edit','variant-edit'].includes(document.activeElement?.id))commitDraft(false);},0);}});
document.addEventListener('input',e=>{
 if(e.target.id==='context-variant-pass'){updateVariantParams();return;}
 if(e.target.id==='part-name'&&renameState){renameState.value=e.target.value;renameState.error='';return;}
 if(e.target.id==='variant-edit'&&draft?.kind==='variant'){draft.value=e.target.value;updateVariantDraft();return;}
 if(e.target.id==='score-edit'&&draft){draft.value=e.target.value;draft.error='';delete draft.variantChanges;}
});
document.addEventListener('change',e=>{
 if(e.target.hasAttribute('data-bar-check')){toggleCheckedBar(Number(e.target.dataset.barCheck),e.target.checked);return;}
 if(e.target.id==='context-variant-following'){updateVariantParams();return;}
 if(e.target.hasAttribute('data-chord-grid')){if(draft&&!commitDraft(false))return;resolution=Number(e.target.value);render();return;}
 if(e.target.dataset.variantStart){setVariantStart(e.target.dataset.variantStart,e.target.value);return;}
 if(e.target.dataset.variantDuration){const b=singleBar(),c=variantOwner(),start=Number(e.target.dataset.variantDuration),duration=Number(e.target.value),next=c.variantAttacks.map(a=>a.start===start?{...a,duration}:a);if(!variantAttacksValid(b,c,next))return fail('Notvärdet går utanför variantens spann eller överlappar nästa anslag.');mutate(()=>c.variantAttacks=next,'Variantens notvärde ändrades.');return;}
 if(e.target.dataset.start){setChordStart(e.target.dataset.start,e.target.value);return;}
 if(e.target.dataset.duration){const b=selectedBar(),start=Number(e.target.dataset.duration),duration=Number(e.target.value),next=b.attacks.map(a=>a.start===start?{...a,duration}:a);if(!attacksValid(b,next))return fail('Notvärdet överlappar nästa anslag eller går förbi taktens slut.');mutate(()=>b.attacks=next,'Anslagets notvärde ändrades.');}
});
document.addEventListener('keydown',e=>{
 if(e.target.id==='part-name'){if(e.isComposing)return;if(e.key==='Enter'){e.preventDefault();commitRename();}if(e.key==='Escape'){e.preventDefault();renameState=null;render();}return;}
 if(e.target.id==='variant-edit'){if(e.isComposing)return;if(e.key==='Enter'){e.preventDefault();commitDraft();}if(e.key==='Escape'){e.preventDefault();cancelVariantDraft();}return;}
 if(['score-edit'].includes(e.target.id)){if(e.isComposing)return;if(e.key==='Enter'){e.preventDefault();commitDraft();}if(e.key==='Escape'){e.preventDefault();draft=null;panelOpen=false;message='Textändringen avbröts.';render();}return;}
 if(e.key==='Escape'&&pendingPart){e.preventDefault();pendingPart=null;render();return;}
 if(e.key==='Escape'&&contextView){e.preventDefault();handleContextAction('close-context');return;}
 if(e.key==='Escape'){resetContext();rangeAnchor=null;pendingHouse=null;if(panelOpen&&innerWidth<761){panelOpen=false;render();}else{selected=[];chordId=null;selectedPart=null;renameState=null;error='';render();}return;}
 if(e.target.matches('input,textarea,select'))return;
 if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();document.querySelector(`[data-action="${e.shiftKey?'redo':'undo'}"]`).click();return;}
 if(e.target.closest('button'))return;
 const variant=e.target.closest('[data-variant-chord]'),variantArea=e.target.closest('[data-variant-area]');if((variant||variantArea)&&(e.key==='Enter'||e.key===' ')){e.preventDefault();if(variant)selectVariant(Number(variant.closest('[data-bar]').dataset.bar),Number(variant.dataset.variantOwner),Number(variant.dataset.variantChord));else {if(selected[0]!==Number(variantArea.closest('[data-bar]').dataset.bar))selectBar(Number(variantArea.closest('[data-bar]').dataset.bar));beginVariantEdit(Number(variantArea.dataset.variantArea));}return;}
 const bar=e.target.closest('[data-bar]');if(bar&&(e.key==='Enter'||e.key===' ')){e.preventDefault();if(e.target.closest('[data-select-bar]'))selectBar(Number(bar.dataset.bar),e.shiftKey);else if(e.target.dataset.chord)selectChord(Number(bar.dataset.bar),Number(e.target.dataset.chord));else beginEdit(Number(bar.dataset.bar),null);}
});
let dragging='';document.addEventListener('dragstart',e=>{const block=e.target.closest('[data-block]');if(block){dragging=block.dataset.block;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',dragging);}});document.addEventListener('dragover',e=>{if(e.target.closest('[data-block]'))e.preventDefault();});document.addEventListener('drop',e=>{const block=e.target.closest('[data-block]');if(block&&dragging){e.preventDefault();moveBlock(dragging,model.form.findIndex(b=>b.id===block.dataset.block));dragging='';}});
window.hybrid={getState:()=>clone({model,selected,chordId,draft,tab,panelOpen,panelCollapsed,resolution,pastCount:past.length,futureCount:future.length,message,error,selectedVariantId,variantOwnerId,rangeAnchor,pendingHouse,pendingPart,selectedPart,renameState,contextView,selectedReuse}),select:(section,index)=>beginEdit(sectionById(section).bars[index].id,null),reset:()=>{model=initial();past=[];future=[];selected=[];chordId=null;resetContext();selectedPart=null;renameState=null;draft=null;rangeAnchor=null;pendingHouse=null;render();}};
render();

document.fonts.ready.then(positionChordTools);
let narrowLayout=innerWidth<761;
window.addEventListener('resize',()=>{const narrow=innerWidth<761;if(narrow!==narrowLayout){narrowLayout=narrow;render();return;}positionChordTools();const toggle=$('[data-action="toggle-panel"]');if(toggle){const label=innerWidth<761?(panelOpen?'Stäng menyn':'Öppna menyn'):(panelCollapsed?'Visa menykolumn':'Fäll in menykolumn');toggle.setAttribute('aria-label',label);toggle.dataset.tooltip=label;toggle.setAttribute('aria-expanded',String(innerWidth<761?panelOpen:!panelCollapsed));toggle.innerHTML=iconSVG(actionIcon('toggle-panel'));}});

document.addEventListener('cancel',e=>{if(e.target.id==='context-popup'){e.preventDefault();handleContextAction('close-context');}if(e.target.classList.contains('variant-choice-dialog')){e.preventDefault();if(draft)delete draft.variantChanges;render();focusDraft(false);}},true);
