import {chromium} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({executablePath:'/home/kevin/.cache/ms-playwright/chromium-1246/chrome-linux64/chrome',args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1512,height:1050}});
const url=new URL('prototype.html',import.meta.url).href;
const errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(url);
const state=()=>page.evaluate(()=>window.hybrid.getState());
const source=async(id='verse')=>(await state()).model.sections.find(s=>s.id===id);
const action=name=>page.locator(`button[data-action="${name}"]`).filter({visible:true}).first().click();
const tool=name=>page.locator(`.toolbar [data-action="tool:${name}"]`).click();
const assert=(condition,message)=>{if(!condition)throw Error(message);};
async function fresh(){await page.setViewportSize({width:1512,height:1050});await page.evaluate(()=>localStorage.removeItem('harmis-editor-preferences'));await page.reload();await page.evaluate(()=>document.fonts.ready);}
async function select(index=0,id='verse'){const b=(await source(id)).bars[index];await page.locator(`[data-select-bar="${b.id}"]`).click();return b;}
async function editBar(value,index=0,id='verse'){const b=(await source(id)).bars[index];await page.locator(`[data-chord-area="${b.id}"]`).click({position:{x:4,y:5}});await page.locator('#score-edit').fill(value);await page.locator('#score-edit').press('Enter');}
async function range(first,last){await select(first);await action('range-start');await select(last);}
async function house(first,last,number='1'){await range(first,last);await tool('repeats');await action('house:'+number);await action('house-apply');}
async function test(name,fn){try{await fresh();await fn();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:e.message});}}
await test('Measure-number strip selects without opening input',async()=>{const b=await select(0);const s=await state();assert(s.selected[0]===b.id&&!s.draft,'strip opens input');assert(await page.locator('.bar-actions').count()===1,'no selected-bar actions');});
await test('Chord click places caret, typing corrects without replacing full text',async()=>{const b=(await source()).bars[0];await page.locator(`[data-chord="${b.chords[0].id}"]`).dblclick({position:{x:12,y:10}});const caret=await page.locator('#score-edit').evaluate(i=>[i.selectionStart,i.selectionEnd]);assert(caret[0]===caret[1],'whole field selected by default');await page.locator('#score-edit').press('End');await page.locator('#score-edit').press('m');await page.locator('#score-edit').press('Enter');assert((await source()).bars[0].chords[0].name==='Dm','caret correction failed');});
await test('Select-all preference applies to opened field and persists reload',async()=>{await action('tab:settings');await page.locator('input[name="text-behavior"][value="select"]').check();await page.reload();const b=(await source()).bars[4];await page.locator(`[data-chord-area="${b.id}"]`).click({position:{x:4,y:5}});const selected=await page.locator('#score-edit').evaluate(i=>[i.selectionStart,i.selectionEnd,i.value.length]);assert(selected[0]===0&&selected[1]===selected[2]&&selected[2]>1,'preference not applied');});
await test('Second activation edits the complete measure and scope is visible',async()=>{const b=(await source()).bars[4];await page.locator(`[data-chord="${b.chords[0].id}"]`).dblclick();assert(!await page.locator('.chord-tools').count()&&(await page.locator('.editing-help').textContent()).includes('Hela takten'),'missing whole measure scope');await page.locator('#score-edit').fill('Dm F');await page.locator('#score-edit').press('Enter');assert((await source()).bars[4].chords.map(c=>c.name).join(' ')==='Dm F','neighbor lost');});
await test('Bar-local duplicate inserts copy after source and selects it',async()=>{const b=await select(4),before=(await source()).bars.length;await action('duplicate-bar:'+b.id);const bars=(await source()).bars;assert(bars.length===before+1&&bars[5].chords.map(c=>c.name).join(' ')==='D A/C#','wrong duplicate');assert(bars[5].id!==b.id&&bars[5].chords[0].id!==b.chords[0].id,'IDs reused');assert((await state()).selected[0]===bars[5].id&&!(await state()).draft,'selection enters editor');await action('undo');assert((await source()).bars.length===before,'duplicate undo failed');await action('redo');assert((await source()).bars.length===before+1,'duplicate redo failed');});
await test('Bar-local delete removes one bar and undo restores contents',async()=>{const before=await source(),b=await select(2);await action('delete-bar:'+b.id);assert((await source()).bars.length===7&&!(await source()).bars.some(x=>x.id===b.id),'delete failed');await action('undo');assert(JSON.stringify((await source()).bars)===JSON.stringify(before.bars),'delete undo loses contents');});
await test('Last remaining bar is emptied and part deletion remains separate',async()=>{for(let i=0;i<3;i++){const b=await select(0,'intro');await action('delete-bar:'+b.id);}await select(0,'intro');const last=(await source('intro')).bars[0];await action('delete-bar:'+last.id);assert((await source('intro')).bars.length===1&&!(await source('intro')).bars[0].chords.length,'last bar not emptied');});
await test('Deleting first or middle house bar keeps span contiguous and valid',async()=>{await house(2,4);const first=(await source()).bars[2].id;await select(2);await action('delete-bar:'+first);let bars=(await source()).bars;assert(bars[2].houseSpan?.length===2&&bars[2].houseSpan.barIds.every(id=>bars.some(b=>b.id===id)),'owner not transferred');const middle=bars[3].id;await select(3);await action('delete-bar:'+middle);bars=(await source()).bars;assert(bars[2].houseSpan?.length===1,'span did not shrink');});
await test('Deleting a local meter change preserves successor meter and attacks',async()=>{await select(0);await tool('insert');await page.locator('#local-meter').selectOption('6/8');await action('local-apply');await select(1);await tool('rhythm');await action('resolution:16');await action('attack:6.5');const b=(await source()).bars[0];await select(0);await action('delete-bar:'+b.id);assert((await source()).bars[0].meter==='6/8'&&(await source()).bars[0].attacks[0].start===6.5,'meter lost after deletion');});
await test('Duplicate copies music and omits repeat/layout boundaries',async()=>{const b=await select(0);await tool('repeats');await action('repeat:end');await tool('layout');await action('break:page');await action('duplicate-bar:'+b.id);const copy=(await source()).bars[1];assert(copy.chords[0].name==='D'&&!copy.repeatEnd&&!copy.pageBreak&&!copy.rowBreak&&!copy.houseSpan,'duplicate adds structural boundaries');});
await test('Changed base chord asks before retaining/removing variant',async()=>{const b=await select(0);await tool('chord');await page.locator('#variant').fill('Dm');await page.locator(`[data-chord="${b.chords[0].id}"]`).dblclick();await page.locator('#score-edit').fill('A');await page.locator('#score-edit').press('Enter');assert((await source()).bars[0].chords[0].name==='D'&&await page.locator('.variant-review').count()===1,'variant silently follows renamed chord');await action('variant-choice:remove');const c=(await source()).bars[0].chords[0];assert(c.name==='A'&&!c.variant,'variant removal failed');await action('undo');assert((await source()).bars[0].chords[0].variant==='Dm','undo lost variant');});
await test('Explicitly keeping variant and moving chord preserves its metadata',async()=>{await editBar('D A');await select(0);await tool('chord');await page.locator('#variant').fill('Dm');const b=(await source()).bars[0];await page.locator(`[data-chord="${b.chords[0].id}"]`).dblclick();await page.locator('#score-edit').fill('G A');await page.locator('#score-edit').press('Enter');await action('variant-choice:keep');await tool('chord');const second=(await source()).bars[0].chords[1];await action('chord-up:'+second.id);const moved=(await source()).bars[0].chords[1];assert(moved.name==='G'&&moved.variant==='Dm'&&moved.start===3,'variant not moving with chord');});
await test('New three/four chords use accepted standard positions',async()=>{await editBar('C D E');assert((await source()).bars[0].chords.map(c=>c.start).join(',')==='1,2,3','three positions wrong');await editBar('C D E F');assert((await source()).bars[0].chords.map(c=>c.start).join(',')==='1,2,3,4','four positions wrong');});
await test('Partial house overlap offers explicit replacement without early changes',async()=>{await house(2,4);await range(3,5);await tool('repeats');await action('house:2');await action('house-apply');assert((await state()).pendingHouse&&((await source()).bars[2].houseSpan.number==='1'),'old house changed before choice');await action('house-replace');const bars=(await source()).bars;assert(!bars[2].houseSpan&&bars[3].houseSpan.number==='2'&&bars[3].houseSpan.length===3,'replacement inconsistent');await action('undo');assert((await source()).bars[2].houseSpan.number==='1','house replacement undo failed');});
await test('Declining conflicting house preserves old house',async()=>{await house(2,4);await range(3,5);await tool('repeats');await action('house:2');await action('house-apply');await action('house-cancel');assert(!(await state()).pendingHouse&&(await source()).bars[2].houseSpan.number==='1','cancel changed house');});
await test('Reuse moves before original and keeps source meter',async()=>{await select(0);await tool('insert');await page.locator('#local-meter').selectOption('6/8');await action('local-apply');await action('tab:form');await action('block:f2');await action('reuse');const id=(await state()).model.form.at(-1).id;await action('move:'+id+':-1');await action('move:'+id+':-1');await action('move:'+id+':-1');const s=await state();assert(s.model.form[0].id===id&&!s.error,'before-original move blocked');assert(s.model.sections.find(x=>x.id==='verse').entryMeter==='6/8','source meter not anchored');});
await test('Detach preserves count/instruction, remaps houses and separates edits',async()=>{await house(2,4);await action('tab:form');await action('block:f2');await action('reuse');await page.locator('#reuse-count').fill('2');await page.locator('#reuse-instruction').fill('Sista refrängen');await action('reuse-apply');const original=await source();await action('detach-reuse');const s=await state(),block=s.model.form.at(-1),copy=s.model.sections.find(x=>x.id===block.source);assert(!block.reuse&&block.count===2&&block.instruction==='Sista refrängen'&&copy.id!==original.id,'detach loses occurrence settings');const span=copy.bars[2].houseSpan;assert(span.barIds.every(id=>copy.bars.some(b=>b.id===id))&&!span.barIds.some(id=>original.bars.some(b=>b.id===id)),'house IDs still linked');await editBar('F',0,copy.id);assert((await source()).bars[0].chords[0].name==='D'&&(await source(copy.id)).bars[0].chords[0].name==='F','copy edits source');await action('undo');await action('undo');assert((await state()).model.form.at(-1).reuse,'detach undo failed');});
await test('Detached 6/8 part before original keeps sixteenth placement',async()=>{await select(0);await tool('insert');await page.locator('#local-meter').selectOption('6/8');await action('local-apply');await select(1);await tool('rhythm');await action('resolution:16');await action('attack:6.5');await action('tab:form');await action('block:f2');await action('reuse');const id=(await state()).model.form.at(-1).id;for(let i=0;i<3;i++)await action('move:'+id+':-1');await action('detach-reuse');const s=await state(),copy=s.model.sections.find(x=>x.id===s.model.form[0].source);assert(copy.bars[0].meter==='6/8'&&copy.bars[1].attacks[0].start===6.5&&!s.error,'detach corrupted timing');});
await test('Mobile two-tap range selects without keyboard or popup',async()=>{await page.setViewportSize({width:430,height:760});const first=await select(2);await action('range-start');assert(await page.locator('.bar-actions').count()===0,'destructive actions remain in range-picking mode');const last=await select(4);const s=await state();assert(s.selected.length===3&&s.selected[0]===first.id&&s.selected.at(-1)===last.id&&!s.draft&&!s.panelOpen,'mobile range not selected');await page.locator('.toolbar [data-action="tab:music"]').click();await action('tool:repeats');await action('house:1');await action('house-apply');assert((await source()).bars[2].houseSpan.length===3,'mobile house does not use range');});
await test('Range selection rejects crossing parts and can be cancelled',async()=>{await select(0);await action('range-start');await select(2,'intro');assert((await state()).rangeAnchor!==null&&(await state()).selected.length===1,'cross-part range applied');await action('range-cancel');assert((await state()).rangeAnchor===null,'range cancel failed');});
await test('Mobile settings and local bar actions have no horizontal overflow',async()=>{await page.setViewportSize({width:375,height:580});const b=await select(3,'intro');await page.waitForTimeout(220);assert(await page.evaluate(()=>document.documentElement.scrollWidth)<=375,'selection overflow');const r=await page.locator('.bar-actions').boundingBox();assert(r.x>=0&&r.x+r.width<=375,'local buttons outside viewport');await action('tab:settings');await page.waitForTimeout(220);const box=await page.locator('.panel').boundingBox();assert(box.y>=0&&box.y+box.height<=580,'settings popup outside viewport');await page.locator('input[name="text-behavior"][value="select"]').check();assert((await state()).preferences.selectAll,'mobile settings failed');});
await test('Keyboard activates local delete as a button without opening editor',async()=>{const b=await select(2);await page.locator('[data-action="delete-bar:'+b.id+'"]').focus();await page.locator('[data-action="delete-bar:'+b.id+'"]').press('Enter');assert((await source()).bars.length===7&&!(await state()).draft,'Enter starts chord editor instead of deleting');});
await test('Deleting meter change at end of part preserves following part',async()=>{await select(7);await tool('insert');await page.locator('#local-meter').selectOption('6/8');await action('local-apply');await select(0,'chorus');await tool('rhythm');await action('resolution:16');await action('attack:6.5');const b=await select(7);await action('delete-bar:'+b.id);const chorus=await source('chorus');assert(chorus.bars[0].meter==='6/8'&&chorus.bars[0].attacks[0].start===6.5,'following source timing invalidated');});
await writeFile(new URL('revision-verification.json',import.meta.url),JSON.stringify({errors,results},null,2)+'\n');
console.log(JSON.stringify({errors,results},null,2));await browser.close();if(errors.length||results.some(r=>!r.passed))process.exitCode=1;
