'use client';
import { forwardRef, useEffect, useImperativeHandle, useLayoutEffect, useRef, useState, type ReactNode } from 'react';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Check, Copy, Eraser, FilePlus2, Flag, GitBranch, ListMusic, Music2, Parentheses, Pencil, Plus, Repeat2, Settings2, Trash2, X, CornerDownLeft, FileDown, Hash, Type, Unlink, Eye, CirclePause, CircleStop } from 'lucide-react';
import { asBar, readSong, type Song, type RhythmNote } from '@/lib/song';
import { insertFeature, renameSection, inlineLegacyForm, type EditAction } from '@/lib/edit';
import { addVariant, barCursor, bounds, clearHouse, houseSpans, copySection, deleteBars, deleteChord, duplicateBars, insertBar, insertChord, moveChord, moveSection, normalizeChordLine, reorderChord, patchBar, patchSection, patchSong, removeSection, removeVariant, reuseSection, setChordLine, setHouse, startsFor, tokens, VariantChoiceError, type ScoreTarget } from '@/lib/score-edit';

type Selection = {kind:'bar';section:number;bars:number[];chord?:number;variant?:number;page?:number} | {kind:'section'|'reuse';section:number;page?:number};
type Draft = {kind:'chords'|'variant'|'name';target:ScoreTarget;value:string;originalText:string;baseText:string;group:string;error:string;caret?:number};
type Box={left:number;top:number;width:number;height:number;scale:number};
type Geometry={viewport?:{left:number;width:number};bar?:Box;area?:Box;part?:Box;chord?:Box;bounds?:Box;checks:{target:ScoreTarget;number:number;page:number;box:Box}[]};
export type ScoreEditorHandle={flush:()=>string|null;clear:()=>void;showPanel:(panel:'form'|'song')=>void;togglePanel:()=>void;rollback:()=>void};
type Props={text:string;song?:Song;pages:string[];printPages:string[];printPreview:boolean;previewText:string;busy:boolean;enabled:boolean;zoom:string;twoPages:boolean;onEdit:(text:string,group?:string)=>void;onRollback:(text:string,group:string)=>void;onCursor:(position:number)=>void;onDraftChange:(dirty:boolean)=>void;onNotice:(text:string)=>void;onPanelChange:(open:boolean)=>void;extraSongPanel?:ReactNode};
export function ScoreButton({label,children,onClick,disabled,active,className=''}:{label:string;children:ReactNode;onClick:()=>void;disabled?:boolean;active?:boolean;className?:string}) {return <button type="button" className={`score-icon ${active?'active':''} ${className}`} aria-label={label} aria-pressed={active} title={label} data-tooltip={label} disabled={disabled} onClick={onClick}>{children}</button>;}
const scalarStyle=(box:Box)=>({left:box.left,top:box.top,width:box.width,height:box.height});
export const ScoreEditor=forwardRef<ScoreEditorHandle,Props>(function ScoreEditor({text,song,pages,printPages,printPreview,previewText,busy,enabled,zoom,twoPages,onEdit,onRollback,onCursor,onDraftChange,onNotice,onPanelChange,extraSongPanel},ref){
  const [storedSelection,setSelection]=useState<Selection|null>(null),[draft,setDraft]=useState<Draft|null>(null),[context,setContext]=useState(''),[error,setError]=useState('');
  const selection=(()=>{const s=storedSelection,part=s&&song?.delar[s.section];if(!s||!part)return null;if(s.kind==='reuse'&&!part.ateranvand||s.kind==='section'&&part.ateranvand)return null;if(s.kind==='bar'){if(part.ateranvand||s.bars.some(n=>!Number.isInteger(n)||n<0||n>=part.takter.length))return null;const bar=asBar(part.takter[s.bars[0]]),fields=s.variant===undefined?bar:bar.varianter?.[s.variant];if(!fields||s.chord!==undefined&&s.chord>=tokens(fields.ackord).length)return null;}return s;})();
  const [panel,setPanel]=useState<'form'|'song'>('form'),[panelOpen,setPanelOpen]=useState(true),[resolution,setResolution]=useState(4),[recent,setRecent]=useState<string[]>([]),[geometry,setGeometry]=useState<Geometry>({checks:[]});
  const [dockPlacement,setDockPlacement]=useState<'top'|'bottom'>('bottom');
  const dockAnchor=useRef('');
  const [fastOverlay,setFastOverlay]=useState(false),[hovered,setHovered]=useState<{section:number;bar:number;page:number}|null>(null);
  const [confirmVariant,setConfirmVariant]=useState(false),[small,setSmall]=useState(false);
  const workspace=useRef<HTMLDivElement>(null),paramCommit=useRef(false),paramInvalid=useRef(false),fieldErrors=useRef(new Map<string,{input:HTMLInputElement;message:string}>()),fieldFailure=useRef<string|null>(null);
  const stack=useRef<HTMLDivElement>(null),input=useRef<HTMLInputElement>(null),popup=useRef<HTMLDialogElement>(null),variantDialog=useRef<HTMLDialogElement>(null),draftRef=useRef<Draft|null>(null),latest=useRef(text),ownChange=useRef<string|null>(null),seq=useRef(0),dragSource=useRef<string|null>(null);
  latest.current=text;
  const updateDraft=(d:Draft|null)=>{draftRef.current=d;setDraft(d);onDraftChange(!!d&&d.value!==initialDraftValue(d));};
  const initialDraftValue=(d:Draft)=>{try{const s=readSong(d.baseText);return d.kind==='name'?s.delar[d.target.section].namn:d.target.variant===undefined?asBar(s.delar[d.target.section].takter[d.target.bar]).ackord:asBar(s.delar[d.target.section].takter[d.target.bar]).varianter![d.target.variant].ackord;}catch{return '';}};
  const change=(next:string,group?:string)=>{ownChange.current=next;latest.current=next;onEdit(next,group);};
  const fail=(e:unknown)=>{const message=e instanceof Error?e.message:'Ändringen kunde inte göras.';if(paramCommit.current)fieldFailure.current=message;setError(message);};
  const flush=(choice?:'keep'|'remove'):string|null=>{const d=draftRef.current;if(!d)return latest.current;
    try{const next=d.kind==='name'?renameSection(latest.current,d.target.section,d.value):setChordLine(d.kind==='variant'?d.baseText:latest.current,d.target,d.value,choice);setFastOverlay(true);change(next,d.group);setRecent(old=>[...new Set([...tokens(normalizeChordLine(d.kind==='name'?'':d.value)),...old])].slice(0,8));updateDraft(null);if(d.kind==='variant')setSelection({kind:'bar',section:d.target.section,bars:[d.target.bar],variant:d.target.variant,chord:tokens(normalizeChordLine(d.value)).length?0:undefined});setConfirmVariant(false);setError('');return next;}
    catch(e){if(e instanceof VariantChoiceError)setConfirmVariant(true);else {updateDraft({...d,error:e instanceof Error?e.message:'Kontrollera ackorden.'});input.current?.focus({preventScroll:true});}return null;}
  };
  const rollback=()=>{const d=draftRef.current;if(!d)return;ownChange.current=d.originalText;latest.current=d.originalText;onRollback(d.originalText,d.group);updateDraft(null);setConfirmVariant(false);setContext('');setError('');};
  const clear=()=>{fieldErrors.current.clear();paramInvalid.current=false;updateDraft(null);setSelection(null);setContext('');setError('');setConfirmVariant(false);};
  const fieldKey=(input:HTMLInputElement)=>input.getAttribute('aria-label')??input.name??input.id;
  const callerFlush=()=>{const active=document.activeElement;if(active instanceof HTMLInputElement&&workspace.current?.contains(active)&&active.closest('.score-field,.score-beat-row'))active.blur();for(const [key,value] of fieldErrors.current)if(!value.input.isConnected)fieldErrors.current.delete(key);paramInvalid.current=fieldErrors.current.size>0;const invalid=fieldErrors.current.values().next().value;if(invalid){setError(invalid.message);if(invalid.input.closest('.score-side-panel')){setPanel('song');setPanelOpen(true);}requestAnimationFrame(()=>invalid.input.focus({preventScroll:false}));return null;}return flush();};
  const fieldCommit=(input:HTMLInputElement,fn:()=>void)=>{paramCommit.current=true;fieldFailure.current=null;fn();paramCommit.current=false;const key=fieldKey(input);if(fieldFailure.current){fieldErrors.current.set(key,{input,message:fieldFailure.current});input.setAttribute('aria-invalid','true');}else{fieldErrors.current.delete(key);input.removeAttribute('aria-invalid');}paramInvalid.current=fieldErrors.current.size>0;const remaining=fieldErrors.current.values().next().value;if(remaining)setError(remaining.message);onDraftChange(paramInvalid.current||!!draftRef.current&&draftRef.current.value!==initialDraftValue(draftRef.current));};
  useImperativeHandle(ref,()=>({flush:callerFlush,clear,rollback,showPanel:p=>{if(flush()===null)return;setPanel(p);setPanelOpen(true);},togglePanel:()=>{if(flush()===null)return;setPanelOpen(v=>!v);}}));
  useEffect(()=>onPanelChange(panelOpen),[panelOpen,onPanelChange]);
  useEffect(()=>{const media=matchMedia('(max-width:760px)'),sync=()=>{setSmall(media.matches);if(media.matches)setPanelOpen(false);};sync();media.addEventListener('change',sync);return()=>media.removeEventListener('change',sync);},[]);
  useEffect(()=>{if(ownChange.current===text){ownChange.current=null;return;}if(draftRef.current){updateDraft(null);}setSelection(null);setContext('');setError('');setFastOverlay(false);},[text]); // External text/history edits cannot keep an index pointing at different music.
  const draftAnchor=!!(draft?.kind==='name'?geometry.part:geometry.area);
  useEffect(()=>{const el=input.current;if(draft&&el&&document.activeElement!==el){el.focus({preventScroll:true});el.setSelectionRange(draft.caret??el.value.length,draft.caret??el.value.length);el.scrollIntoView({block:'nearest',inline:'nearest'});}},[draft?.kind,draft?.target.section,draft?.target.bar,draft?.target.variant,draftAnchor]);
  useEffect(()=>{if(small&&context&&popup.current&&!popup.current.open)popup.current.showModal();},[small,context]);
  useEffect(()=>{const escape=(e:KeyboardEvent)=>{if(e.key!=='Escape'||e.defaultPrevented||document.querySelector('.live-view,.setlist-dialog[open],.help-dialog'))return;if(e.target instanceof Element&&e.target.closest('.score-param-dialog,.variant-confirm'))return;if(draftRef.current){e.preventDefault();rollback();}else if(context){e.preventDefault();setContext('');}else if(storedSelection){e.preventDefault();setSelection(null);}else if(small&&panelOpen){e.preventDefault();setPanelOpen(false);}};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[context,storedSelection,small,panelOpen]);
  useEffect(()=>{if(confirmVariant)variantDialog.current?.showModal();},[confirmVariant]);
  useLayoutEffect(()=>{
    const root=stack.current;if(!root)return;const scroller=root.closest<HTMLElement>('.paper-scroll');
    const calculate=()=>{const parent=root.getBoundingClientRect(),box=(el:Element):Box=>{const r=el.getBoundingClientRect(),svg=el.closest('svg')!;return {left:r.left-parent.left,top:r.top-parent.top,width:r.width,height:r.height,scale:svg.getBoundingClientRect().width/595.2756};};
      const pick=(selector:string)=>{const list=[...root.querySelectorAll(selector)];return list.find(el=>Number(el.closest<HTMLElement>('.paper')?.dataset.page)===selection?.page)||list[0];};
      const match=selection?.kind==='bar'?`[data-section="${selection.section}"][data-bar="${selection.bars.at(-1)}"]`:'';
      const b=match?pick('.bar-hit'+match):undefined,area=match?pick((draft?.target.variant!==undefined?'.variant-area-hit'+match+`[data-variant="${draft.target.variant}"]`:'.chord-area-hit'+match)):undefined;
      const part=selection&&selection.kind!=='bar'?pick((selection.kind==='reuse'?'.reuse-hit':'.section-hit')+`[data-section="${selection.section}"]`):undefined;
      const chord=selection?.kind==='bar'&&selection.chord!==undefined?pick('.chord-hit'+match+`[data-chord="${selection.chord}"]`+(selection.variant===undefined?':not([data-variant])':`[data-variant="${selection.variant}"]`)):undefined;
      const checks=enabled&&!draft&&selection?.kind!=='section'&&selection?.kind!=='reuse'?[...root.querySelectorAll<SVGElement>('.bar-number-hit')].filter(el=>!selection||Number(el.dataset.section)===selection.section).map(el=>({target:{section:Number(el.dataset.section),bar:Number(el.dataset.bar)},number:Number(el.dataset.number),page:Number(el.closest<HTMLElement>('.paper')?.dataset.page),box:box(el)})):[];
      const svg=(b??part)?.closest('svg'),r=svg?box(svg):undefined;const range=r?{...r,left:r.left+31*r.scale,width:r.width-62*r.scale}:undefined;
      const dockTarget=chord??b??part;
      if(selection&&scroller&&dockTarget){const key=`${selection.kind}-${selection.section}-${selection.kind==='bar'?selection.bars.at(-1):''}-${selection.page??''}-${scroller.clientWidth}-${scroller.clientHeight}`;if(dockAnchor.current!==key){dockAnchor.current=key;const target=dockTarget.getBoundingClientRect(),view=scroller.getBoundingClientRect();setDockPlacement(target.top+target.height/2>view.top+view.height/2?'top':'bottom');}}else if(!selection)dockAnchor.current='';
      requestAnimationFrame(()=>workspace.current?.querySelectorAll<HTMLElement>('.score-action-strip').forEach(el=>el.closest('.score-action-card')?.classList.toggle('can-scroll',el.scrollWidth>el.clientWidth+1)));
      setGeometry({viewport:scroller?{left:scroller.getBoundingClientRect().left-parent.left,width:scroller.clientWidth}:undefined,bar:b?box(b):undefined,area:area?box(area):undefined,part:part?box(part):undefined,chord:chord?box(chord):undefined,bounds:range,checks});
      root.querySelectorAll('.score-selected-hit,.score-selected-bar').forEach(el=>el.classList.remove('score-selected-hit','score-selected-bar'));if(enabled&&chord)chord.classList.add('score-selected-hit');if(enabled&&selection?.kind==='bar')selection.bars.forEach(bar=>root.querySelectorAll(`.bar-hit[data-section="${selection.section}"][data-bar="${bar}"]`).forEach(el=>el.classList.add('score-selected-bar')));
    };calculate();const observer=new ResizeObserver(calculate);observer.observe(root);scroller?.addEventListener('scroll',calculate,{passive:true});return()=>{observer.disconnect();scroller?.removeEventListener('scroll',calculate);};
  },[pages,selection,draft?.kind,draft?.target.variant,zoom,twoPages,enabled]);
  const run=(fn:(source:string)=>string,nextSelection?:Selection|null,notice='Ändringen är gjord. Spara för att behålla den.')=>{const source=flush();if(source===null||busy)return;try{setFastOverlay(nextSelection===undefined);change(fn(source));if(nextSelection!==undefined)setSelection(nextSelection);setError('');onNotice(notice);}catch(e){fail(e);}};
  const barTarget=selection?.kind==='bar'?{section:selection.section,bar:selection.bars[0],...(selection.variant===undefined?{}:{variant:selection.variant})}:null;
  const activeBar=song&&barTarget?asBar(song.delar[barTarget.section]?.takter[barTarget.bar]??''):null;
  const activeFields=barTarget?.variant===undefined?activeBar:activeBar?.varianter?.[barTarget.variant];
  const activeTokens=tokens(activeFields?.ackord??''),chosen=selection?.kind==='bar'?selection.chord:undefined;
  const single=selection?.kind==='bar'&&selection.bars.length===1,contiguous=selection?.kind==='bar'&&selection.bars.every((n,i)=>!i||n===selection.bars[i-1]+1);
  const begin=(t:ScoreTarget,kind:'chords'|'variant'|'name'='chords',originalText?:string,group?:string,baseText?:string,caret?:number)=>{
    const source=flush();if(source===null)return;try{const s=readSong(baseText??source),value=kind==='name'?s.delar[t.section].namn:t.variant===undefined?asBar(s.delar[t.section].takter[t.bar]).ackord:asBar(s.delar[t.section].takter[t.bar]).varianter![t.variant].ackord;setContext('');setError('');if(kind!=='name')setSelection({kind:'bar',section:t.section,bars:[t.bar],variant:t.variant});updateDraft({kind,target:t,value,originalText:originalText??source,baseText:baseText??source,group:group??'score-'+(++seq.current),error:'',caret});}catch(e){fail(e);}
  };
  const hit=(el:Element,keyboard=false,touch=false)=>{
    if(!enabled||previewText!==latest.current||busy||!song)return;
    let target=el.closest<SVGElement>('.chord-hit,.bar-number-hit,.chord-area-hit,.variant-area-hit,.reuse-hit,.section-hit,.bar-hit');if(!target)return;if(target.classList.contains('section-hit')){const point=target.getBoundingClientRect(),reuse=[...target.closest('svg')!.querySelectorAll<SVGElement>('.reuse-hit')].find(el=>{const r=el.getBoundingClientRect();return point.left>=r.left&&point.right<=r.right&&point.top>=r.top&&point.bottom<=r.bottom;});if(reuse)target=reuse;}const s=Number(target.dataset.section),b=Number(target.dataset.bar),v=target.dataset.variant===undefined?undefined:Number(target.dataset.variant),c=target.dataset.chord===undefined?undefined:Number(target.dataset.chord),page=Number(target.closest<HTMLElement>('.paper')?.dataset.page);
    if(flush()===null)return;setContext('');setError('');
    // A source-title hit inside a reused block selects the occurrence first.
    const reused=song.delar[s]?.ateranvand;const reuseTarget=target.classList.contains('reuse-hit')||!!reused;
    if(reuseTarget){setSelection({kind:'reuse',section:s,page});return;}
    if(target.classList.contains('section-hit')){setSelection({kind:'section',section:s,page});return;}
    onCursor(barCursor(latest.current,{section:s,bar:b}));
    if(c!==undefined){if(selection?.kind==='bar'&&selection.section===s&&selection.bars.length===1&&selection.bars[0]===b&&selection.chord===c&&selection.variant===v){const field=v===undefined?asBar(song.delar[s].takter[b]):asBar(song.delar[s].takter[b]).varianter![v],words=tokens(field.ackord),prefix=words.slice(0,c).join(' '),caret=prefix.length+(c?1:0)+words[c].length;begin({section:s,bar:b,variant:v},v===undefined?'chords':'variant',undefined,undefined,undefined,caret);return;}setSelection({kind:'bar',section:s,bars:[b],chord:c,variant:v,page});if(keyboard)requestAnimationFrame(()=>document.querySelector('.chord-actions')?.scrollIntoView({block:'nearest'}));return;}
    if(target.classList.contains('variant-area-hit')){begin({section:s,bar:b,variant:v},'variant');return;}
    if(target.classList.contains('chord-area-hit')){begin({section:s,bar:b});return;}
    if(target.classList.contains('bar-hit')&&!asBar(song.delar[s].takter[b]).ackord){begin({section:s,bar:b});return;}
    if(touch&&target.classList.contains('bar-number-hit')&&selection?.kind==='bar'&&selection.section===s&&selection.chord===undefined){checkbox({section:s,bar:b},!selection.bars.includes(b));return;}
    setSelection({kind:'bar',section:s,bars:[b],page});
  };
  const checkbox=(t:ScoreTarget,on:boolean)=>{if(previewText!==text||busy||flush()===null)return;setContext('');setSelection(old=>{const bars=old?.kind==='bar'&&old.section===t.section?[...old.bars]:[];const next=on?[...new Set([...bars,t.bar])].sort((a,b)=>a-b):bars.filter(n=>n!==t.bar);return next.length?{kind:'bar',section:t.section,bars:next}:null;});onCursor(barCursor(text,t));};
  const openContext=(view:string)=>{if(flush()===null)return;setError('');setContext(old=>old===view?'':view);};
  const createVariant=()=>{if(!barTarget)return;const source=flush();if(source===null)return;try{const existing=activeBar?.varianter?.findIndex(v=>v.ackord_nr===(chosen??0)+1);if(existing!==undefined&&existing>=0){begin({...barTarget,variant:existing},'variant');return;}const group='score-'+(++seq.current),result=addVariant(source,{section:barTarget.section,bar:barTarget.bar},(chosen??0)+1);change(result.text,group);begin({...barTarget,variant:result.variant},'variant',source,group,result.text);}catch(e){fail(e);}};
  const feature=(action:EditAction)=>{if(!barTarget)return;run(source=>insertFeature(source,barCursor(source,barTarget),action).text);};
  const patch=(fields:Record<string,unknown>,variant=barTarget?.variant)=>{if(!barTarget)return;run(source=>patchBar(source,{...barTarget,variant},fields));};
  const nextPosition=(direction:number)=>{if(!song||!barTarget||chosen===undefined)return;const bs=bounds(song,barTarget),starts=startsFor(song,barTarget),grid=Array.from({length:Math.ceil((bs.end-bs.start)*resolution/bs.denominator)},(_,i)=>bs.start+i*bs.denominator/resolution);return direction<0?grid.filter(n=>n<starts[chosen]&&n>(starts[chosen-1]??bs.start-.01)).at(-1):grid.find(n=>n>starts[chosen]&&n<(starts[chosen+1]??bs.end));};
  const step=(direction:number)=>{const start=nextPosition(direction);if(start!==undefined&&barTarget&&chosen!==undefined)run(source=>moveChord(source,barTarget,chosen,start));};
  const proposeLine=(value:string)=>{if(!barTarget)return;const source=flush();if(source===null||busy)return;try{setFastOverlay(true);change(setChordLine(source,barTarget,value));setError('');}catch(e){if(e instanceof VariantChoiceError){begin(barTarget,barTarget.variant===undefined?'chords':'variant');const d=draftRef.current;if(d){updateDraft({...d,value,error:''});setConfirmVariant(true);}}else fail(e);}};
  const editOne=(value:string|null)=>{if(!barTarget||chosen===undefined)return;if(value===null){const owned=barTarget.variant===undefined&&activeBar?.varianter?.some(v=>v.ackord_nr===chosen+1);if(owned&&!window.confirm('Ta bort ackordet och dess variantrader?'))return;run(source=>deleteChord(source,barTarget,chosen),{kind:'bar',section:barTarget.section,bars:[barTarget.bar],variant:barTarget.variant,chord:activeTokens.length>1?Math.min(chosen,activeTokens.length-2):undefined});return;}const list=[...activeTokens];list[chosen]=value;proposeLine(list.join(' '));};
  const addRecent=(value:string)=>{if(!barTarget)return;const source=flush();if(source===null||busy)return;try{const result=insertChord(source,barTarget,chosen,value,resolution);change(result.text);setSelection({kind:'bar',section:barTarget.section,bars:[barTarget.bar],variant:barTarget.variant,chord:result.chord});setFastOverlay(true);setError('');onNotice(`${value} lades till på slag ${result.start}.`);}catch(e){fail(e);}};
  const addBlank=()=>{if(selection?.kind!=='bar')return;const source=flush();if(source===null||busy)return;try{const bar=selection.bars.at(-1)!+1,next=insertBar(source,selection.section,bar-1);change(next);begin({section:selection.section,bar},'chords',next,undefined,next);}catch(e){fail(e);}};
  const applyHouse=(number:string)=>{if(selection?.kind!=='bar'||!song)return;const previous=houseSpans(song,selection.section).filter(v=>selection.bars.some(n=>n>=v.start&&n<=v.end));if(previous.some(v=>v.start!==selection.bars[0]||v.end!==selection.bars.at(-1))&&!window.confirm('Huset överlappar ett befintligt hus. Ersätt hela det befintliga huset?'))return;run(s=>setHouse(s,selection.section,selection.bars,number));};
  const barActions=selection?.kind==='bar'?<div className="score-action-card measure-actions" role="group" aria-label="Taktverktyg"><div className="score-scope">{song?.delar[selection.section].namn} · {selection.bars.length===1?'takt '+(geometry.checks.find(c=>c.target.bar===selection.bars[0])?.number??selection.bars[0]+1):selection.bars.length+' valda takter'}<span className="action-scroll-hint">↔ {small?'Svep':'Rulla'}</span></div><div className="score-action-strip">
    <ScoreButton label="Ny tom takt efter markeringen" onClick={addBlank}><Plus/></ScoreButton>
    <ScoreButton label={single?'Duplicera takten':'Duplicera valda takter'} onClick={()=>run(s=>duplicateBars(s,selection.section,selection.bars),{kind:'bar',section:selection.section,bars:selection.bars.map((_,i)=>selection.bars.at(-1)!+1+i)})}><Copy/></ScoreButton>
    <ScoreButton label={single?'Ta bort takten':'Ta bort valda takter'} onClick={()=>{if(single||window.confirm(`Ta bort ${selection.bars.length} valda takter?`))run(s=>deleteBars(s,selection.section,selection.bars),null);}}><X/></ScoreButton>
    <ScoreButton label="Töm ackordraden" onClick={()=>run(s=>selection.bars.reduce((value,bar)=>setChordLine(value,{section:selection.section,bar},'','remove'),s))}><Eraser/></ScoreButton><ScoreButton label="Upprepa takt" disabled={!single} onClick={()=>{feature('repeat_bar');setSelection({kind:'bar',section:selection.section,bars:selection.bars});}}><span className="music-icon">%</span></ScoreButton><span className="score-divider"/>
    <ScoreButton label="Rytm" disabled={!single} active={context==='rhythm'} onClick={()=>openContext('rhythm')}><Music2/></ScoreButton>
    <ScoreButton label="Tonart och taktart" disabled={!single} active={context==='changes'} onClick={()=>openContext('changes')}><Settings2/></ScoreButton><span className="score-divider"/>
    <ScoreButton label="Repris runt markeringen" disabled={!contiguous} onClick={()=>run(s=>patchBar(patchBar(s,{section:selection.section,bar:selection.bars[0]},{repris_start:true}),{section:selection.section,bar:selection.bars.at(-1)!},{repris_slut:true}))}><Repeat2/></ScoreButton>
    <ScoreButton label={activeBar?.repris_start?'Ta bort reprisstart':'Reprisstart'} onClick={()=>run(s=>patchBar(s,{section:selection.section,bar:selection.bars[0]},{repris_start:activeBar?.repris_start?undefined:true}))}><span className="music-icon">‖:</span></ScoreButton>
    <ScoreButton label={activeBar?.repris_slut?'Ta bort reprisslut':'Reprisslut'} onClick={()=>run(s=>patchBar(s,{section:selection.section,bar:selection.bars.at(-1)!},{repris_slut:activeBar?.repris_slut?undefined:true}))}><span className="music-icon">:‖</span></ScoreButton>
    {[1,2].map(n=><ScoreButton key={n} label={n===1?'Första hus':'Andra hus'} disabled={!contiguous} onClick={()=>applyHouse(String(n))}><span className="house-icon">{n}</span></ScoreButton>)}
    <ScoreButton label="Eget husnummer" disabled={!contiguous} onClick={()=>openContext('house')}><span className="house-icon">⌝</span></ScoreButton>
    <ScoreButton label="Ta bort hus" disabled={!houseSpans(song!,selection.section).some(v=>selection.bars.some(n=>n>=v.start&&n<=v.end))} onClick={()=>run(s=>clearHouse(s,selection.section,selection.bars))}><Eraser/></ScoreButton><span className="score-divider"/>
    <ScoreButton label={activeBar?.radbrytning?'Ta bort radbrytning':'Ny rad'} onClick={()=>run(s=>patchBar(s,{section:selection.section,bar:selection.bars[0]},{radbrytning:activeBar?.radbrytning?undefined:true}))}><CornerDownLeft/></ScoreButton>
    <ScoreButton label={activeBar?.sidbrytning?'Ta bort sidbrytning':'Ny sida'} onClick={()=>run(s=>patchBar(s,{section:selection.section,bar:selection.bars[0]},{sidbrytning:activeBar?.sidbrytning?undefined:true}))}><FileDown/></ScoreButton>
    <ScoreButton label="Taktnummer och kolumn" disabled={!single} onClick={()=>openContext('layout')}><Hash/></ScoreButton>
    <ScoreButton label="Anvisning" disabled={!single} onClick={()=>openContext('instruction')}><Type/></ScoreButton>
    <ScoreButton label={activeBar?.break?'Ta bort BREAK':'BREAK'} disabled={!single} onClick={()=>activeBar?.break?patch({break:undefined},undefined):feature('break')}><CirclePause/></ScoreButton>
    <ScoreButton label={activeBar?.coda==='mal'?'Ta bort coda':'Coda'} disabled={!single} onClick={()=>patch({coda:activeBar?.coda==='mal'?undefined:'mal'},undefined)}><span className="music-icon">⊕</span></ScoreButton>
    <ScoreButton label="Till coda" disabled={!single} onClick={()=>patch({coda:activeBar?.coda==='hopp'?undefined:'hopp'},undefined)}><Flag/></ScoreButton>
    <ScoreButton label="Segno" disabled={!single} onClick={()=>patch({segno:activeBar?.segno?undefined:true},undefined)}><span className="music-icon">𝄋</span></ScoreButton>
    <ScoreButton label="Slut" disabled={!single} onClick={()=>patch({slut:activeBar?.slut?undefined:true},undefined)}><CircleStop/></ScoreButton>
  </div></div>:null;
  const chordActions=single&&chosen!==undefined?<div className="score-action-card chord-actions" role="group" aria-label={barTarget?.variant===undefined?'Ackordverktyg':'Variantackordverktyg'}><div className="score-scope">{barTarget?.variant===undefined?'':'Variant · '}{activeTokens[chosen]} <span>Placering på slag {song&&barTarget?startsFor(song,barTarget)[chosen]:''}<small className="action-scroll-hint"> ↔ {small?'Svep':'Rulla'}</small></span></div><div className="score-action-strip">
    <ScoreButton label="Flytta ackord åt vänster" disabled={nextPosition(-1)===undefined} onClick={()=>step(-1)}><ArrowLeft/></ScoreButton><ScoreButton label="Flytta ackord åt höger" disabled={nextPosition(1)===undefined} onClick={()=>step(1)}><ArrowRight/></ScoreButton>
    <select aria-label="Notvärde för ackordets placeringssteg" value={resolution} onChange={e=>setResolution(Number(e.target.value))}>{[4,8,16].map(n=><option key={n} value={n}>1/{n}</option>)}</select><span className="score-divider"/>
    <ScoreButton label="Skriv ackord" onClick={()=>barTarget&&begin(barTarget,barTarget.variant===undefined?'chords':'variant')}><Pencil/></ScoreButton>
    <ScoreButton label={barTarget?.variant===undefined?'Variantackord':'Variantens spelomgång'} onClick={()=>barTarget?.variant===undefined?createVariant():openContext('variant')}><GitBranch/></ScoreButton>
    {barTarget?.variant!==undefined&&<ScoreButton label="Variantens rytm" active={context==='variant-rhythm'} onClick={()=>openContext('variant-rhythm')}><Music2/></ScoreButton>}
    <ScoreButton label="Lägg till ackord" onClick={()=>openContext('recent')}><Plus/></ScoreButton>
    <ScoreButton label="Inom parentes" active={activeTokens[chosen]?.startsWith('(')} onClick={()=>{const v=activeTokens[chosen];editOne(v.startsWith('(')&&v.endsWith(')')?v.slice(1,-1):'('+v+')');}}><Parentheses/></ScoreButton>
    <ScoreButton label="N.C." onClick={()=>editOne('N.C.')}><span className="music-icon">N.C.</span></ScoreButton>
    <ScoreButton label="Ordning och startpunkter" onClick={()=>openContext('order')}><ArrowUp/></ScoreButton>
    <ScoreButton label="Ta bort ackord" onClick={()=>editOne(null)}><X/></ScoreButton>
    {barTarget?.variant===undefined&&<><span className="score-divider"/><ScoreButton label="Föruttag" onClick={()=>patch({rytm:undefined,synkop:activeBar?.synkop?.typ==='foruttag'?undefined:{typ:'foruttag',ackord:chosen+1}},undefined)}><span className="music-icon">♪⌒</span></ScoreButton><ScoreButton label="Synkop" onClick={()=>patch({rytm:undefined,synkop:activeBar?.synkop?.typ==='offbeat'?undefined:{typ:'offbeat',ackord:chosen+1}},undefined)}><Music2/></ScoreButton><ScoreButton label="Fermat" onClick={()=>patch({fermat:activeBar?.fermat===chosen+1?undefined:chosen+1},undefined)}><span className="music-icon">◠</span></ScoreButton></>}
  </div></div>:null;
  const partActions=selection&&selection.kind!=='bar'?<div className="score-action-card part-actions"><div className="score-scope">{selection.kind==='reuse'?'Återanvänd ':''}{song?.delar[selection.section].ateranvand??song?.delar[selection.section].namn}<span className="action-scroll-hint">↔ {small?'Svep':'Rulla'}</span></div><div className="score-action-strip">
    {selection.kind==='section'?<><ScoreButton label="Ändra titel" onClick={()=>begin({section:selection.section,bar:0},'name')}><Pencil/></ScoreButton><ScoreButton label="Återanvänd" onClick={()=>run(s=>reuseSection(s,selection.section),null)}><Repeat2/></ScoreButton><ScoreButton label="Duplicera del" onClick={()=>run(s=>copySection(s,selection.section),null)}><Copy/></ScoreButton><ScoreButton label="Ny del" onClick={()=>run(s=>copySection(s,selection.section,true),null)}><FilePlus2/></ScoreButton></>:<><ScoreButton label="Återanvänd del" onClick={()=>openContext('reuse')}><Settings2/></ScoreButton><ScoreButton label="Visa original" onClick={()=>{const original=song!.delar.findIndex(p=>!p.ateranvand&&p.namn===song!.delar[selection.section].ateranvand);setSelection({kind:'section',section:original});setContext('');requestAnimationFrame(()=>stack.current?.querySelector(`.section-hit[data-section="${original}"]`)?.scrollIntoView({block:'nearest'}));}}><Eye/></ScoreButton><ScoreButton label="Gör till egen del" onClick={()=>run(s=>copySection(s,selection.section,false,true),null)}><Unlink/></ScoreButton></>}
    <ScoreButton label="Flytta del upp" disabled={selection.section===0} onClick={()=>run(s=>moveSection(s,selection.section,-1),null)}><ArrowUp/></ScoreButton><ScoreButton label="Flytta del ned" disabled={selection.section===(song?.delar.length??0)-1} onClick={()=>run(s=>moveSection(s,selection.section,1),null)}><ArrowDown/></ScoreButton>
    <ScoreButton label={selection.kind==='reuse'?'Ta bort återanvändning':'Ta bort delen'} onClick={()=>{const part=song!.delar[selection.section],hasMusic=!!part.anvisning||!!part.sidbrytning||!!part.skuggad||part.ganger>1||part.takter.some(raw=>Object.entries(asBar(raw)).some(([key,value])=>key==='ackord'?!!String(value).trim():value!==undefined&&value!==false&&value!=='')),linked=song!.delar.filter(p=>p.ateranvand===part.namn).length;if(selection.kind==='reuse'||(!hasMusic&&!linked)||window.confirm(`Ta bort ${part.namn}?${linked?' Även '+linked+' återanvändningar tas bort.':''}`))run(s=>removeSection(s,selection.section),null);}}><Trash2/></ScoreButton>
  </div></div>:null;
  function params(){
    if(!song||!selection)return null;const target=barTarget,part=song.delar[selection.section],fields=context==='rhythm'?activeBar:activeFields;
    const heading=<div className="score-param-heading"><strong>{({rhythm:'Rytm i takten','variant-rhythm':'Variantens rytm',variant:'Variantens spelomgång',changes:'Tonart och taktart',order:'Ordning och startpunkter',recent:'Lägg till ackord',house:'Eget husnummer',reuse:'Återanvänd del',layout:'Taktnummer och kolumn',instruction:'Anvisning'} as Record<string,string>)[context]}</strong><ScoreButton label="Stäng parametrar" onClick={()=>setContext('')}><X/></ScoreButton></div>;
    const numberField=(label:string,value:number|undefined,callback:(value:number|undefined)=>void,extra={})=><label className="score-field">{label}<input aria-label={label} type="number" defaultValue={value??''} key={label+selection.section+(target?.bar??'')+(value??'')} onBlur={e=>fieldCommit(e.currentTarget,()=>callback(e.currentTarget.value===''?undefined:Number(e.currentTarget.value)))} {...extra}/></label>;
    if(context==='rhythm'||context==='variant-rhythm'){
      if(!target||!fields)return null;const t=context==='rhythm'?{section:target.section,bar:target.bar}:target,bs=bounds(song,t),notes=fields.rytm??[],grid=Array.from({length:Math.round((bs.end-bs.start)*resolution/bs.denominator)},(_,i)=>bs.start+i*bs.denominator/resolution);
      const apply=(next:RhythmNote[])=>run(s=>patchBar(s,t,{rytm:next.length?next.sort((a,b)=>a.slag-b.slag):undefined,...(t.variant===undefined?{synkop:undefined}:{})}));
      return <>{heading}{t.variant!==undefined&&<p className="score-hint">Variantraden {fields.ackord}</p>}<label className="score-field">Notvärde<select aria-label="Notvärde för nya anslag" value={resolution} onChange={e=>setResolution(Number(e.target.value))}>{[4,8,16].map(n=><option key={n} value={n}>1/{n}</option>)}</select></label><div className="score-beat-grid">{grid.map(n=><button type="button" key={n} className={notes.some(a=>a.slag===n)?'active':''} aria-label={(t.variant===undefined?'Anslag':'Variantens anslag')+' på slag '+n} aria-pressed={notes.some(a=>a.slag===n)} onClick={()=>apply(notes.some(a=>a.slag===n)?notes.filter(a=>a.slag!==n):[...notes,{slag:n,notvarde:resolution as 4|8|16}])}>{n}</button>)}</div>{notes.map((note,i)=><div className="score-beat-row" key={note.slag}><span>Slag {note.slag}</span><select aria-label={`Notvärde för anslag ${note.slag}`} value={note.notvarde} onChange={e=>apply(notes.map((n,index)=>index===i?{...n,notvarde:Number(e.target.value) as RhythmNote['notvarde']}:n))}>{[...new Set([4,8,16,note.notvarde])].map(n=><option key={n} value={n}>1/{n}</option>)}</select><ScoreButton label={`Ta bort anslag ${note.slag}`} onClick={()=>apply(notes.filter((_,j)=>j!==i))}><X/></ScoreButton><input aria-label={`Text under anslag ${note.slag}`} defaultValue={note.text??''} placeholder="Text under noten" onBlur={e=>fieldCommit(e.currentTarget,()=>apply(notes.map((n,j)=>j===i?{...n,text:e.currentTarget.value||undefined}:n)))}/></div>)}<p className="score-hint">Slaget anger placeringen. Notvärdet anger längden.</p></>;
    }
    if(context==='variant'&&target?.variant!==undefined){const v=activeBar!.varianter![target.variant];return <>{heading}<div className="score-two">{numberField('Spelas gång',v.gang,n=>patch({gang:n}),{min:2,max:16})}<label className="score-check"><input type="checkbox" checked={!!v.och_foljande} onChange={e=>patch({och_foljande:e.target.checked||undefined})}/>Även följande gånger</label></div>{v.stamma&&<p className="score-hint">{v.stamma}</p>}<ScoreButton label="Ta bort variantraden" onClick={()=>run(s=>removeVariant(s,target),{kind:'bar',section:target.section,bars:[target.bar]})}><Trash2/></ScoreButton></>;}
    if(context==='changes'&&target){const meter=bounds(song,{section:target.section,bar:target.bar}).meter;return <>{heading}<label className="score-field">Tonart<input aria-label="Tonart i takten" defaultValue={activeBar?.tonart??''} onBlur={e=>fieldCommit(e.currentTarget,()=>patch({tonart:e.currentTarget.value||undefined},undefined))} placeholder="Inget byte"/></label><label className="score-field">Taktart<select aria-label="Taktart i takten" value={activeBar?.taktart??''} onChange={e=>patch({taktart:e.target.value||undefined},undefined)}>{[...new Set(['','4/4','3/4','6/8',meter,activeBar?.taktart??''])].map(n=><option key={n} value={n}>{n||'Inget byte'}</option>)}</select></label></>;}
    if(context==='order'&&target){const starts=startsFor(song,target),bs=bounds(song,target),grid=Array.from({length:Math.ceil((bs.end-bs.start)*resolution/bs.denominator)},(_,i)=>bs.start+i*bs.denominator/resolution);return <>{heading}<label className="score-field">Placeringssteg<select aria-label="Placeringssteg" value={resolution} onChange={e=>setResolution(Number(e.target.value))}>{[4,8,16].map(n=><option key={n} value={n}>1/{n}</option>)}</select></label>{activeTokens.map((name,i)=><div className="score-beat-row" key={i}><span>{name}</span><select aria-label={`${name} börjar på`} value={starts[i]} onChange={e=>run(s=>moveChord(s,target,i,Number(e.target.value)))}>{[...new Set([...grid,starts[i]])].sort((a,b)=>a-b).map(n=><option key={n} value={n}>Slag {n}</option>)}</select><ScoreButton label={`Flytta ${name} före föregående ackord`} disabled={!i} onClick={()=>{run(s=>reorderChord(s,target,i,-1),{kind:'bar',section:target.section,bars:[target.bar],variant:target.variant,chord:i-1});}}><ArrowUp/></ScoreButton></div>)}</>;}
    if(context==='recent')return <>{heading}<div className="score-recent">{[...new Set([...recent,...(song?.delar.flatMap(s=>s.takter.flatMap(raw=>tokens(asBar(raw).ackord)))??[])])].slice(0,12).map(n=><button type="button" key={n} onClick={()=>addRecent(n)} disabled={activeTokens.length>=4}>{n}</button>)}</div></>;
    if(context==='house'&&selection.kind==='bar')return <>{heading}<form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);applyHouse(String(data.get('house')));setContext('');}}><label className="score-field">Husnummer<input name="house" aria-label="Husnummer" defaultValue="1, 2"/></label><ScoreButton label="Lägg till hus" onClick={()=>{const el=document.querySelector<HTMLInputElement>('.score-parameters input[name=house]');if(el){applyHouse(el.value);setContext('');}}}><Check/></ScoreButton></form></>;
    if(context==='reuse')return <>{heading}{numberField('Antal gånger',part.ganger,n=>run(s=>patchSection(s,selection.section,{ganger:n})),{min:1,max:16})}<label className="score-field">Anvisning för denna återkomst<input aria-label="Anvisning för denna återkomst" defaultValue={part.anvisning??''} onBlur={e=>fieldCommit(e.currentTarget,()=>run(s=>patchSection(s,selection.section,{anvisning:e.currentTarget.value})))}/></label></>;
    if(context==='layout')return <>{heading}{numberField('Taktnummer',activeBar?.nummer,n=>patch({nummer:n},undefined),{min:1})}{numberField('Kolumn på utskriften',activeBar?.kolumn===undefined?undefined:activeBar.kolumn+1,n=>patch({kolumn:n===undefined?undefined:n-1},undefined),{min:1,max:4})}</>;
    if(context==='instruction')return <>{heading}<label className="score-field">Anvisning<input aria-label="Anvisning i takten" defaultValue={activeBar?.anvisning??''} onBlur={e=>fieldCommit(e.currentTarget,()=>patch({anvisning:e.currentTarget.value||undefined},undefined))}/></label></>;
    return null;
  }
  const stackWidth=stack.current?.clientWidth??700;
  const start=geometry.bounds?.left??0,available=geometry.bounds?.width??stackWidth;
  const fieldBox=draft?.kind==='name'?geometry.part:geometry.area;
  const fieldStart=small&&geometry.viewport?Math.max(start,geometry.viewport.left+12):start;
  const fieldEnd=small&&geometry.viewport?Math.min(start+available,geometry.viewport.left+geometry.viewport.width-12):start+available;
  const fieldWidth=fieldBox?Math.min(Math.max(1,fieldEnd-fieldStart),small?fieldEnd-fieldStart:Math.max(120,fieldBox.width-6)):0;
  const fieldLeft=fieldBox?Math.max(fieldStart,Math.min(fieldBox.left+3,fieldEnd-fieldWidth)):fieldStart;
  const trackHover=(el:Element)=>{
    const target=el.closest<SVGElement|HTMLLabelElement>('.bar-hit,.bar-number-hit,.chord-hit,.chord-area-hit,.variant-area-hit,.score-bar-check');
    const next=target?{section:Number(target.dataset.section),bar:Number(target.dataset.bar),page:Number(target.dataset.page??target.closest<HTMLElement>('.paper')?.dataset.page)}:null;
    setHovered(old=>old?.section===next?.section&&old?.bar===next?.bar&&old?.page===next?.page?old:next);
  };
  const visibleOverlay=enabled&&!busy&&(previewText===text||!!draft||fastOverlay);
  return <div ref={workspace} onInput={e=>{if(e.target instanceof HTMLInputElement&&e.target.closest('.score-field,.score-beat-row')){onDraftChange(true);}}} onKeyDown={e=>{const input=e.target;if(input instanceof HTMLInputElement&&input.closest('.score-field,.score-beat-row')){if(e.key==='Enter'){e.preventDefault();input.blur();}if(e.key==='Escape'){e.preventDefault();input.value=input.defaultValue;fieldErrors.current.delete(fieldKey(input));paramInvalid.current=fieldErrors.current.size>0;input.blur();setContext('');setError('');}}}} className={`score-workspace ${printPreview?'print-view':''} ${panelOpen?'':'score-panel-collapsed'}`}>
    <section className={`preview-panel score-preview ${!enabled||busy||previewText!==text?'preview-readonly':''}`} aria-label="Förhandsvisning">
      <div className="paper-scroll"><div ref={stack} className={`paper-stack ${zoom==='fit'?'fit-pages':''} ${twoPages&&pages.length>1?'two-pages':''}`} style={zoom==='fit'?undefined:{'--paper-width':`${Number(zoom)*7.94}px`} as React.CSSProperties} onPointerMove={e=>{if(e.pointerType==='mouse'&&e.target instanceof Element)trackHover(e.target);}} onPointerLeave={()=>setHovered(null)} onClick={e=>{if(e.target instanceof Element&&!e.target.closest('.score-overlay'))hit(e.target,false,'pointerType' in e.nativeEvent&&e.nativeEvent.pointerType==='touch');}} onKeyDown={e=>{if((e.key==='Enter'||e.key===' ')&&e.target instanceof Element&&!e.target.closest('.score-overlay')){e.preventDefault();hit(e.target,true);}}}>
        {pages.map((svg,i)=><figure key={i} data-page={i} className="paper" aria-label={`Ackordblad sida ${i+1}`} dangerouslySetInnerHTML={{__html:svg}}/>)}
        {!pages.length&&<div className="preview-empty">{song?'Ritar ditt ackordblad…':'Rätta låtfilen för att visa bladet.'}</div>}
        {visibleOverlay&&<div className="score-overlay">
          {!draft&&geometry.checks.map(({target,number,page,box})=><label className={`score-bar-check ${hovered?.section===target.section&&hovered?.bar===target.bar&&hovered?.page===page?'revealed':''} ${selection?.kind==='bar'&&selection.bars.includes(target.bar)?'touch-eligible':''}`} data-section={target.section} data-bar={target.bar} data-page={page} key={`${target.section}-${target.bar}-${page}`} style={{left:box.left+box.width-24,top:box.top+(box.height-24)/2}}><input aria-label={`Markera takt ${number}`} type="checkbox" checked={selection?.kind==='bar'&&selection.section===target.section&&selection.bars.includes(target.bar)} onChange={e=>checkbox(target,e.target.checked)}/></label>)}
          {!draft&&geometry.chord&&<div className="score-chord-selection" style={scalarStyle(geometry.chord)}/>}
          {draft&&fieldBox&&<div className="score-inline-wrap" style={{left:fieldLeft,top:fieldBox.top+Math.max(0,fieldBox.height-30*fieldBox.scale),width:fieldWidth}}><input id={draft.kind==='name'?'part-name':draft.kind==='variant'?'variant-edit':'score-edit'} ref={input} aria-label={draft.kind==='name'?'Delens namn':draft.kind==='variant'?'Skriv variantackord på bladet':'Skriv ackord på bladet'} className="score-inline-input" style={{fontSize:Math.max(16,fieldBox.scale*(draft.kind==='name'?13:draft.kind==='variant'?16.1:23)),height:Math.max(36,30*fieldBox.scale)}} value={draft.value} autoComplete="off" spellCheck={false} aria-invalid={!!draft.error} onChange={e=>{const next={...draftRef.current!,value:e.target.value,error:''};updateDraft(next);if(next.kind==='variant'){try{change(setChordLine(next.baseText,next.target,next.value),next.group);}catch(error){updateDraft({...next,error:error instanceof Error?error.message:'Kontrollera ackorden.'});}}}} onBlur={e=>{if(e.relatedTarget instanceof Element&&e.relatedTarget.closest('.variant-confirm'))return;setTimeout(()=>{if(draftRef.current&&!input.current?.matches(':focus'))flush();},0);}} onKeyDown={e=>{if(e.nativeEvent.isComposing)return;if(e.key==='Enter'){e.preventDefault();flush();}if(e.key==='Escape'){e.preventDefault();rollback();}}}/>{draft.error&&<p role="alert" className="score-inline-error">{draft.error}</p>}</div>}
        </div>}
      </div></div>
      {visibleOverlay&&!draft&&selection&&<div className="score-context-dock" data-placement={dockPlacement}>
        {selection.kind==='bar'&&selection.chord===undefined&&<p className="score-touch-hint">Tryck på taktnumren för att markera fler.</p>}
        {selection.kind==='bar'?<>{barActions}{chordActions}</>:partActions}
        {!small&&context&&<div className="score-parameters" key={`${selection.section}-${barTarget?.bar}-${barTarget?.variant}-${context}`}>{params()}{error&&<p role="alert" className="score-error">{error}</p>}</div>}
        {error&&!context&&<p role="alert" className="score-error">{error}</p>}
      </div>}
      <div className="score-print-pages">{printPages.map((svg,i)=><div key={i} className="print-paper" dangerouslySetInnerHTML={{__html:svg}}/>)}</div>
      {!song&&<p role="alert" className="parse-error">Låtfilen behöver rättas. Visa låtfilen för att redigera texten.</p>}
    </section>
    <aside className={`score-side-panel ${panelOpen?'open':''}`} aria-label="Globala verktyg"><nav><ScoreButton label="Visa låtform" active={panel==='form'} onClick={()=>{if(flush()!==null)setPanel('form');}}><ListMusic/></ScoreButton><ScoreButton label="Visa låtuppgifter" active={panel==='song'} onClick={()=>{if(flush()!==null)setPanel('song');}}><Type/></ScoreButton><ScoreButton label="Fäll in menykolumn" onClick={()=>setPanelOpen(false)}><X/></ScoreButton></nav><div className="score-side-body"><fieldset className="score-fields" disabled={busy}>
      {panel==='form'?<><h2>Låtform</h2><p className="score-hint">Välj en del för att visa dess verktyg.</p>{song?.spelordning&&<section className="legacy-form"><p className="score-hint">Spelordning: {song.spelordning.map(s=>s.del+(s.ganger>1?' × '+s.ganger:'')).join(' → ')}</p><ScoreButton label="Redigera spelordningen som formblock" onClick={()=>run(s=>inlineLegacyForm(s),null)}><Pencil/></ScoreButton></section>}<ol className="score-form">{song?.delar.map((part,i)=><li key={i} className={part.ateranvand?'reused':''} draggable={!busy&&!song?.spelordning} onDragStart={e=>{if(flush()===null||busy){e.preventDefault();return;}dragSource.current=latest.current;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('application/x-harmis-part',String(i));}} onDragOver={e=>{if(e.dataTransfer.types.includes('application/x-harmis-part'))e.preventDefault();}} onDrop={e=>{e.preventDefault();const value=e.dataTransfer.getData('application/x-harmis-part'),from=Number(value);if(value===''||!Number.isInteger(from)||from===i||busy)return;if(dragSource.current!==latest.current){setError('Låten har ändrats. Välj delen igen.');return;}run(s=>moveSection(s,from,i-from),null);dragSource.current=null;}}><button type="button" onClick={()=>{if(flush()===null)return;setSelection({kind:part.ateranvand?'reuse':'section',section:i});setContext('');if(small)setPanelOpen(false);requestAnimationFrame(()=>stack.current?.querySelector(`.${part.ateranvand?'reuse-hit':'section-hit'}[data-section="${i}"]`)?.scrollIntoView({block:'nearest'}));}}><span>{String(i+1).padStart(2,'0')}</span><strong>{part.ateranvand??part.namn}{part.ganger>1?' × '+part.ganger:''}</strong><small>{part.ateranvand?'Återanvänd del':part.takter.length+' takter'}</small></button></li>)}</ol><ScoreButton label="Ny del" onClick={()=>run(s=>copySection(s,Math.max(0,(song?.delar.length??1)-1),true),null)}><Plus/></ScoreButton></>:<><h2>Låtuppgifter</h2>{song&&[['Titel','titel',song.titel],['Artist','artist',song.artist],['Grundtonart','grundtonart',song.grundtonart],['Grundtaktart','taktart',song.taktart],['Tempo','tempo',song.tempo??''],['Version','version',song.version??''],['Stil','stil',song.stil??''],['Upphov','upphov',song.upphov??'']].map(([label,key,value])=><label className="score-field" key={String(key)+'-'+value}>{label}<input aria-label={String(label)} defaultValue={value} onBlur={e=>fieldCommit(e.currentTarget,()=>{const v=e.currentTarget.value;run(s=>patchSong(s,{[String(key)]:key==='tempo'?(v?Number(v):undefined):v}));})}/></label>)}<label className="score-field">Status<select aria-label="Status" value={song?.status??'utkast'} onChange={e=>run(s=>patchSong(s,{status:e.target.value}))}><option value="utkast">Arbetsutkast</option><option value="granskad">Granskad</option></select></label>{extraSongPanel}{error&&!context&&<p role="alert" className="score-error">{error}</p>}</>}
    </fieldset></div></aside>
    {small&&panelOpen&&<button className="score-panel-scrim" aria-label="Stäng menyn" onClick={()=>setPanelOpen(false)}/>}
    {small&&context&&<dialog className="score-param-dialog score-parameters" ref={popup} onCancel={()=>setContext('')}><fieldset className="score-fields" disabled={busy}>{params()}{error&&<p role="alert" className="score-error">{error}</p>}</fieldset></dialog>}
    {confirmVariant&&<dialog ref={variantDialog} className="variant-confirm" onCancel={()=>{setConfirmVariant(false);input.current?.focus();}}><h2>Variantackord behöver ett val</h2><p>Grundackorden ändras. Ska varianterna behållas?</p>{draft?.error&&<p role="alert" className="score-error">{draft.error}</p>}<div><button type="button" className="button secondary" onClick={()=>flush('keep')}>Behåll varianter</button><button type="button" className="button secondary" onClick={()=>flush('remove')}>Ta bort berörda varianter</button><button type="button" className="button secondary" onClick={()=>{setConfirmVariant(false);input.current?.focus();}}>Återgå till texten</button></div></dialog>}
  </div>;
});
